<?php
use \Welfony\Utility\Util;

$this->headLink()
     ->appendStylesheet(Util::baseAssetUrl('js/vendor/umeditor/1.2.2/themes/default/css/umeditor.min.css'));

$this->headScript()
     ->appendFile(Util::baseAssetUrl('js/vendor/umeditor/1.2.2/umeditor.config.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/umeditor/1.2.2/umeditor.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/umeditor/1.2.2/lang/zh-cn/zh-cn.js'));
?>
<div class="m-form">
    <form id="frm-goods-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">商品名称：</label>
                <div class="ipt">
                    <input id="goodsname" type="text"  datatype="*" value="<?php echo $this->goodsInfo['Name']; ?>"  errormsg="名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">关键词：</label>
                <div class="ipt">
                    <input id="goodskeywords" type="text"   value="<?php echo $this->goodsInfo['Keywords']; ?>"  class="u-ipt"/>
                    <p>每个关键词最长为15个字符，超过后系统不予存储</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">沙龙：</label>
                <div class="ipt">
                    <ul class="ipt-mul-select">
                        <?php foreach( $this->companies as $company) : ?>
                        <li><label><input type="checkbox" name="company[]" value="<?php echo $company['CompanyId']; ?>" <?php echo in_array($company['CompanyId'], $this->goodscompanies)? 'checked':'' ?> ><?php echo $company['Name']; ?></label></li>
                        <?php endforeach; ?>

                    </ul>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">分类：</label>
                <div class="ipt">
                    <ul class="ipt-mul-select">
                        <?php foreach( $this->categories as $category) : ?>
                        <li><label><input type="checkbox" name="category[]" value="<?php echo $category['CategoryId']; ?>" <?php echo in_array($category['CategoryId'], $this->goodscategories)? 'checked':'' ?> ><?php echo $category['Name']; ?></label></li>
                        <?php endforeach; ?>

                    </ul>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">是否上架：</label>
                <div class="ipt">
                     <span class="u-btns" data-type="radio">
                        <span class="u-btn <?php echo $this->goodsInfo['DownTime']? 'u-btn-c4': 'u-btn-c3'; ?>" data-value="1" >是</span>
                        <span class="u-btn <?php echo $this->goodsInfo['DownTime']? 'u-btn-c3': 'u-btn-c4'; ?>" data-value="0" >否</span>
                    </span>
                    <p></p>
                </div>
            </div>
            <div>
                <label class="lab">附属数据：</label>
                <div class="ipt">
                    <table class="m-table small-tbl" id="extenddata" style="width:485px;">
                        <thead>
                            <tr>
                                <th class="cola">购买成功增加积分</th>
                                <th class="cola">排序</th>
                                <th class="cola">计量单位</th>
                                <th class="cola">购买成功增加经验值</th>
                            </tr>
                        </thead>
                        <tbody>
                            <td><input id="point" type="text" value="<?php echo $this->goodsInfo['Point']? $this->goodsInfo['Point']: '0'; ?>"  class="u-ipt"/></td>
                            <td><input id="sort" type="text" value="<?php echo $this->goodsInfo['Sort']? $this->goodsInfo['Sort']: '99'; ?>" class="u-ipt"/></td>
                            <td><input id="unit" type="text" value="<?php echo $this->goodsInfo['Unit']? $this->goodsInfo['Unit']: '千克'; ?>" class="u-ipt"/></td>
                            <td><input id="experience" type="text" value="<?php echo $this->goodsInfo['Experience']? $this->goodsInfo['Experience']: '0'; ?>"  class="u-ipt"/></td>
                        </tbody>
                    </table>
                    <br/>
                </div>
            </div>

             <div>
                <label class="lab">基本数据：</label>
                <div class="ipt">
                    <?php if( empty($this->products)) :?>
                    <table class="m-table small-tbl" id="basicdatatable" style="width:550px;">
                        <thead>
                            <tr>
                                <th class="cola">商品货号</th>
                                <th class="cola">库存</th>
                                <th class="cola">市场价格</th>
                                <th class="cola">销售价格</th>
                                <th class="cola">成本价格</th>
                                <th class="cola">重量</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input name="goodsno"  type="text" value="<?php echo $this->goodsInfo['GoodsNo'] ? : $this->defaultgoodsno; ?>"  class="u-ipt"/></td>
                                <td><input name="storenums" type="text" value="<?php echo $this->goodsInfo['StoreNums'] ? : 100; ?>"  class="u-ipt"/></td>
                                <td><input name="marketprice" type="text" value="<?php echo $this->goodsInfo['MarketPrice'] ? : '0.00'; ?>"  class="u-ipt"/></td>
                                <td><input name="sellprice" type="text" value="<?php echo $this->goodsInfo['SellPrice'] ? : '0.00'; ?>" class="u-ipt"/></td>
                                <td><input name="costprice" type="text" value="<?php echo $this->goodsInfo['CostPrice'] ? : '0.00'; ?>"  class="u-ipt"/></td>
                                <td><input name="weight" type="text" value="<?php echo $this->goodsInfo['Weight'] ? : '0'; ?>"  class="u-ipt"/></td>
                            </tr>
                        </tbody>
                    </table>
                    <?php else: ?>

                     <table class="m-table small-tbl hasspecs" id="basicdatatable" style="width:550px;" specarray='<?php echo $this->goodsInfo['SpecArray'];?>'>
                        <thead>
                            <tr>
                                <th class="cola">商品货号</th>
                                <th class="cola"><?php echo json_decode($this->products[0]['SpecArray'], true)['Name']; ?></th>
                                <th class="cola">库存</th>
                                <th class="cola">市场价格</th>
                                <th class="cola">销售价格</th>
                                <th class="cola">成本价格</th>
                                <th class="cola">重量</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach( $this->products as $product) :?>
                            <?php $specrow = json_decode($product['SpecArray'], true); ?>
                            <tr spec-id="<?php echo $specrow['Id']; ?>" spec-value="<?php echo $specrow['Value']; ?>">
                                <td><input name="goodsno"  type="text" value="<?php echo $product['ProductsNo']; ?>"  class="u-ipt"/></td>
                                <td><?php echo $specrow['Value']; ?><input type=hidden name="spec" value='<?php echo $product['SpecArray']; ?>'></td>
                                <td><input name="storenums" type="text" value="<?php echo $product['StoreNums']; ?>"  class="u-ipt"/></td>
                                <td><input name="marketprice" type="text" value="<?php echo $product['MarketPrice']; ?>"  class="u-ipt"/></td>
                                <td><input name="sellprice" type="text" value="<?php echo $product['SellPrice']; ?>"  class="u-ipt"/></td>
                                <td><input name="costprice" type="text" value="<?php echo $product['CostPrice']; ?>"  class="u-ipt"/></td>
                                <td><input name="weight" type="text" value="<?php echo $product['Weight']; ?>"  class="u-ipt"/></td>
                            </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>

                    <?php endif; ?>
                </div>
            </div>
             <div class="formitm">
                <label class="lab"> 添加规格： </a></label>
                <div class="ipt">
                    <a class="t-action" id="btnAddSpec"><i class="iconfont">&#xf0175;</i>添加规格值</a>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">商品模型：</label>
                <div class="ipt">
                     <select id="goodsmodel"  class="u-sel">
                        <option value="0" >通用模型</option>
                        <?php foreach( $this->models as $model) :?>
                        <option value="<?php echo $model['ModelId']; ?>"  <?php echo $this->goodsInfo['ModelId'] == $model['ModelId']? 'selected':''; ?>><?php echo $model['Name']; ?></option>
                        <?php endforeach;?>
                     </select>
                     <p></p>
                </div>
            </div>
            <?php if( empty($this->goodsattributes)) :?>
            <div class="formitm" id="attributepanel" style="display:none;">
                <label class="lab">扩展属性：</label>
                <div class="ipt">
                     <table class="m-table" id="attributestable" style="width:600px;">
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php else: ?>
            <div class="formitm hasattribute" id="attributepanel">
                <label class="lab">扩展属性：</label>
                <div class="ipt">
                     <table class="m-table" id="attributestable" style="width:600px;">
                        <tbody>
                        <?php foreach( $this->goodsattributes as $attribute): ?>
                        <tr><th><?php echo $attribute['Name']; ?></th>
                            <td attr-type='<?php echo $attribute['Type']; ?>' attr-id='<?php echo $attribute['AttributeId']; ?>'>
                                <?php if($attribute['Type'] == '1'): ?>
                                    <?php foreach( explode(',',$attribute['Value']) as $val): ?>
                                    <label class="attr"><input class="attribute" <?php echo $val == $attribute['AttributeValue'] ? 'checked' :''; ?> type="radio" value="<?php echo $val; ?>"><?php echo $val; ?></label>
                                    <?php endforeach; ?>
                                <?php elseif($attribute['Type'] == '2') :?>
                                    <?php foreach( explode(',',$attribute['Value']) as $val): ?>
                                    <label class="attr"><input class="attribute" type="checkbox" <?php echo in_array($val,explode(',',$attribute['AttributeValue'])) ? 'checked' :''; ?> value="<?php echo $val; ?>" ><?php echo $val; ?></label>
                                    <?php endforeach; ?>
                                <?php elseif($attribute['Type'] == '3') :?>
                                    <select class='attribute'>
                                        <?php foreach( explode(',',$attribute['Value']) as $val): ?>
                                        <option value="<?php echo $val; ?>" <?php echo $val == $attribute['AttributeValue'] ? 'selected' :''; ?>><?php echo $val; ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php endif; ?>
             <div class="formitm">
                <label class="lab">商品推荐类型：</label>
                <div class="ipt">
                    <label class="attr"><input type="checkbox" value="1" <?php echo in_array("1", $this->recommends) ? 'checked':''; ?> name="goods_commend[]">最新商品</label>
                    <label class="attr"><input type="checkbox" value="2" <?php echo in_array("2", $this->recommends)? 'checked':''; ?> name="goods_commend[]">特价商品</label>
                    <label class="attr"><input type="checkbox" value="3" <?php echo in_array("3", $this->recommends) ? 'checked':''; ?> name="goods_commend[]">热卖商品</label>
                    <label class="attr"><input type="checkbox" value="4" <?php echo in_array("4", $this->recommends) ? 'checked':''; ?> name="goods_commend[]">推荐商品</label>
                </div>
            </div>
              <div class="formitm">
                <label class="lab">商品品牌：</label>
                <div class="ipt">
                     <select id="goodsbrand"  class="u-sel">
                        <option value="0" >请选择</option>
                        <?php foreach( $this->brands as $brand) :?>
                        <option value="<?php echo $brand['BrandId']; ?>" <?php echo $this->goodsInfo['BrandId'] == $brand['BrandId']? 'selected':''; ?>><?php echo $brand['Name']; ?></option>
                        <?php endforeach;?>
                     </select>
                     <p></p>
                </div>
            </div>

            <div class="formitm">
                <label class="lab">产品相册：</label>
                <div class="ipt">
                    <span class="u-img2">
                        <a href="javascript:;">
                            <img id="goods-image" src="<?php echo $this->goodsInfo['Img']? $this->goodsInfo['Img']:''; ?>"  alt="">
                            <input id="goods-url" type="hidden" name="goods_url" value="<?php echo $this->goodsInfo['Img']? $this->goodsInfo['Img']:''; ?>" />
                        </a>
                    </span>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"></label>
                <div class="ipt">
                    <div id="goods-uploader"></div>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">图文详情：</label>
                <div class="ipt">
                    <div id="goods-editor" style="width: 80%; height: 600px;">
                        <?php echo $this->goodsInfo['Content']; ?>
                    </div>
                </div>
            </div>


            <div class="formitm formitm-1">
                <input type="hidden" name="goods_id" value="<?php echo intval($this->goodsInfo['GoodsId']); ?>" />
                <input type="hidden" id="goodsno" name="goodsno" value="<?php echo $this->defaultgoodsno; ?>"/>
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<div id="specList" style="display:none;" title="规格列表">

</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/goods-info.js'); ?>"></script>