<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-goods-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">商品名称：</label>
                <div class="ipt">
                    <input id="goodsname" type="text"  datatype="*" value="<?php echo $this->goodsInfo['Name']; ?>"  errormsg="名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">关键词：</label>
                <div class="ipt">
                    <input id="goodskeywords" type="text"  datatype="s*" value="<?php echo $this->goodsInfo['Keywords']; ?>"  class="u-ipt"/> 
                    <p>每个关键词最长为15个字符，超过后系统不予存储</p>
                </div>
            </div>  
             <div class="formitm">
                <label class="lab">分类：</label>
                <div class="ipt">
                    <ul class="ipt-mul-select">
                        <?php foreach( $this->categories as $category) : ?>
                        <li><label><input type="checkbox" name="category[]" value="<?php echo $category['CategoryId']; ?>" ><?php echo $category['Name']; ?></label></li>
                        <?php endforeach; ?>

                    </ul>
                </div>
            </div>    
            <div class="formitm">
                <label class="lab">是否：</label>
                <div class="ipt">
                     <span class="u-btns" data-type="radio">
                        <span class="u-btn u-btn-c3" data-value="1" >是</span>
                        <span class="u-btn u-btn-c4" data-value="0" >否</span>
                    </span>
                    <p></p>
                </div>
            </div>
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="goods_id" value="<?php echo intval($this->goodsInfo['GoodsId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/goods-info.js'); ?>"></script>