<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-goods-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">商品名称：</label>
                <div class="ipt">
                    <input id="goodsname" type="text"  datatype="*" value="<?php echo $this->goodsInfo['Name']; ?>"  errormsg="名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">关键词：</label>
                <div class="ipt">
                    <input id="goodskeywords" type="text"  datatype="s*" value="<?php echo $this->goodsInfo['Keywords']; ?>"  class="u-ipt"/> 
                    <p>每个关键词最长为15个字符，超过后系统不予存储</p>
                </div>
            </div>  
             <div class="formitm">
                <label class="lab">分类：</label>
                <div class="ipt">
                    <ul class="ipt-mul-select">
                        <?php foreach( $this->categories as $category) : ?>
                        <li><label><input type="checkbox" name="category[]" value="<?php echo $category['CategoryId']; ?>" ><?php echo $category['Name']; ?></label></li>
                        <?php endforeach; ?>

                    </ul>
                </div>
            </div>    
            <div class="formitm">
                <label class="lab">是否上架：</label>
                <div class="ipt">
                     <span class="u-btns" data-type="radio">
                        <span class="u-btn u-btn-c3" data-value="1" >是</span>
                        <span class="u-btn u-btn-c4" data-value="0" >否</span>
                    </span>
                    <p></p>
                </div>
            </div>
            <div>
                <label class="lab">附属数据：</label>
                <div class="ipt">
                    <table class="m-table small-tbl" id="spectable" style="width:485px;">
                        <thead>
                            <tr>
                                <th class="cola">购买成功增加积分</th>
                                <th class="cola">排序</th>
                                <th class="cola">计量单位</th>
                                <th class="cola">购买成功增加经验值</th>
                            </tr>
                        </thead>
                        <tbody>
                            <td><input name="specval" type="text" value=""  class="u-ipt"/></td>
                            <td><input name="specval" type="text" value="" class="u-ipt"/></td>  
                            <td><input name="specval" type="text" value="" class="u-ipt"/></td>  
                            <td><input name="specval" type="text" value=""  class="u-ipt"/></td>  
                        </tbody>
                    </table>
                    <br/>
                </div>
            </div>

             <div>
                <label class="lab">基本数据：</label>
                <div class="ipt">
                    <table class="m-table small-tbl" id="spectable" style="width:550px;">
                        <thead>
                            <tr>
                                <th class="cola">商品货号</th>
                                <th class="cola">库存</th>
                                <th class="cola">市场价格</th>
                                <th class="cola">销售价格</th>
                                <th class="cola">成本价格</th>
                                <th class="cola">重量</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input name="specval" type="text" value="<?php echo $this->defaultgoodsno; ?>"  class="u-ipt"/></td>
                                <td><input name="specval" type="text" value=""  class="u-ipt"/></td>  
                                <td><input name="specval" type="text" value=""  class="u-ipt"/></td>  
                                <td><input name="specval" type="text" value=""  class="u-ipt"/></td> 
                                <td><input name="specval" type="text" value=""  class="u-ipt"/></td>  
                                <td><input name="specval" type="text" value=""  class="u-ipt"/></td> 
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
             <div class="formitm">
                <label class="lab"> 添加规格： </a></label>
                <div class="ipt">
                    <a class="t-action" id="btnAddSpec"><i class="iconfont">&#xf0175;</i>添加规格值</a>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">商品模型：</label>
                <div class="ipt">
                     <select id="goodsmodel"  class="u-sel">
                        <option value="0" >通用模型</option>
                        <?php foreach( $this->categories as $category) :?>
                        <option value="<?php echo $category['CategoryId']; ?>" ><?php echo $category['Name']; ?></option>  
                        <?php endforeach;?>                       
                     </select>
                     <p></p>
                </div>
            </div>
            <div class="formitm" id="attributepanel" style="display:none;">
                <label class="lab">扩展属性：</label>
                <div class="ipt">
                     <table class="m-table" id="attributestable" style="width:600px;">
                    </table>                    
                </div>
            </div>
             <div class="formitm">
                <label class="lab">商品推荐类型：</label>
                <div class="ipt">
                    <label class="attr"><input type="checkbox" value="1" name="_goods_commend[]">最新商品</label>
                    <label class="attr"><input type="checkbox" value="2" name="_goods_commend[]">特价商品</label>
                    <label class="attr"><input type="checkbox" value="3" name="_goods_commend[]">热卖商品</label>
                    <label class="attr"><input type="checkbox" value="4" name="_goods_commend[]">推荐商品</label> 
                </div>
            </div>
              <div class="formitm">
                <label class="lab">商品品牌：</label>
                <div class="ipt">
                     <select id="goodsbrand"  class="u-sel">
                        <option value="0" >请选择</option>  
                        <?php foreach( $this->brands as $brand) :?>
                        <option value="<?php echo $brand['BrandId']; ?>" ><?php echo $brand['Name']; ?></option>  
                        <?php endforeach;?>                   
                     </select>
                     <p></p>
                </div>
            </div>

            <div class="formitm">
                <label class="lab">产品相册：</label>
                <div class="ipt">
                    <span class="u-img2">
                        <a href="javascript:;">
                            <img id="goods-image" src=""  alt="">
                            <input id="goods-url" type="hidden" name="goods_url" value="" />
                        </a>
                    </span>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"></label>
                <div class="ipt">
                    <div id="goods-uploader"></div>
                </div>
            </div>           
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="goods_id" value="<?php echo intval($this->goodsInfo['GoodsId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<div id="specList" style="display:none;" title="规格列表">

</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/goods-info.js'); ?>"></script>