<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('goods/index/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
      </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">名称</th>
            <th class="cola">分类</th>
            <th class="cola">销售价</th>
            <th class="cola">库存</th>
            <th class="cola">品牌</th>
            <th class="cola">排序</th>
            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
      <?php foreach( $this->rows as $goods) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>
                <a href="<?php echo $this->baseUrl('goods/index/info?goods_id=' .  $goods['GoodsId']); ?>">
                    <?php echo $goods['Name']; ?>
                </a>
            </td>
            <td> <?php echo $goods['CategoryName']; ?></td>
            <td> <?php echo $goods['SellPrice']; ?></td>
            <td> <?php echo $goods['StoreNums']; ?></td>
            <td> <?php echo $goods['BrandName']; ?></td>
            <td><?php echo $goods['Sort']; ?></td>
            <td> 
                <a href="#" href="#" class="btnDelete" data-id="<?php echo $goods['GoodsId']; ?>" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/goods-list.js'); ?>"></script>