<div class="projects">
    <div class="row">
        <div class="side_left span65">
            <div class="sideitem">
                <div id="tbody">
                    <div id="mainbody">
                        <img src="<?php echo $this->staffDetail['ProfileBackgroundUrl'][0]; ?>" width="100%" id="mainphoto" />
                    </div>
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goleft.gif" width="11" height="56" id="goleft" />
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goright.gif" width="11" height="56" id="goright" />
                    <div id="photos">
                        <div id="showArea">
                            <?php foreach ($this->staffDetail['ProfileBackgroundUrl'] as $pic): ?>
                            <img src="<?php echo str_replace('480x480', '110x110', $pic); ?>" rel="<?php echo $pic; ?>" />
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div id="maincontent">
                    </div>
                </div>
                <div class="salonaddress">
                    <h2>
                        <span>
                            沙龙位置
                        </span>
                    </h2>
                    <ul class="clearfix">
                        <li class="addressmap">
                            <input id="latitude" type="hidden" name="latitude" value="<?php echo doubleval($this->staffDetail['Company']['Latitude']); ?>" />
                            <input id="longitude" type="hidden" name="longitude" value="<?php echo doubleval($this->staffDetail['Company']['Longitude']); ?>" />
                            <div id="company-map" class="map"></div>
                        </li>
                        <li class="addresscontent">
                            <h3>
                                <?php echo $this->staffDetail['Company']['Name']; ?>
                            </h3>
                            <p>
                                地址：<?php echo $this->staffDetail['Company']['Address']; ?>
                            </p>
                            <p>
                                电话：<?php echo empty($this->staffDetail['Company']['Mobile']) ? $this->staffDetail['Company']['Tel'] : $this->staffDetail['Company']['Mobile']; ?>
                            </p>
                        </li>
                    </ul>
                </div>
                <div class="sidefunc" style="background: #f8f8f8;">
                    <div class="share">
                        <div class="bdsharebuttonbox">
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                            <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                            <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>
                            <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <?php if (count($this->staffDetail['Services']) > 0): ?>
                <div class="salonaddress">
                    <h2>
                        <span>
                            服务项目
                        </span>
                    </h2>
                    <div style="padding: 10px;">
                      <table class="m-table">
                        <thead>
                            <tr>
                                <th>服务名称</th>
                                <th>原价</th>
                                <th>现价</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->staffDetail['Services'] as $data): ?>
                            <tr>
                                <td>
                                    <?php echo $data['Title']; ?>
                                </td>
                                <td class="col-center">
                                    ￥<?php echo number_format($data['OldPrice'], 2); ?>
                                </td>
                                <td class="col-center">
                                    ￥<?php echo number_format($data['Price'], 2); ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                  </div>
                </div>
                <?php endif; ?>
                <div class="salonaddress">
                    <h2>
                        <span>
                            作品
                        </span>
                    </h2>
                </div>
                <div id="hair-list" class="msgList break-bottom">
                    <?php foreach ($this->staffDetail['Works'] as $work): ?>
                    <div class="span20-8">
                        <div class="col-md-3 box_shadow clearfix">
                            <div class="picbox">
                                <a href="<?php echo $this->baseUrl('hair/index/detail?hair_id=' . $work['WorkId']); ?>">
                                    <img src="<?php echo $work['PictureUrl'][0]; ?>" onerror="this.src='<?php echo $this->config->asset->baseUrl; ?>/img/photo-default.png';" />
                                </a>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="side_right span33">
            <div class="c1">
                <a href="#" class="avatar">
                    <img src="<?php echo $this->staffDetail['AvatarUrl']; ?>" class="picimg">
                    <span class="mask_side">
                    </span>
                </a>
            </div>
            <div class="c2">
                <div class="username">
                    <a href="#">
                        设计师：<?php echo $this->staffDetail['Nickname']; ?>
                    </a>
                </div>
                <div class="opt">
                    <a<?php echo $this->currentUser ? ' id="stylist_appointment" href="#"' : (' href="' . $this->baseUrl('user/auth/signin?continue=' . $this->continueUrl) . '"'); ?> data-stylist-id="<?php echo $this->staffDetail['UserId']; ?>" class="btn btn2_xl btn2_l">
                        <span class="t">
                            预约
                        </span>
                    </a>
                    <a<?php echo $this->currentUser ? ' id="stylist_like" href="#"' : (' href="' . $this->baseUrl('user/auth/signin?continue=' . $this->continueUrl) . '"'); ?> data-stylist-id="<?php echo $this->staffDetail['UserId']; ?>" href="#" class="btn btn2_xl btn2_l btn2_1_l">
                        <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/heart<?php echo $this->staffDetail['IsLiked'] ? '_red' : ''; ?>.png" class="ico">
                        <span class="t">
                            收藏
                        </span>
                    </a>
                </div>
                <div class="data">
                    <span class="count">
                        <?php echo count($this->staffDetail['Works']); ?>作品
                    </span>
                    <span class="spacer">
                        |
                    </span>
                    <span class="count">
                        <?php echo count($this->staffDetail['Services']); ?>服务项目
                    </span>
                </div>
            </div>
            <div class="c3">
                <div class="salonna">
                    沙龙名称：
                    <a href="<?php echo $this->baseUrl('salon/index/detail?salon_id=' . $this->staffDetail['Company']['CompanyId']); ?>">
                        <?php echo $this->staffDetail['Company']['Name']; ?>
                    </a>
                </div>
                <div class="saloninfo">
                    <h3>
                        发型师简介
                    </h3>
                    <p>
                        这家伙什么都没留下...
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=3998daac6ca53a8067263f139b4aadf4"></script>
<script>

window._bd_share_config.common.bdText = "<?php echo $this->staffDetail['Nickname']; ?>";

initSlider();
$(document).ready(function() {
    initAppointment();
    initLike();
    initMap();
    initShare();
});

</script>