<div class="content">
  <div class="search">
    <div class="search_tip">
      <p><span>过滤条件</span></p>
    </div>
    <div class="fliter">
      <div class="fliter_bd">
        <div class="col-md-1 fliter_kind_box" style="border-bottom:none;">
          <div class="a_key">地区:</div>
          <?php
          $params = $this->params;
          $select = isset($params['district']) ? $params['district'] : 0;
          unset($params['district']);
          $qryStr = http_build_query($params);
          ?>
          <ul>
           <li<?php echo $select == 0 ? ' class="select"' : ''; ?>><a href="<?php echo $this->baseUrl('stylist' . (!empty($qryStr) ? '?' . $qryStr : '')); ?>">全部</a></li>
           <?php foreach ($this->districtList as $area): ?>
           <li<?php echo $select == $area['AreaId'] ? ' class="select"' : ''; ?>><a href="<?php echo $this->baseUrl('stylist?district=' . $area['AreaId'] . (!empty($qryStr) ? '&' . $qryStr : '')); ?>"><?php echo $area['Name']; ?></a></li>
           <?php endforeach; ?>
          </ul>
        </div>
      </div>
      <div class="fliter_foot">
       <div class="buttom_tip">
       <?php
        $params = $this->params;
        $select = isset($params['sort']) ? $params['sort'] : 0;
        unset($params['sort']);
        $qryStr = http_build_query($params);
        ?>
        <a href="<?php echo $this->baseUrl('stylist' . (!empty($qryStr) ? '?' . $qryStr : '')); ?>" class="button-strip-item button-strip-item-right<?php echo $select == 0 ? ' button-strip-item-checked' : ''; ?>">默认排序</a>
        <a href="<?php echo $this->baseUrl('stylist?sort=1' . (!empty($qryStr) ? '&' . $qryStr : '')); ?>" class="button-strip-item<?php echo $select == 1 ? ' button-strip-item-checked' : ''; ?>"><span class="button-strip-item_name">离我最近</span><span class="button_arrow_top"></span></a>
        <a href="<?php echo $this->baseUrl('stylist?sort=2' . (!empty($qryStr) ? '&' . $qryStr : '')); ?>" class="button-strip-item<?php echo $select == 2 ? ' button-strip-item-checked' : ''; ?>"><span  class="button-strip-item_name">评分最高</span><span class="button_arrow_down"></span></a>
        <a href="<?php echo $this->baseUrl('stylist?sort=2' . (!empty($qryStr) ? '&' . $qryStr : '')); ?>" class="button-strip-item<?php echo $select == 2 ? ' button-strip-item-checked' : ''; ?>"><span  class="button-strip-item_name">作品数量</span><span class="button_arrow_down"></span></a>
       </div>
      </div>
    </div>
  </div>
  <div class="projects">
    <div class="row card-full">
        <div class="card-container">
        <?php foreach ($this->staffList as $staff): ?>
        <div class="card-list">
            <div class="card-list-inner">
                <div class="card-img">
                    <a href="<?php echo $this->baseUrl('stylist/index/detail?stylist_id=' . $staff['UserId']); ?>">
                        <img src="<?php echo $staff['AvatarUrl']; ?>" onerror="this.src='<?php echo $this->config->asset->baseUrl; ?>/img/photo-default.png';" />
                    </a>
                </div>
                <div class="card-info">
                    <div class="username">
                        <strong>
                            <a href="<?php echo $this->baseUrl('stylist/index/detail?stylist_id=' . $staff['UserId']); ?>"><?php echo $staff['Nickname']; ?></a>
                        </strong>
                    </div>
                    <p class="card-info-first">沙龙：<?php echo $staff['Company']['Name']; ?></p>
                    <div class="card-action-bar">
                        <ul>
                            <li><img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/iconfont-chanpin.png"><span><?php echo $staff['WorkCount']; ?></span></li>
                            <li><img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/iconfont-zan.png"><span><?php echo $staff['RateCount']; ?></span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
        </div>
    </div>
    <?php echo $this->pager; ?>
  </div>
</div>