<div class="content">
  <div class="search">
    <div class="search_tip">
      <p><span>过滤条件</span></p>
    </div>
    <div class="fliter">
      <div class="fliter_bd">
        <div class="col-md-1 fliter_kind_box" style="border-bottom:none;">
          <div class="a_key">地区:</div>
          <ul>
           <li class="select"><a href="#">全部</a></li>
           <li><a href="#">历下区</a></li>
           <li><a href="#">市中区</a></li>
           <li><a href="#">历城</a></li>
           <li><a href="#">长清</a></li>
           <li><a href="#">高新区</a></li>
          </ul>
        </div>
      </div>
      <div class="fliter_foot">
       <div class="buttom_tip">
        <a href="#" class="button-strip-item button-strip-item-right button-strip-item-checked">默认排序</a>
        <a href="#" class="button-strip-item"><span class="button-strip-item_name">离我最近</span><span class="button_arrow_top"></span></a>
        <a href="#" class="button-strip-item"><span  class="button-strip-item_name">评分最高</span><span class="button_arrow_down"></span></a>
        <a href="#" class="button-strip-item"><span  class="button-strip-item_name">作品数量</span><span class="button_arrow_down"></span></a>
       </div>
      </div>
    </div>
  </div>
  <div class="projects">
  </div>
</div>