<?php
use \Welfony\Utility\Util;

$this->headLink()
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.uploadify/3.2.1/jquery.uploadify.css'))
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.imgareaselect/0.9.10/imgareaselect-default.css'));

$this->headScript()
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.validform/5.3.2/jquery.validform.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.uploadify/3.2.1/jquery.uploadify.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.imgareaselect/0.9.10/jquery.imgareaselect.min.js'));
?>
<div class="m-form">
    <form id="frm-coupon-info" method="post">
        <fieldset>
             <div class="formitm">
                <label class="lab">沙龙名称：</label>
                <div class="ipt">
                    <input id="companyname" name="companyname" type="text" value="<?php echo $this->couponInfo['CompanyName']; ?>" datatype="s4-30" errormsg="沙龙名称至少4个字符，最多30个字符！" class="u-ipt"/>
                    <input type="hidden" id="companyid" >
                    <a id="btnSelectCompany" class="u-btn u-btn-c3" >选择沙龙</a>
                    <p></p>
                   
                </div>
            </div>
            <div class="formitm">
                <label class="lab">名称：</label>
                <div class="ipt">
                    <input name="tel" type="text" value="<?php echo $this->couponInfo['CouponName']; ?>" datatype="tel" class="u-ipt"/>
                    <p>设定名称后优惠券标题将优先显示为该名称</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">类型：</label>
                <div class="ipt">
                     <select id="coupon-type"  class="u-sel">
                      <?php foreach( $this->couponTypes as $couponType) :?>
                        <option value="<?php echo $couponType['CouponTypeId']; ?>"><?php echo $couponType['TypeName']; ?></option>
                      <?php endforeach; ?>
                     </select>
                     <div id="coupontype_div1" class="ipt-inner-div">满<input  type="text"  datatype="n" class="u-ipt"/>元 减<input  type="text"  datatype="n" class="u-ipt"/>元</div>
                     <div id="coupontype_div2" class="ipt-inner-div" style="display:none;">金额：<input  type="text"  datatype="n" class="u-ipt"/>元</div>	                     
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">活动券：</label>
                <div class="ipt">
                     <select id="isliveactivity"  class="u-sel">
                        <option value="0">否</option>
                        <option value="1">是</option>
                       
                     </select>
                     <div id="liveactivity_div" class="ipt-inner-div">优惠券数量：<input  type="text" id="liveactiveamount" datatype="n" class="u-ipt"/> 领取地址：<input  type="text"  id='liveactivityaddress' datatype="n" class="u-ipt"/></div>
                     <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">有效期：</label>
                <div class="ipt">
	                     <select id="hasexpire"  class="u-sel">
	                        <option value="1">有限制</option>
                            <option value="0">无限制</option>
	                     </select>
	                     <div id="expiredate_div" class="ipt-inner-div">有效期至：<input  type="text"  id="expiredate"  class="u-ipt inputxt"/> </div>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">领取数量限制：</label>
                <div class="ipt">
	                     <select id="couponamountlimittype"  class="u-sel">
	                     <?php foreach( $this->couponAmountLimitTypes as $couponAmountLimitType) :?>
                            <option value="<?php echo $couponAmountLimitType['CouponAmountTypeId']; ?>"><?php echo $couponAmountLimitType['TypeName']; ?></option>
                          <?php endforeach; ?>
	                     </select>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">领取账户限制：</label>
                <div class="ipt">
	                     <select id="couponaccountlimittype"  class="u-sel">
	                      <?php foreach( $this->couponAccountLimitTypes as $couponAccountLimitType) :?>
                            <option value="<?php echo $couponAccountLimitType['CouponAccountTypeId']; ?>"><?php echo $couponAccountLimitType['TypeName']; ?></option>
                          <?php endforeach; ?>
	                     </select>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">付费：</label>
                <div class="ipt">
	                     <select id="couponpaymenttype"  class="u-sel">
	                      <?php foreach( $this->couponPaymentTypes as $couponPaymentType) :?>
                            <option value="<?php echo $couponPaymentType['CouponPaymentTypeId']; ?>"><?php echo $couponPaymentType['TypeName']; ?></option>
                          <?php endforeach; ?>
	                     </select>
	                     <div id="couponpaymenttype_price_div" class="ipt-inner-div">价格：<input  type="text"  datatype="n" class="u-ipt"/> </div>
	                     <div id="couponpaymenttype_amount_div" class="ipt-inner-div">数量：<input  type="text"  datatype="n" class="u-ipt"/> </div>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">使用说明：</label>
                <div class="ipt">
	                <textarea  type="text"  datatype="n" class="u-ipt"></textarea>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">温馨提示：</label>
                <div class="ipt">
	                <textarea  type="text"  datatype="n" class="u-ipt"></textarea>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">优惠券代码保密：</label>
                <div class="ipt">
	                 <span class="u-btns" data-type="radio">
                        <span class="u-btn u-btn-c3" data-value="1">是</span>
                        <span class="u-btn u-btn-c4" data-value="0">否</span>
                    </span>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">图片：</label>
                <div class="ipt">
                    <span class="u-img2">
                        <a href="javascript:;">
                            <img id="coupon-image" src=""  alt="">
                            <input id="coupon_image_url" type="hidden" name="coupon_image_url" value="" />
                        </a>
                    </span>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"></label>
                <div class="ipt">
                    <div id="coupon-uploader"></div>
                </div>
            </div>
            <div class="formitm formitm-1">
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<div id="companyList" style="display:none;" title="沙龙列表">

</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/coupon-info.js'); ?>"></script>
