<?php
use \Welfony\Utility\Util;
?>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">名称</th>
            <th class="cola">有效期</th>
            <th class="cola">价格</th>
            <th class="cola">数量</th>
            <th class="cola">已领取数量</th>
            <th class="cola">剩余数量</th>
            <th class="cola">激活</th>
            <th class="colb"></th>
        </tr>
    </thead>
    <tbody>
         <?php foreach( $this->rows as $coupon) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>
                <a href="<?php echo $this->baseUrl('coupon/index/info?coupon_id=' .  $coupon['CouponId']); ?>">
                <?php echo $coupon['CouponName']; ?>
                </a>
            </td>
            <td>
                <?php echo $coupon['HasExpire']? $coupon['ExpireDate'] : '无限制'; ?>
            </td>
            <td>
                 <?php echo ( ($coupon['CouponPaymentTypeId'] == 1)? '免费' : ( ($coupon['CouponPaymentTypeId'] == 2)? $coupon['CouponPaymentValue'].'元' : $coupon['CouponPaymentValue'].'积分') ); ?>
            </td>
                
            <td><?php echo $coupon['CouponCodeCount']; ?></td>
            <td><?php echo $coupon['ReceivedCouponCodeCount']; ?></td>
            <td><?php echo intval($coupon['CouponCodeCount'])-intval($coupon['ReceivedCouponCodeCount']); ?></td>
            <td>
               <a class="btnActive" data-id="<?php echo $coupon['CouponId']; ?>" data-status="<?php echo  $coupon['IsActive']; ?>" href="#">
                  <img data-status="1" src="<?php echo  Util::baseAssetUrl('img/status-active.gif'); ?>" style="display:<?php echo  $coupon['IsActive'] ? '': 'none'; ?>;"/>
                  <img data-status="0" src="<?php echo  Util::baseAssetUrl('img/status-inactive.gif'); ?>" style="display:<?php echo $coupon['IsActive']? 'none': ''; ?>;"/>
               </a>
            </td>
            <td><a href="<?php echo $this->baseUrl('coupon/code/search?coupon_id=' .  $coupon['CouponId']. '&coupon_name='.$coupon['CouponName']); ?>">
                    <i class="iconfont">&#x344a;</i>&nbsp;&nbsp;优惠码管理
                </a>
                <a href="#" class="btnDelete" data-id="<?php echo $coupon['CouponId']; ?>">
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/coupon-list.js'); ?>"></script>