<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
      <li>
             <a href="<?php echo $this->baseUrl('coupon/code/search'); ?>">
                <i class="iconfont">&#xf0112;</i>
                返回
            </a>
        </li>
    </ul>
</div>
<div class="m-form">
    <form id="frm-couponcode-info" method="post">
        <table class="m-table" id="tblcoupcode" style="width:600px;">
            <thead>
                <tr>
                    <th class="cola">优惠码</th>
                    <th class="cola">密码</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input name="couponcode" type="text" value="" datatype="s" class="u-ipt"/></td>
                    <td><input name="passcode" type="text" value=""  class="u-ipt"/></td>
                </tr>
                <tr class="actiontr">
                    <td colspan="2" > <a class="t-action"><i class="iconfont">&#xf0175;</i> 增加 </a></td>
                </tr>
            </tbody>
        </table>
        <fieldset>
            <div class="formitm formitm-1">
                <input type="hidden" id="coupon_id" value="<?php echo $this->couponid; ?>">
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/couponcode-info.js'); ?>"></script>
