<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('coupon/code/info?coupon_id='.$this->couponid); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
      </li>
      <li>
             <a href="<?php echo $this->baseUrl('coupon/index/search'); ?>">
                <i class="iconfont">&#xf0112;</i>
                返回
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">名称</th>
            <th class="cola">优惠码</th>
            <th class="cola">密码</th>
            <th class="cola">领取人</th>
            <th class="cola">领取时间</th>
            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
         <?php foreach( $this->rows as $couponcode) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td><?php echo $couponcode['CouponName']; ?></td>
            <td><?php echo $couponcode['Code']; ?></td>
            <td><?php echo $couponcode['PassCode']; ?></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>