<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-category-info" method="post">
      <fieldset>
             <div class="formitm">
                <label class="lab">分类名称：</label>
                <div class="ipt">
                    <input id="categoryname" name="categoryname" type="text" value="<?php echo $this->categoryInfo['Name']; ?>" datatype="s4-30" errormsg="名称至少4个字符，最多30个字符！" class="u-ipt"/>
                    <p>必选项</p>
                   
                </div>
            </div>
            <div class="formitm">
                <label class="lab">上级分类：</label>
                <div class="ipt">
                     <select id="coupon-type"  class="u-sel">
      
                        <option value="0">顶级分类</option>
                     </select>
                                 
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">商品模型：</label>
                <div class="ipt">
                     <select id="coupon-type"  class="u-sel">
      
                        <option value="">选择商品模型</option>
                     </select>
                                 
                    <p>必选项</p>
                </div>
            </div>
          
            <div class="formitm">
                <label class="lab">首页是否显示：</label>
                <div class="ipt">
                     <span class="u-btns" data-type="radio">
                        <span class="u-btn u-btn-c3" data-value="1" >是</span>
                        <span class="u-btn u-btn-c4" data-value="0" >否</span>
                    </span>
                    <p></p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">排序：</label>
                <div class="ipt">
                    <input id="categorysort" name="categorysort" type="text" value="<?php echo $this->categoryInfo['Sort']; ?>" datatype="s*"  class="u-ipt"/>
                    <p></p>
                   
                </div>
            </div>
           
            <div class="formitm formitm-1">
                <input type="hidden" id="categoryid" value="<?php echo $this->categoryInfo['CategoryId']; ?>" >
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/category-info.js'); ?>"></script>