<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('goods/category/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
      </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">名称</th>
            <th class="cola">模型</th>
            <th class="cola">是否首页显示</th>

            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
      <?php if (count($this->rows) > 0): ?>
      <?php foreach( $this->rows as $category) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>
                <a href="<?php echo $this->baseUrl('goods/category/info?category_id=' .  $category['CategoryId']); ?>">
                    <?php echo $category['Name']; ?>
                </a>
            </td>
            <td><?php echo $category['ModelName']; ?></td>
            <td><?php
                echo $category['Visibility']? '是':'否';
            ?></td>
            <td>
                <a href="#" href="#" class="btnDelete" data-id="<?php echo $category['CategoryId']; ?>" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php else: ?>
    <tr>
        <td class="col-center" colspan="5">您还没有添加任何记录</td>
    </tr>
    <?php endif; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/category-list.js'); ?>"></script>