<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-staff-add" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">沙龙：</label>
                <div class="ipt">
                    <input id="company-search" type="text" class="u-ipt"<?php echo $this->companyInfo['CompanyId'] > 0 ? ' style="display: none;"' : '"'; ?>/>
                    <div id="company-search-result" class="autocomplete-search-result"<?php echo $this->companyInfo['CompanyId'] > 0 ? '' : ' style="display: none;"'; ?>>
                        <a class="close"><i class="iconfont">&#xf00b3;</i></a>
                        <a class="autocomplete-item">
                            <img class="autocomplete-item-icon" src="" />
                            <strong class="autocomplete-item-label"><?php echo $this->companyInfo['Name']; ?></strong>
                            <span class="autocomplete-item-detail">
                                <?php echo $this->companyInfo['ProvinceName'] . ' - ' . $this->companyInfo['CityName'] . ' - ' . $this->companyInfo['DistrictName']; ?>
                            </span>
                        </a>
                    </div>
                    <input id="company-search-value" type="hidden" name="company_id" value="<?php echo $this->companyInfo['CompanyId']; ?>" />
                </div>
            </div>
            <div class="formitm">
                <label class="lab">发型师：</label>
                <div class="ipt">
                    <input id="staff-search" type="text" class="u-ipt"/>
                    <div id="staff-search-result" class="autocomplete-search-result" style="display: none;">
                        <a class="close"><i class="iconfont">&#xf00b3;</i></a>
                        <a class="autocomplete-item">
                            <img class="autocomplete-item-icon" src="" />
                            <strong class="autocomplete-item-label"></strong>
                            <span class="autocomplete-item-detail"></span>
                        </a>
                    </div>
                    <input id="staff-search-value" type="hidden" name="staff_id" />
                </div>
            </div>
            <div class="formitm formitm-1">
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/staff-add.js'); ?>"></script>