<?php
use Welfony\Utility\Converter;
?>
<div class="toolbar">
    <ul class="clearfix">
        <?php if ($this->staffInfo['UserId'] > 0): ?>
        <li>
            <a href="<?php echo $this->baseUrl('company/staff/service/info?staff_id=' . $this->staffInfo['UserId']); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
        <?php endif; ?>
        <li>
            <a href="#">
                <i class="iconfont">&#xf013f;</i>
                删除
            </a>
        </li>
    </ul>
</div>

<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input id="chk_all" type="checkbox" /></th>
            <th class="cola">发型师</th>
            <th>服务名称</th>
            <th>原价</th>
            <th>现价</th>
            <th>创建时间</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->dataList) > 0): ?>
        <?php foreach ($this->dataList as $data): ?>
        <tr>
            <td class="col-center"><input name="chk_ids[]" type="checkbox" /></td>
            <td><?php echo $data['Nickname']; ?></td>
            <td>
                <a href="<?php echo $this->baseUrl('company/staff/service/info?staff_id=' . $data['UserId'] . '&service_id=' . $data['ServiceId']); ?>">
                    <?php echo $data['Title']; ?>
                </a>
            </td>
            <td class="col-center">
                <?php echo number_format($data['OldPrice'], 2); ?>
            </td>
            <td class="col-center">
                <?php echo number_format($data['Price'], 2); ?>
            </td>
            <td class="col-center">
                <?php echo date('Y-m-d', strtotime($data['CreatedDate'])); ?>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="6">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->pager; ?>