<?php
use Welfony\Utility\Converter;
use Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <?php if ($this->staffInfo['UserId'] > 0): ?>
        <li>
            <a href="<?php echo $this->baseUrl('company/staff/work/info?staff_id=' . $this->staffInfo['UserId']); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
        <?php endif; ?>
        <li>
            <a id="work-batch-remove" href="#">
                <i class="iconfont">&#xf013f;</i>
                删除
            </a>
        </li>
    </ul>
</div>

<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input id="chk_all" type="checkbox" /></th>
            <th class="cola">发型师</th>
            <th>标题</th>
            <th>性别</th>
            <th>脸型</th>
            <th>发型</th>
            <th>发量</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->dataList) > 0): ?>
        <?php foreach ($this->dataList as $data): ?>
        <tr>
            <td class="col-center"><input name="chk_ids[]" value="<?php echo $data['WorkId']; ?>" type="checkbox" /></td>
            <td><?php echo $data['Nickname']; ?></td>
            <td>
                <a href="<?php echo $this->baseUrl('company/staff/work/info?staff_id=' . $data['UserId'] . '&work_id=' . $data['WorkId']); ?>">
                    <?php echo $data['Title']; ?>
                </a>
            </td>
            <td class="col-center">
                <?php echo $data['Gender'] == 1 ? '男' : '女'; ?>
            </td>
            <td class="col-center">
                <?php
                $faceIdArr = explode(',', $data['Face']);
                foreach ($faceIdArr as $faceId) {
                    $faceNameArr[] = Converter::faceFromEnumToString($faceId);
                }

                echo implode(',', $faceNameArr);
                ?>
            </td>
            <td class="col-center">
                <?php echo Converter::hairStyleFromEnumToString($data['HairStyle']); ?>
            </td>
            <td class="col-center">
                <?php echo Converter::hairAmountFromEnumToString($data['HairAmount']); ?>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="7">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->pager; ?>
<script src="<?php echo Util::baseAssetUrl('js/backend/work-list.js'); ?>"></script>