<?php if ($this->currentUser): ?>
    <?php if ($this->module == 'default'): ?>
    <ul class="lists">
        <li<?php echo ($this->controller == 'index' && $this->action == 'index') ? ' class="active"' : ''; ?>>
            <a href="<?php echo $this->baseUrl(''); ?>">
                <i class="iconfont">&#xf012b;</i>
                后台首页
            </a>
        </li>
        <li></li>
        <li>
            <a href="<?php echo $this->baseUrl(''); ?>">
                <i class="iconfont">&#xf0103;</i>
                支付方式
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl(''); ?>">
                <i class="iconfont">&#xf018d;</i>
                系统设置
            </a>
        </li>
    </ul>
    <?php endif; ?>

    <?php if ($this->module == 'user'): ?>
    <ul class="lists">
        <li<?php echo ($this->controller == 'index' && $this->action == 'search') ? ' class="active"' : ''; ?>>
            <a href="<?php echo $this->baseUrl('user/index/search'); ?>">
                <i class="iconfont">&#x344a;</i>
                会员列表
            </a>
        </li>
        <li<?php echo ($this->controller == 'index' && $this->action == 'info') ? ' class="active"' : ''; ?>>
            <a href="<?php echo $this->baseUrl('user/index/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加会员
            </a>
        </li>
    </ul>
    <?php endif; ?>

    <?php if ($this->module == 'order'): ?>
    <ul class="lists">
        <li>
            <a href="<?php echo $this->baseUrl('user/index/info'); ?>">
                <i class="iconfont">&#x344a;</i>
                订单列表
            </a>
        </li>
    </ul>
    <?php endif; ?>

    <?php if ($this->module == 'goods'): ?>
    <ul class="lists">
        <li>
            <a href="<?php echo $this->baseUrl('goods/index/search'); ?>">商品管理</a>
        </li>
        <?php if ($this->controller == 'index'): ?>
        <li class="sub-menu<?php echo $this->action == 'search' ? ' active' : ''; ?>">
            <a href="<?php echo $this->baseUrl('goods/index/search'); ?>">
                <i class="iconfont">&#x344a;</i>
                商品列表
            </a>
        </li>
        <li class="sub-menu">
            <a href="<?php echo $this->baseUrl('goods/index/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                商品添加
            </a>
        </li>
        <?php endif; ?>
        <li>
            <a href="<?php echo $this->baseUrl('goods/category/search'); ?>">商品分类</a>
        </li>
        <?php if ($this->controller == 'category'): ?>
        <li class="sub-menu">
            <a href="<?php echo $this->baseUrl('goods/category/search'); ?>">
                <i class="iconfont">&#x344a;</i>
                分类列表
            </a>
        </li>
        <li class="sub-menu">
            <a href="<?php echo $this->baseUrl('goods/category/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加分类
            </a>
        </li>
        <?php endif; ?>
        <li>
            <a href="<?php echo $this->baseUrl('goods/brand/categorysearch'); ?>">品牌</a>
        </li>
        <?php if ($this->controller == 'brand'): ?>
        <li class="sub-menu">
            <a href="<?php echo $this->baseUrl('goods/brand/categorysearch'); ?>">
                <i class="iconfont">&#x344a;</i>
                品牌分类
            </a>
        </li>
        <li class="sub-menu">
            <a href="<?php echo $this->baseUrl('goods/brand/search'); ?>">
                <i class="iconfont">&#x344a;</i>
                品牌列表
            </a>
        </li>
        <?php endif; ?>
        <li>
            <a href="<?php echo $this->baseUrl('goods/model/search'); ?>">模型</a>
        </li>
        <?php if ($this->controller == 'model'): ?>
        <li class="sub-menu">
            <a href="<?php echo $this->baseUrl('goods/model/search'); ?>">
                <i class="iconfont">&#x344a;</i>
                模型列表
            </a>
        </li>
        <li class="sub-menu">
            <a href="<?php echo $this->baseUrl('goods/spec/search'); ?>">
                <i class="iconfont">&#x344a;</i>
                规格列表
            </a>
        </li>
        <?php endif; ?>
    </ul>
    <?php endif; ?>
<?php endif; ?>