<?php

$request = Zend_Controller_Front::getInstance()->getRequest();
$module = $request->getModuleName();
$controller = $request->getControllerName();
$action = $request->getActionName();

?>

<?php if ($module == 'default'): ?>
<ul class="lists">
    <li<?php echo ($controller == 'index' && $action == 'index') ? ' class="active"' : ''; ?>>
        <a href="<?php echo $this->baseUrl(''); ?>">
            <i class="iconfont">&#xf012b;</i>
            后台首页
        </a>
    </li>
    <li></li>
    <li>
        <a href="<?php echo $this->baseUrl(''); ?>">
            <i class="iconfont">&#xf0103;</i>
            支付方式
        </a>
    </li>
    <li>
        <a href="<?php echo $this->baseUrl(''); ?>">
            <i class="iconfont">&#xf018d;</i>
            系统设置
        </a>
    </li>
</ul>
<?php endif; ?>

<?php if ($module == 'user'): ?>
<ul class="lists">
    <li<?php echo ($controller == 'index' && $action == 'search') ? ' class="active"' : ''; ?>>
        <a href="<?php echo $this->baseUrl('user/index/search'); ?>">
            <i class="iconfont">&#x344a;</i>
            会员列表
        </a>
    </li>
    <li<?php echo ($controller == 'index' && $action == 'info') ? ' class="active"' : ''; ?>>
        <a href="<?php echo $this->baseUrl('user/index/info'); ?>">
            <i class="iconfont">&#xf0175;</i>
            添加会员
        </a>
    </li>
</ul>
<?php endif; ?>

<?php if ($module == 'order'): ?>
<ul class="lists">
    <li>
        <a href="<?php echo $this->baseUrl('user/index/info'); ?>">
            <i class="iconfont">&#x344a;</i>
            订单列表
        </a>
    </li>
</ul>
<?php endif; ?>

<?php if ($module == 'goods'): ?>
<ul class="submenu">
    <li>
        <span>商品管理</span>
        <ul name="menu">
            <li><a href="/index.php?controller=goods&amp;action=goods_list">商品列表</a></li>
            <li class="selected"><a href="/index.php?controller=goods&amp;action=goods_edit">商品添加</a></li>
        </ul>
    </li>
    <li>
        <span>商品分类</span>
        <ul name="menu">
            <li><a href="/index.php?controller=goods&amp;action=category_list">分类列表</a></li>
            <li><a href="/index.php?controller=goods&amp;action=category_edit">添加分类</a></li>
        </ul>
    </li>
    <li>
        <span>品牌</span>
        <ul name="menu">
            <li><a href="/index.php?controller=brand&amp;action=category_list">品牌分类</a></li>
            <li><a href="/index.php?controller=brand&amp;action=brand_list">品牌列表</a></li>
        </ul>
    </li>
    <li>
        <span>模型</span>
        <ul name="menu">
            <li><a href="/index.php?controller=goods&amp;action=model_list">模型列表</a></li>
            <li><a href="/index.php?controller=goods&amp;action=spec_list">规格列表</a></li>
        </ul>
    </li>
</ul>
<?php endif; ?>