<div class="projects" style="width: 860px; margin: 0 0 0 20px;">
    <div class="row">
        <?php foreach ($this->workList as $work): ?>
        <div class="span21-7">
            <div class="col-md-3 box_shadow clearfix">
                <div class="userBox">
                    <div class=" userPic">
                        <a href="<?php echo $this->baseUrl('stylist/index/detail?stylist_id=' . $work['Staff']['UserId']); ?>"><img src="<?php echo $work['Staff']['AvatarUrl']; ?>"></a>
                    </div>
                    <div class="pannel">
                        <div class="username">
                            <strong>
                                <a href="<?php echo $this->baseUrl('stylist/index/detail?stylist_id=' . $work['Staff']['UserId']); ?>"><?php echo $work['Staff']['Nickname']; ?></a>
                            </strong>
                        </div>
                        <div class="usersalon">沙龙名：<?php echo $work['Staff']['Company']['Name']; ?></div>
                    </div>
                </div>
                <div class="picbox">
                    <a href="<?php echo $this->baseUrl('hair/index/detail?hair_id=' . $work['WorkId']); ?>">
                        <img src="<?php echo $work['PictureUrl'][0]; ?>" onerror="this.src='<?php echo $this->config->asset->baseUrl; ?>/img/photo-default.png';" />
                    </a>
                </div>
                <div class="comtbox" style="text-align: right;">
                    <a style="margin-right: 10px;" class="remove-fav" data-hair-id="<?php echo $work['WorkId']; ?>">
                        <i class="iconfont" title="删除作品">&#xf013f;</i>
                    </a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>