<div class="projects" style="width: 860px; margin: 0 0 0 20px;">
    <div class="row">
        <?php foreach ($this->companyList as $company): ?>
        <div class="span21-7">
            <div class="col-md-3 box_shadow clearfix">
                <div class="userBox">
                    <div class=" userPic">
                        <a href="<?php echo $this->baseUrl('salon/index/detail?salon_id=' . $company['CompanyId']); ?>"><img src="<?php echo $company['LogoUrl']; ?>"></a>
                    </div>
                    <div class="pannel">
                        <div class="username">
                            <strong>
                                <a href="<?php echo $this->baseUrl('salon/index/detail?salon_id=' . $company['CompanyId']); ?>"><?php echo $company['Name']; ?></a>
                            </strong>
                        </div>
                        <div class="usersalon">地址：<?php echo $company['Address']; ?></div>
                    </div>
                </div>
                <div class="picbox">
                    <a href="<?php echo $this->baseUrl('salon/index/detail?salon_id=' . $company['CompanyId']); ?>">
                        <img src="<?php echo $company['PictureUrl'][0]; ?>" onerror="this.src='<?php echo $this->config->asset->baseUrl; ?>/img/photo-default.png';" />
                    </a>
                </div>
                <div class="comtbox" style="text-align: right;">
                    <a style="margin-right: 10px;" class="remove-fav" data-salon-id="<?php echo $company['CompanyId']; ?>">
                        <i class="iconfont" title="删除沙龙">&#xf013f;</i>
                    </a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>