<ul id="tags">
    <li class="tags-h<?php echo $this->action == 'info' ? ' selectTag' : ''; ?>">
        <a href="<?php echo $this->baseUrl('user/salon/info'); ?>">
            沙龙资料
        </a>
    </li>
    <li class="tags-h<?php echo $this->action == 'stylist' ? ' selectTag' : ''; ?>">
        <a href="<?php echo $this->baseUrl('user/salon/stylist'); ?>">
            沙龙发型师
        </a>
    </li>
    <li class="tags-h<?php echo $this->action == 'request' ? ' selectTag' : ''; ?>">
        <a href="<?php echo $this->baseUrl('user/salon/request'); ?>">
            发型师请求
        </a>
    </li>
    <li class="tags-h<?php echo $this->action == 'account' ? ' selectTag' : ''; ?>">
        <a href="<?php echo $this->baseUrl('user/salon/account'); ?>">
            沙龙账户
        </a>
    </li>
</ul>