<div class="projects">
    <div class="row">
        <div class="side_left span65">
            <div class="sideitem">
                <div id="tbody">
                    <div id="mainbody">
                        <img src="<?php echo $this->goodsDetail['PictureUrl'][0]; ?>" width="100%" id="mainphoto" />
                    </div>
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goleft.gif" width="11" height="56" id="goleft" />
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goright.gif" width="11" height="56" id="goright" />
                    <div id="photos">
                        <div id="showArea">
                            <?php foreach ($this->goodsDetail['PictureUrl'] as $pic): ?>
                            <img src="<?php echo str_replace('480x480', '110x110', $pic); ?>" rel="<?php echo $pic; ?>" />
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div id="maincontent">
                    </div>
                </div>
                <?php if (isset($this->goodsDetail['Company'])): ?>
                <div class="salonaddress">
                    <h2>
                        <span>
                            沙龙位置
                        </span>
                    </h2>
                    <ul>
                        <li class="addressmap">
                            <input id="latitude" type="hidden" name="latitude" value="<?php echo doubleval($this->goodsDetail['Company']['Latitude']); ?>" />
                            <input id="longitude" type="hidden" name="longitude" value="<?php echo doubleval($this->goodsDetail['Company']['Longitude']); ?>" />
                            <div id="company-map" class="map"></div>
                        </li>
                        <li class="addresscontent">
                            <h3>
                                <?php echo $this->goodsDetail['Company']['Name']; ?>
                            </h3>
                            <p>
                                地址：<?php echo $this->goodsDetail['Company']['Address']; ?>
                            </p>
                            <p>
                                电话：<?php echo empty($this->goodsDetail['Company']['Mobile']) ? $this->goodsDetail['Company']['Tel'] : $this->goodsDetail['Company']['Mobile']; ?>
                            </p>
                        </li>
                    </ul>
                </div>
                <?php endif; ?>
                <div class="sidefunc">
                    <div class="share">
                        <div class="bdsharebuttonbox">
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                            <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                            <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>
                            <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <?php if (count($this->goodsDetail['Attributes']) > 0): ?>
                <div class="salonaddress">
                    <h2>
                        <span>
                            商品属性
                        </span>
                    </h2>
                    <div style="padding: 10px;">
                      <table class="m-table">
                        <tbody>
                            <?php for ($i = 0; $i < ceil(count($this->goodsDetail['Attributes']) / 2); $i++): ?>
                            <tr>
                                <th style="width: 100px">
                                    <?php echo $this->goodsDetail['Attributes'][$i * 2]['Title']; ?>
                                </th>
                                <td<?php echo isset($this->goodsDetail['Attributes'][$i * 2 + 1]) ? '' : ' colspan="3"'; ?>>
                                    <?php echo $this->goodsDetail['Attributes'][$i * 2]['Value']; ?>
                                </td>
                                <?php if (isset($this->goodsDetail['Attributes'][$i * 2 + 1])): ?>
                                <th style="width: 100px">
                                    <?php echo $this->goodsDetail['Attributes'][$i * 2 + 1]['Title']; ?>
                                </th>
                                <td>
                                    <?php echo $this->goodsDetail['Attributes'][$i * 2 + 1]['Value']; ?>
                                </td>
                                <?php endif; ?>
                            </tr>
                            <?php endfor; ?>
                        </tbody>
                    </table>
                  </div>
                </div>
                <?php endif; ?>
                <div id="comment-list" class="msgList">
                    <ul>
                        <?php foreach ($this->comments as $comment): ?>
                        <li>
                            <div class="sideuser">
                                <div class="userPic">
                                    <a href="#" class="avatar">
                                        <img src="<?php echo str_replace('480x480', '110x110', $comment['CreatedBy']['AvatarUrl']); ?>" />
                                    </a>
                                </div>
                                <div class="pannel">
                                    <div class="username">
                                        <strong>
                                            <a href="#">
                                                <?php echo $comment['CreatedBy']['Nickname']; ?>
                                            </a>
                                        </strong>
                                        <span class="date">
                                            <?php echo date('m月d日 H:i', strtotime($comment['CreatedDate']));?>
                                        </span>
                                    </div>
                                    <div class="mscontent">
                                        <p>
                                            <?php echo $comment['Body']; ?>
                                        </p>
                                        <div class="msconent-img">
                                          <?php if(count($comment['PictureUrl']) > 0): ?>
                                          <?php foreach ($comment['PictureUrl'] as $pic): ?>
                                          <img src="<?php echo str_replace('480x480', '110x110', $pic); ?>" rel="<?php echo $pic; ?>" />
                                          <?php endforeach; ?>
                                          <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="side_right span33">
            <div class="c2">
                <div class="username">
                    <a href="#">
                        <?php echo $this->goodsDetail['Name']; ?>
                    </a>
                </div>
                <div class="opt">
                    <a<?php echo $this->currentUser ? ' id="goods_order" href="#"' : (' href="' . $this->baseUrl('user/auth/signin?continue=' . $this->continueUrl) . '"'); ?> data-goods-id="<?php echo $this->goodsDetail['GoodsId']; ?>" data-company-id="<?php echo isset($this->goodsDetail['Company']) ? $this->goodsDetail['Company']['CompanyId'] : 0; ?>" class="btn btn2_xl btn2_l">
                        <span class="t">
                            购买
                        </span>
                    </a>
                    <a id="stylist_like" href="<?php echo $this->baseUrl('goods/index/content?goods_id=' . $this->goodsDetail['GoodsId']); ?>" class=" btn btn2_xl btn2_l btn2_1_l">
                        <span class="t">
                            图文详情
                        </span>
                    </a>
                </div>
            </div>
            <div class="c3">
                <div class="salonna">
                    价格：
                    <?php
                    $priceList = array();
                    if (isset($this->goodsDetail['Products']) && count($this->goodsDetail['Products'])) {
                        foreach ($this->goodsDetail['Products'] as $prod) {
                            $priceList[] = floatval($prod['Price']);
                        }
                    }

                    if (count($priceList) > 0) {
                        if (max($priceList) > min($priceList)) {
                            $price = '￥' . number_format(min($priceList), 2) . ' - ￥' . number_format(max($priceList), 2);
                        } else {
                            $price = '￥' . number_format($priceList[0], 2);
                        }
                    } else {
                        $price = '￥' . number_format(floatval($this->goodsDetail['SellPrice']), 2);
                    }
                    ?>
                    <span style="font-size: 16px; font-weight: bold; color: red"><?php echo $price; ?></span>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=3998daac6ca53a8067263f139b4aadf4"></script>

<script>

window._bd_share_config.common.bdText = "<?php echo $this->goodsDetail['Name']; ?>";

initSlider();
$(document).ready(function() {
    initLike();
    <?php if (isset($this->goodsDetail['Company'])): ?>
    initMap();
    <?php endif; ?>
    initShare();
    initOrder();
});

</script>