<div class="my_container">
    <div class="my_right g_mc" style="width: 960px;">
        <div id="tagContent">
            <div class="tagContent selectTag" style="padding-left: 0;">
                <div class="grid-button-container">
                    <div class="grid-button full-width">
                        <a href="<?php echo $this->baseUrl(''); ?>">
                            <i class="iconfont">&#xf014e;</i>
                            <h2>出错了，点击回到首页！</h2>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>