<?php
use \Welfony\Utility\Util;

$this->headLink()
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/normalize/1.1.3/normalize.css'))
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.ui/1.9.2/jquery-ui.css'))
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.validform/5.3.2/jquery.validform.css'))
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.uploadify/3.2.1/jquery.uploadify.css'))
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.imgareaselect/0.9.10/imgareaselect-default.css'))
     ->appendStylesheet(Util::baseAssetUrl('css/backend/style.css'));

$this->headScript()
     ->prependFile(Util::baseAssetUrl('js/vendor/jquery.ui/1.9.2/jquery-ui.min.js'))
     ->prependFile(Util::baseAssetUrl('js/vendor/jquery/1.11.0/jquery.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.validform/5.3.2/jquery.validform.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.uploadify/3.2.1/jquery.uploadify.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.imgareaselect/0.9.10/jquery.imgareaselect.min.js'));
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->translate('default_pagetitle_prefix'); ?></title>
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <?php
        echo $this->headLink();
        echo $this->headScript();
        ?>
    </head>
    <body>
        <?php echo $this->partial('header.phtml'); ?>
        <div class="container clearfix">
            <div class="sidebar">
                <?php echo $this->partial('shared/sidebar.phtml'); ?>
            </div>
            <div class="content">
                <div class="content-inner">
                    <div class="content-header">
                        <h3 class="title">
                            <?php echo $this->pageTitle; ?>
                        </h3>
                    </div>
                    <div class="content-body">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->partial('footer.phtml'); ?>
    </body>
</html>