<?php
use \Welfony\Utility\Util;

$this->headLink()
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/normalize/1.1.3/normalize.css'));

$this->headScript()
     ->prependFile(Util::baseAssetUrl('js/vendor/jquery/1.11.0/jquery.min.js'));
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->translate('default_pagetitle_prefix'); ?></title>
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <?php
        echo $this->headLink();
        echo $this->headScript();
        ?>
    </head>
    <body>
        <?php echo $this->partial('header.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->partial('footer.phtml'); ?>
    </body>
</html>