<script>
    var globalSetting = {
        apiBaseUrl: '<?php echo $this->config->api->baseUrl; ?>',
        staticAssetBaseUrl: '<?php echo $this->config->asset->baseUrl; ?>'
    };
</script>
<div class="header container">
    <div class="nav">
        <strong class="brand">
            <a href="<?php echo $this->baseUrl(); ?>">打扮吧后台管理系统</a>
        </strong>
        <?php if ($this->currentUser): ?>
        <div class="lnks clearfix">
            <ul class="lnks-li">
                <li>
                    <a class="lnk<?php echo $this->module == 'user' ? ' on' : ''; ?>" href="<?php echo $this->baseUrl('user/index/search'); ?>">会员</a>
                </li>
                <li>
                    <a class="lnk<?php echo $this->module == 'company' ? ' on' : ''; ?>" href="<?php echo $this->baseUrl('user/index/search'); ?>">沙龙</a>
                </li>
                <li>
                    <a class="lnk<?php echo $this->module == 'goods' ? ' on' : ''; ?>" href="<?php echo $this->baseUrl('goods/index/search'); ?>">商品</a>
                </li>
                <li>
                    <a class="lnk<?php echo $this->module == 'reservation' ? ' on' : ''; ?>" href="#">预约</a>
                </li>
                <li>
                    <a class="lnk<?php echo $this->module == 'order' ? ' on' : ''; ?>" href="<?php echo $this->baseUrl('order/index/search'); ?>">订单</a>
                </li>
                <li>
                    <a class="lnk<?php echo $this->module == 'system' ? ' on' : ''; ?>" href="#">系统</a>
                </li>
                <li class="right">
                    <a class="lnk" href="<?php echo $this->baseUrl('user/auth/signout'); ?>">退出</a>
                </li>
                <li class="right">
                    <a class="lnk" href="javascript:;">当前登录：<?php echo $this->currentUser['Nickname']; ?></a>
                </li>
            </ul>
        </div>
        <?php endif; ?>
    </div>
</div>