<?php
use \Welfony\Utility\Util;
?>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"></th>
            <th >沙龙</th>
            <th style="width:120px;">货号</th>
            <th>名称</th>
            <th >规格</th>
            <th >售价</th>
            <th ></th>
            <th ></th>
        </tr>
    </thead>
    <tbody>
      <?php if (count($this->rows) > 0): ?>
      <?php foreach( $this->rows as $goods) : ?>
      <?php
                    $spc= '';
                    if( $goods['SpecArray'] )
                    {
                        $spec= json_decode($goods['SpecArray'],true);
                        $spc= $spec['Name'].":".$spec['Value'];
                    }

        ?>
        <tr>
            <td class="col-center"><input type="checkbox" data-name="<?php echo $goods['Name'];?>"
                data-goodsid= "<?php echo $goods['GoodsId']; ?>"
                data-productsid = "<?php echo $goods['ProductsId'] ; ?>"
                data-sellprice = "<?php echo $goods['SellPrice']; ?>"
                data-costprice = "<?php echo $goods['CostPrice']; ?>"
                data-weight = "<?php echo $goods['Weight']; ?>"
                data-img= "<?php echo $goods['Img']; ?>"
                data-spec="<?php echo $spc; ?>"
                data-id="<?php echo $goods['GoodsId'].'_'.$goods['ProductsId'];  ?>"
                data-companyid = "<?php echo $goods['CompanyId']; ?>"
                data-companyname = "<?php echo $goods['CompanyName']; ?>"
             /></td>
            <td><?php echo $goods['CompanyName']; ?></td>
            <td>
                    <?php echo isset($goods['ProductsNo'])? $goods['ProductsNo']: $goods['GoodsNo']; ?>
            </td>
            <td> <?php echo $goods['Name']; ?></td>
            <td><?php echo $spc; ?></td>
            <td> <?php echo $goods['SellPrice']; ?></td>
            <td><img style="max-width:100px;max-height:100px;" src="<?php echo $goods['Img']; ?>"/></td>
            <td><img style="max-width:100px;max-height:100px;" src="<?php echo $this->baseUrl('goods/index/qrcode?goodsid=' .  $goods['GoodsId']. '&companyid='.$goods['CompanyId'].'&productsid='.$goods['ProductsId'] ); ?>""/></td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="5">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>