<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('company/index/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
        <li>
            <a href="#">
                <i class="iconfont">&#xf013f;</i>
                删除
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input id="chk_all" type="checkbox" /></th>
            <th class="cola">名字</th>
            <th>地址</th>
            <th>联系电话</th>
            <th class="cola">手机</th>
            <th class="cola">验证</th>
            <th>创建时间</th>
            <th class="cola"></th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->dataList) > 0): ?>
        <?php foreach ($this->dataList as $data): ?>
        <tr>
            <td class="col-center"><input name="chk_ids[]" type="checkbox" /></td>
            <td>
                <a href="<?php echo $this->baseUrl('company/index/info?company_id=' . $data['CompanyId']); ?>">
                    <?php echo $data['Name']; ?>
                </a>
            </td>
            <td>
                <?php echo $data['ProvinceName']; ?> - <?php echo $data['CityName']; ?> - <?php echo $data['DistrictName']; ?>
                <p><?php echo $data['Address']; ?></p>
            </td>
            <td><?php echo $data['Tel']; ?></td>
            <td><?php echo $data['Mobile']; ?></td>
            <td class="col-center">
                <?php echo $data['Status'] == 1 ? '通过' : '未通过'; ?>
            </td>
            <td><?php echo $data['CreatedDate']; ?></td>
            <td>
                <a href="<?php echo $this->baseUrl('company/staff/search?company_id=' . $data['CompanyId']); ?>">
                    <i class="iconfont">&#xf00ec;</i>&nbsp;&nbsp;
                    沙龙成员
                </a>
                <br/>
                <a href="#">
                    <i class="iconfont">&#xf0148;</i>&nbsp;&nbsp;
                    商品
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="8">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->pager; ?>