<?php
use Welfony\Utility\Converter;
use Welfony\Utility\Util;
?>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input id="chk_all" type="checkbox" /></th>
            <th class="cola">沙龙</th>
            <th>数量</th>
            <th>请求时间</th>
            <th>状态</th>
            <th>描述</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->dataList) > 0): ?>
        <?php foreach ($this->dataList as $data): ?>
        <tr>
            <td class="col-center"><input name="chk_ids[]" value="<?php echo $data['WithdrawalId']; ?>" type="checkbox" /></td>
            <td class="cola">
                 <a href="<?php echo $this->baseUrl('company/index/withdrawalinfo?withdrawal_id=' . $data['WithdrawalId']); ?>">
                    <?php echo $data['Name']; ?>
                </a>
            </td>
            <td><?php echo $data['Amount']; ?></td>
            <td><?php echo $data['CreateTime']; ?></td>
            <td class="statusrow"><?php echo $data['Status'] =='0' ? '新建' :($data['Status'] =='1'? '已批准': '已拒绝'); ?></td>
            <td><?php echo $data['Description']; ?></td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="7">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->pager; ?>
<script src="<?php echo Util::baseAssetUrl('js/backend/withdrawal-list.js'); ?>"></script>