<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-withdrawal-info" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">沙龙：</label>
                <div class="ipt">
                   <?php echo $this->withdrawalInfo['Name']; ?> &nbsp;
                </div>
            </div>     
            <div class="formitm">
                <label class="lab">金额：</label>
                <div class="ipt">
                   <?php echo $this->withdrawalInfo['Amount']; ?> &nbsp;
                </div>
            </div>
            <div class="formitm">
                <label class="lab">描述：</label>
                <div class="ipt">
                    <?php echo $this->withdrawalInfo['Description']; ?>&nbsp;
                </div>
            </div>
            <div class="formitm">
                <label class="lab">时间：</label>
                <div class="ipt">
                    <?php echo $this->withdrawalInfo['CreateTime']; ?>&nbsp;
                </div>
            </div>
            <div class="formitm">
                <label class="lab">银行：</label>
                <div class="ipt">
                    <?php echo $this->withdrawalInfo['Bank']; ?>&nbsp;
                </div>
            </div>
            <div class="formitm">
                <label class="lab">开户行：</label>
                <div class="ipt">
                    <?php echo $this->withdrawalInfo['OpenAccountBank']; ?>&nbsp;
                </div>
            </div>
            <div class="formitm">
                <label class="lab">账号：</label>
                <div class="ipt">
                    <?php echo $this->withdrawalInfo['AccountNo']; ?>&nbsp;
                </div>
            </div>
            <div class="formitm">
                <label class="lab">账户名：</label>
                <div class="ipt">
                    <?php echo $this->withdrawalInfo['AccountName']; ?>&nbsp;
                </div>
            </div>
            <div class="formitm">
                <label class="lab">状态：</label>
                <div class="ipt">
                    <?php if( $this->withdrawalInfo['Status'] == '0') :?>
                    <span class="u-btns" data-type="radio">
                        <span class="u-btn u-btn-c<?php echo $this->withdrawalInfo['Status'] == 0 ? '3' : '4'; ?>" data-value="0">新建</span>
                        <span class="u-btn u-btn-c<?php echo $this->withdrawalInfo['Status'] == 1 ? '3' : '4'; ?>" data-value="1">已批准</span>
                        <span class="u-btn u-btn-c<?php echo $this->withdrawalInfo['Status'] == 2 ? '3' : '4'; ?>" data-value="2">已拒绝</span>
                    </span>
                    <?php else: ?>
                        <?php echo $this->withdrawalInfo['Status'] == 1 ? '已批准':'已拒绝'?>
                    <?php endif; ?>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">操作记录：</label>
                <div class="ipt">
                    <?php foreach( $this->logs as $log) :?>
                        <?php echo $log['CreateTime']. ' '. $log['Action']. ' '.$log['Reason']; ?>
                        <br/>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="formitm formitm-1">
                <input type="hidden" id="withdrawal_id" value="<?php echo intval($this->withdrawalInfo['WithdrawalId']); ?>" />
            </div>
            
        </fieldset>
    </form>
</div>
<div id="rejectpopin" style="display:none;">
    <table width="95%" style="margin:10px auto" class="m-table">
       <tbody>

            <tr>
                <th>拒绝理由:</th><td align="left"><input type="text"  value="" id="txtrejectreason"  class="small"></td>
            </tr>
        </tbody>
    </table>
</div>
<div id="approvepopin" style="display:none;">
    <table width="95%" style="margin:10px auto" class="m-table">
       <tbody>

            <tr>
                <th>说明：</th>
                <td align="left" colspan="3">点击批准后，将直接转入到用户的余额中</td>
            </tr>
        </tbody>
    </table>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/withdrawal-info.js'); ?>"></script>