<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-model-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">模型名称：</label>
                <div class="ipt">
                    <input id="modelname" type="text"  datatype="*" value="<?php echo $this->modelInfo['Name']; ?>"  errormsg="品牌名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab"> 添加扩展属性： </a></label>
                <div class="ipt">
                    <a class="t-action" id="btnAddAttribute"><i class="iconfont">&#xf0175;</i>添加扩展属性</a>
                </div>
            </div>
            <div>
                <label class="lab"></label>
                <div class="ipt">
                    <table class="m-table" id="attributetable" style="width:95%;">
                        <thead>
                            <tr>
                                <th class="cola">属性名</th>
                                <th class="cola">操作方式</th>
                                <th class="cola">选择项数据【每项数据之间用逗号','做分割】</th>
                                <th  style="width: 20px;">是否作为商品筛选项</th>
                                <th class="cola">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach( $this->attributes as $attr) : ?>
                        <tr class="attributerow">
                            <td><input name="attributename" type="text" value="<?php echo $attr['Name']; ?>" datatype="s" class="u-ipt"/></td> 
                            <td>
                                     <select name="attributetype"  class="u-sel" > 
                                        <option value="1" <?php echo $attr['Type'] == '1'? 'selected': ''; ?> >单选框</option> 
                                        <option value="2" <?php echo $attr['Type']== '2'? 'selected': ''; ?> >复选框</option> 
                                       <option value="3" <?php echo $attr['Type'] == '3'? 'selected': ''; ?> >下拉框</option>                        
                                     </select> 
                            </td> 
                            <td><input name="attributevalue" type="text" value="<?php echo $attr['Value']; ?>"  class="u-ipt"/></td>
                            <td> <input name="attributesearch" type="checkbox" <?php echo $attr['Search']? 'checked': ''; ?> /></td> 
                            <td><a href="#" class="btnDelete"><i class="iconfont">&#xf013f;</i></a></td>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>

             <div class="formitm">
                <label class="lab"> 添加规格： </a></label>
                <div class="ipt">
                    <a class="t-action" id="btnAddSpec"><i class="iconfont">&#xf0175;</i>添加规格</a>
                </div>
            </div>
            <div>
                <label class="lab"></label>
                <div class="ipt">
                    <table class="m-table" id="spectable" style="width:600px;">
                        <thead>
                            <tr>
                                <th class="cola">名称</th>
                                <th class="cola">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if($this->specs): ?>
                            <?php foreach ($this->specs as  $spec) :?>
                                 <tr class="specid" data-id="<?php echo $spec['SpecId']; ?>">
                                   <td><?php echo $spec['Name']; ?></td>

                                   <td><a href="#" class="btnUp"><i class="iconfont">&#xf0113;</i></a>&nbsp;&nbsp;<a href="#" class="btnDown"><i class="iconfont">&#xf0111;</i></a>&nbsp;&nbsp;<a href="#" class="btnDelete"><i class="iconfont">&#xf013f;</i></a></td>
                                </tr>
                            <?php endforeach;?>
                            <?php endif; ?>
                        </tbody>
                    </table>

                </div>
            </div>
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="model_id" value="<?php echo intval($this->modelInfo['ModelId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<div id="specList" style="display:none;" title="规格列表">

</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/model-info.js'); ?>"></script>