<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-model-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">模型名称：</label>
                <div class="ipt">
                    <input id="modelname" type="text"  datatype="*" value="<?php echo $this->modelInfo['Name']; ?>"  errormsg="品牌名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">添加扩展属性：</label>
                <div class="ipt">
                    <input id="btnaddattribute" type="button"  datatype="*" value="添加扩展属性" />
                </div>
            </div>
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="model_id" value="<?php echo intval($this->modelInfo['ModelId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/model-info.js'); ?>"></script>