<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-model-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">模型名称：</label>
                <div class="ipt">
                    <input id="modelname" type="text"  datatype="*" value="<?php echo $this->modelInfo['Name']; ?>"  errormsg="品牌名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab"> 添加扩展属性： </a></label>
                <div class="ipt">
                    <a class="t-action" id="btnAddSpec"><i class="iconfont">&#xf0175;</i>添加扩展属性</a>
                </div>
            </div>
            <div>
                <label class="lab"></label>
                <div class="ipt">
                    <table class="m-table" id="spectable" style="width:95%;">
                        <thead>
                            <tr>
                                <th class="cola">属性名</th>
                                <th class="cola">操作方式</th>
                                <th class="cola">选择项数据【每项数据之间用逗号','做分割】</th>
                                <th class="cola">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="model_id" value="<?php echo intval($this->modelInfo['ModelId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/model-info.js'); ?>"></script>