<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('goods/model/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
        <li>
            <a href="#">
                <i class="iconfont">&#xf013f;</i>
                删除
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">模型名称</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach( $this->rows as $model) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td><?php echo $model['Name']; ?></td>
            <td><?php  
                $specs = explode(',', $model['SpecIds']);
                $names= array();
                foreach ($specs as $spec) {
                    if( isset($this->allspec[$spec]) )
                    $names[] = $this->allspec[$spec];
                }
                echo implode(',', $names);
            ?>
            </td>
            <td></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>