<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-spec-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">规格名称：</label>
                <div class="ipt">
                    <input id="specname" type="text"  datatype="*" value="<?php echo $this->specInfo['Name']; ?>"  errormsg="规格名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">备注：</label>
                <div class="ipt">
                    <input id="note" type="text" value="<?php echo $this->specInfo['Note']; ?>"   class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"> 添加： </a></label>
                <div class="ipt">
                    <a class="t-action" id="btnAddSpec"><i class="iconfont">&#xf0175;</i>添加规格值</a>
                </div>
            </div>
            <div>
                <label class="lab"></label>
                <div class="ipt">
                    <table class="m-table" id="spectable" style="width:600px;">
                        <thead>
                            <tr>
                                <th class="colb">规格值</th>
                                <th class="cola">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                            if( isset( $this->specInfo['Value'] ) && $this->specInfo['Value'])
                            {
                                $val = json_decode( $this->specInfo['Value']);
                                if($val && is_array($val))
                                {
                                    foreach( $val as $specVal)
                                    {

                                     echo   '   <tr> ' .
                                    '     <td><input name="specval" type="text" value="'.$specVal.'" datatype="s" class="u-ipt"/></td> ' .
                                    '     <td><a href="#" class="btnUp"><i class="iconfont">&#xf0113;</i></a>&nbsp;&nbsp;<a href="#" class="btnDown"><i class="iconfont">&#xf0111;</i></a>&nbsp;&nbsp;<a href="#" class="btnDelete"><i class="iconfont">&#xf013f;</i></a></td>' .
                                    '   </tr>';
                                    }
                                }
                            }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>


            <div class="formitm formitm-1">
                <input type="hidden" name="spec_id" value="<?php echo intval($this->specInfo['SpecId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/spec-info.js'); ?>"></script>