<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-model-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">规格名称：</label>
                <div class="ipt">
                    <input id="specname" type="text"  datatype="*" value="<?php echo $this->specInfo['Name']; ?>"  errormsg="规格名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">备注：</label>
                <div class="ipt">
                    <input id="note" type="text"   class="u-ipt"/> 
                </div>
            </div>
            <div class="formitm">
                <label class="lab"> 添加： </a></label>
                <div class="ipt">
                    <a class="t-action" id="btnAddSpec"><i class="iconfont">&#xf0175;</i>添加规格值</a>
                </div>
            </div>
            <div>
                <label class="lab"></label>
                <div class="ipt">
                    <table class="m-table" id="spectable" style="width:600px;">
                        <thead>
                            <tr>
                                <th class="cola">规格值</th>
                                <th class="cola">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="spec_id" value="<?php echo intval($this->specInfo['ModelId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/spec-info.js'); ?>"></script>