<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('goods/spec/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
      </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">名称</th>
            <th class="cola">显示方式</th>
            <th class="cola">规格数据</th>

            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
      <?php foreach( $this->rows as $spec) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td><?php echo $spec['Name']; ?></td>
            <td>文字</td>
            <td><?php  
                if( isset( $spec['Value'] ) && $spec['Value'])
                {
                    $val = json_decode( $spec['Value']); 
                    if($val && is_array($val))
                    {
                        echo implode(',', $val);
                    }
                }
            ?></td>
            <td> 
                <a href="#" href="#" class="btnDelete" data-id="<?php echo $spec['SpecId']; ?>" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/spec-list.js'); ?>"></script>