<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('goods/spec/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
      </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">名称</th>
            <th class="cola">显示方式</th>
            <th class="cola">规格数据</th>

            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td></td>
            <td></td>
            <td></td>
            <td> 
                <a href="#" class="btnDelete" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>
        </tr>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/spec-list.js'); ?>"></script>