<div class="container">
    <?php
    echo $this->partial('shared/header.phtml', array(
        'module' => $this->module,
        'config' => $this->config,
        'currentUser' => $this->currentUser,
        'userContext' => $this->userContext));
    ?>
</div>
<div class="my_container">
    <?php
    echo $this->partial('shared/leftnav.phtml', array('active' => 4, 'currentUser' => $this->currentUser));
    ?>
    <div class="my_right g_mc">
        <?php
        echo $this->partial('shared/topnavstylist.phtml', array('action' => $this->action));
        ?>
        <div style="padding: 15px 0 0 15px;">
            <div class="toolbar">
                <ul class="clearfix">
                    <li>
                        <a href="<?php echo $this->baseUrl('user/stylist/appointment'); ?>">
                            <i class="iconfont">&#xf0112;</i>
                            返回
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->baseUrl('user/appointment/noteedit?appointment_id=' . $this->appointmentId); ?>">
                            <i class="iconfont">&#xf0175;</i>
                            添加新效果图
                        </a>
                    </li>
                </ul>
            </div>
            <div class="Dynamic_gmc">
                <div id="tagContent0" class="selectTag">
                    <?php foreach ($this->dataList as $note): ?>
                    <div class="Dynamicitem">
                        <div class="photo">
                            <img src="<?php echo $this->userInfo['AvatarUrl']; ?>" class="photoimg">
                            <span class="mask_side_100">
                            </span>
                        </div>
                        <div class="darrow">
                        </div>
                        <div class="dcontent">
                            <div class="dbody">
                                <ul>
                                    <?php if (count($note['PictureUrl']) > 0): ?>
                                    <li>
                                        <?php foreach ($note['PictureUrl'] as $pic): ?>
                                        <img src="<?php echo $pic; ?>"/>
                                        <?php endforeach; ?>
                                    </li>
                                    <?php endif; ?>
                                    <li class="cdetail">
                                        <p>
                                            <?php echo $note['Body']; ?>
                                        </p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="clearfix"></div>
            <?php echo $this->pager; ?>
        </div>
    </div>
</div>