<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-appointment-info" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">发型师：</label>
                <div class="ipt">
                    <input id="staff-search" type="text" class="u-ipt"<?php echo $this->staffInfo['UserId'] > 0 ? ' style="display: none;"' : '"'; ?>/>
                    <div id="staff-search-result" class="autocomplete-search-result"<?php echo $this->staffInfo['UserId'] > 0 ? '' : ' style="display: none;"'; ?>>
                        <?php if ($this->staffInfo['UserId'] <= 0): ?>
                        <a class="close"><i class="iconfont">&#xf00b3;</i></a>
                        <?php endif; ?>
                        <a class="autocomplete-item">
                            <img class="autocomplete-item-icon" src="<?php echo $this->staffInfo['AvatarUrl']; ?>" />
                            <strong class="autocomplete-item-label"><?php echo $this->staffInfo['Nickname']; ?></strong>
                            <span class="autocomplete-item-detail"><?php echo $this->staffInfo['Company']['Name']; ?></span>
                        </a>
                    </div>
                    <input id="staff-search-value" type="hidden" name="staff_id" />
                </div>
            </div>
            <div class="formitm">
                <label class="lab">发型师服务：</label>
                <div class="ipt">
                    <table id="service-list" class="m-table" style="width: 400px;">
                        <thead>
                            <tr>
                                <th class="col-chk"></th>
                                <th class="colb">服务名称</th>
                                <th class="cola">原价</th>
                                <th class="cola">现价</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($this->staffInfo['UserId'] > 0): ?>
                            <?php foreach ($this->staffInfo['Services'] as $service): ?>
                            <tr>
                                <td class="col-center">
                                    <input type="radio" name="service_id" value="<?php echo $service['ServiceId']; ?>" />
                                </td>
                                <td><?php echo $service['Title']; ?></td>
                                <td><?php echo number_format($service['OldPrice'], 2); ?></td>
                                <td><?php echo number_format($service['Price'], 2); ?></td>
                            </tr>
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">预约时间：</label>
                <div class="ipt">
                    <input name="appointment_date" type="text" value="" datatype="m" class="u-ipt datetime"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">预约状态：</label>
                <div class="ipt">
                    <span class="u-btns" data-type="radio">
                        <span class="u-btn u-btn-c<?php echo $this->appointmentInfo['Status'] == 0 ? '3' : '4'; ?>" data-value="0">未付款</span>
                        <span class="u-btn u-btn-c<?php echo $this->appointmentInfo['Status'] == 1 ? '3' : '4'; ?>" data-value="1">已付款</span>
                        <span class="u-btn u-btn-c<?php echo $this->appointmentInfo['Status'] == 2 ? '3' : '4'; ?>" data-value="2">完成</span>
                        <span class="u-btn u-btn-c<?php echo $this->appointmentInfo['Status'] == 3 ? '3' : '4'; ?>" data-value="3">已退款</span>
                        <span class="u-btn u-btn-c<?php echo $this->appointmentInfo['Status'] == 4 ? '3' : '4'; ?>" data-value="4">已取消</span>
                        <input type="hidden" name="status" value="<?php echo $this->appointmentInfo['Status']; ?>" />
                    </span>
                </div>
            </div>
            <div class="formitm formitm-1">
                <input type="hidden" name="company_id" value="<?php echo intval($this->appointmentInfo['CompanyId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/appointment-info.js'); ?>"></script>