<?php
use Welfony\Utility\Converter;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('appointment/index/info' . ($this->staffInfo['UserId'] > 0 ? '?staff_id=' . $this->staffInfo['UserId'] : '')); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input id="chk_all" type="checkbox" /></th>
            <th>服务</th>
            <th class="cola">预约人</th>
            <th>发型师</th>
            <th class="cola">服务费</th>
            <th class="cola">状态</th>
            <th>预约时间</th>
            <th>创建时间</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->dataList) > 0): ?>
        <?php foreach ($this->dataList as $data): ?>
        <tr>
            <td class="col-center"><input name="chk_ids[]" type="checkbox" /></td>
            <td>
                <a href="<?php echo $this->baseUrl('appointment/index/info?appointment_id=' . $data['AppointmentId']); ?>">
                    <?php echo $data['ServiceTitle']; ?>
                </a>
            </td>
            <td>
                <?php echo $data['Nickname'] . '（' . $data['Username'] . '）'; ?>
            </td>
            <td>
                <?php echo $data['StaffName'] . '（' . $data['CompanyName'] . '）'; ?>
            </td>
            <td class="col-center"><?php echo number_format($data['Price'], 2); ?></td>
            <td class="col-center">
                <?php echo Converter::appointmentStatusFromEnumToString($data['Status']); ?>
            </td>
            <td><?php echo date('Y-m-d H:i', strtotime($data['AppointmentDate'])); ?></td>
            <td><?php echo date('Y-m-d', strtotime($data['CreatedDate'])); ?></td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="8">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->pager; ?>