<div class="projects">
    <div class="row">
        <div class="side_left span65">
            <div class="sideitem">
                <div class="sideuser">
                    <div class="userPic">
                        <a href="#" class="avatar">
                            <img src="<?php echo $this->workDetail['Staff']['AvatarUrl']; ?>" />
                        </a>
                    </div>
                    <div class="pannel">
                        <div class="username">
                            <strong>
                                <a href="#">
                                    <?php echo $this->workDetail['Staff']['Nickname']; ?>
                                </a>
                            </strong>
                        </div>
                        <div class="usersalon">
                            发布时间：<?php echo date('Y-m-d H:i', strtotime($this->workDetail['CreatedDate'])); ?>
                        </div>
                    </div>
                </div>
                <div id="tbody">
                    <div id="mainbody">
                        <img src="<?php echo $this->workDetail['PictureUrl'][0]; ?>" width="100%" id="mainphoto" />
                    </div>
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goleft.gif" width="11" height="56" id="goleft" />
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goright.gif" width="11" height="56" id="goright" />
                    <div id="photos">
                        <div id="showArea">
                            <?php foreach ($this->workDetail['PictureUrl'] as $pic): ?>
                            <img src="<?php echo str_replace('480x480', '110x110', $pic); ?>" rel="<?php echo $pic; ?>" />
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div id="maincontent">
                        <p>这家伙什么都没留下...</p>
                    </div>
                </div>
                <div class="salonaddress">
                    <h2>
                        <span>
                            适合人群
                        </span>
                    </h2>
                    <div class="option-list">
                        <p>
                            <strong>性别：</strong>
                            <span class="u-btns" data-type="checkbox">
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['Gender'] == 1 ? '5' : '4'; ?>">男</span>
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['Gender'] == 2 ? '5' : '4'; ?>">女</span>
                            </span>
                        </p>
                        <p>
                            <strong>脸型：</strong>
                            <span class="u-btns" data-type="checkbox">
                                <?php
                                $hairSelected = explode(',', $this->workDetail['Face']);
                                ?>
                                <span class="u-btn u-btn-c<?php echo in_array(1, $hairSelected) ? '5' : '4'; ?>">圆脸</span>
                                <span class="u-btn u-btn-c<?php echo in_array(2, $hairSelected) ? '5' : '4'; ?>">瓜子脸</span>
                                <span class="u-btn u-btn-c<?php echo in_array(3, $hairSelected) ? '5' : '4'; ?>">方脸</span>
                                <span class="u-btn u-btn-c<?php echo in_array(4, $hairSelected) ? '5' : '4'; ?>">长脸</span>
                            </span>
                        </p>
                        <p>
                            <strong>发型：</strong>
                            <span class="u-btns" data-type="checkbox">
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['HairStyle'] == 1 ? '5' : '4'; ?>">短发</span>
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['HairStyle'] == 2 ? '5' : '4'; ?>">长发</span>
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['HairStyle'] == 3 ? '5' : '4'; ?>">编发</span>
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['HairStyle'] == 4 ? '5' : '4'; ?>">中发</span>
                            </span>
                        </p>
                        <p>
                            <strong>发量：</strong>
                            <span class="u-btns" data-type="checkbox">
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['HairAmount'] == 1 ? '5' : '4'; ?>">多密</span>
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['HairAmount'] == 2 ? '5' : '4'; ?>">中等</span>
                                <span class="u-btn u-btn-c<?php echo $this->workDetail['HairAmount'] == 3 ? '5' : '4'; ?>">偏少</span>
                            </span>
                        </p>
                    </div>
                </div>
                <div class="salonaddress">
                    <h2>
                        <span>
                            沙龙位置
                        </span>
                    </h2>
                    <ul>
                        <li class="addressmap">
                            <input id="latitude" type="hidden" name="latitude" value="<?php echo doubleval($this->workDetail['Staff']['Company']['Latitude']); ?>" />
                            <input id="longitude" type="hidden" name="longitude" value="<?php echo doubleval($this->workDetail['Staff']['Company']['Longitude']); ?>" />
                            <div id="company-map" class="map"></div>
                        </li>
                        <li class="addresscontent">
                            <h3>
                                <?php echo $this->workDetail['Staff']['Company']['Name']; ?>
                            </h3>
                            <p>
                                地址：<?php echo $this->workDetail['Staff']['Company']['Address']; ?>
                            </p>
                            <p>
                                电话：<?php echo empty($this->workDetail['Staff']['Company']['Mobile']) ? $this->workDetail['Staff']['Company']['Tel'] : $this->workDetail['Staff']['Company']['Mobile']; ?>
                            </p>
                        </li>
                    </ul>
                </div>
                <div class="sidefunc">
                    <div class="left">
                        <a id="hair_like" href="#" data-hair-id="<?php echo $this->workDetail['WorkId']; ?>" class="heartcount">
                            <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/heart<?php echo $this->workDetail['IsLiked'] ? '_red' : ''; ?>.png" />
                            <p>
                                <?php echo $this->workDetail['WorkLikeCount']; ?>
                            </p>
                        </a>
                    </div>
                    <div class="share">
                        <div class="bdsharebuttonbox">
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                            <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                            <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>
                            <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
                        </div>
                    </div>
                </div>
                <div class="msgList">
                    <ul>
                        <?php foreach ($this->comments as $comment): ?>
                        <li>
                            <div class="sideuser">
                                <div class="userPic">
                                    <a href="#" class="avatar">
                                        <img src="<?php echo str_replace('480x480', '110x110', $comment['CreatedBy']['AvatarUrl']); ?>" />
                                    </a>
                                </div>
                                <div class="pannel">
                                    <div class="username">
                                        <strong>
                                            <a href="#">
                                                <?php echo $comment['CreatedBy']['Nickname']; ?>
                                            </a>
                                        </strong>
                                        <span class="date">
                                            <?php echo date('m月d日 H:i', strtotime($comment['CreatedDate']));?>
                                        </span>
                                    </div>
                                    <div class="mscontent">
                                        <p>
                                            <?php echo $comment['Body']; ?>
                                        </p>
                                        <div class="msconent-img">
                                          <?php if(count($comment['PictureUrl']) > 0): ?>
                                          <?php foreach ($comment['PictureUrl'] as $pic): ?>
                                          <img src="<?php echo str_replace('480x480', '110x110', $pic); ?>" rel="<?php echo $pic; ?>" />
                                          <?php endforeach; ?>
                                          <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="side_right span33">
            <div class="c1">
                <a href="#" class="avatar">
                    <img src="<?php echo $this->workDetail['Staff']['AvatarUrl']; ?>" class="picimg">
                    <span class="mask_side">
                    </span>
                </a>
            </div>
            <div class="c2">
                <div class="username">
                    <a href="#">
                        设计师：<?php echo $this->workDetail['Staff']['Nickname']; ?>
                    </a>
                </div>
                <div class="opt">
                    <a<?php echo $this->currentUser ? ' id="stylist_appointment" href="#"' : (' href="' . $this->baseUrl('user/auth/signin?continue=' . $this->continueUrl) . '"'); ?> data-stylist-id="<?php echo $this->staffDetail['UserId']; ?>" class="btn btn2_xl btn2_l">
                        <span class="t">
                            预约
                        </span>
                    </a>
                    <a<?php echo $this->currentUser ? ' id="stylist_like" href="#"' : (' href="' . $this->baseUrl('user/auth/signin?continue=' . $this->continueUrl) . '"'); ?> data-stylist-id="<?php echo $this->staffDetail['UserId']; ?>" class="btn btn2_xl btn2_l btn2_1_l">
                        <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/heart<?php echo $this->staffDetail['IsLiked'] ? '_red' : ''; ?>.png" class="ico">
                        <span class="t">
                            收藏
                        </span>
                    </a>
                </div>
                <div class="data">
                    <span class="count">
                        <?php echo count($this->staffDetail['Works']); ?>作品
                    </span>
                    <span class="spacer">
                        |
                    </span>
                    <span class="count">
                        <?php echo count($this->staffDetail['Services']); ?>服务项目
                    </span>
                </div>
            </div>
            <div class="c3">
                <div class="salonna">
                    沙龙名称：
                    <a href="<?php echo $this->baseUrl('salon/index/detail?salon_id=' . $this->workDetail['Staff']['Company']['CompanyId']); ?>">
                        <?php echo $this->workDetail['Staff']['Company']['Name']; ?>
                    </a>
                </div>
                <div class="saloninfo">
                    <h3>
                        发型师简介
                    </h3>
                    <p>
                        这家伙什么都没留下...
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=3998daac6ca53a8067263f139b4aadf4"></script>
<script>

initSlider();
$(document).ready(function() {
    initAppointment();
    initLike();
    initMap();
    initShare();
});

</script>