<div class="content">
  <div class="search">
    <div class="search_tip">
      <p><span>过滤条件</span></p>
    </div>
    <div class="fliter">
      <div class="fliter_bd">
        <div class="col-md-1 fliter_kind_box">
          <div class="a_key">发质:</div>
          <ul>
           <li class="select"><a href="#">全部</a></li>
           <li><a href="#">短发</a></li>
           <li><a href="#">长发</a></li>
           <li><a href="#">编发</a></li>
           <li><a href="#">中发</a></li>
          </ul>
        </div>
        <div class="col-md-1 fliter_kind_box" style="border-bottom:none;">
          <div class="a_key">性别:</div>
          <ul>
           <li class="select"><a href="#">全部</a></li>
           <li><a href="#">男士</a></li>
           <li><a href="#">女士</a></li>
          </ul>
        </div>
      </div>
      <div class="fliter_foot">
       <div class="buttom_tip">
        <a href="#" class="button-strip-item button-strip-item-right button-strip-item-checked">默认排序</a>
        <a href="#" class="button-strip-item"><span class="button-strip-item_name">最新发型</span><span class="button_arrow_top"></span></a>
        <a href="#" class="button-strip-item"><span  class="button-strip-item_name">最受欢迎</span><span class="button_arrow_down"></span></a>
       </div>
      </div>
    </div>
  </div>
  <div class="projects">
  </div>
</div>