platform :ios, '6.0'

inhibit_all_warnings!

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "armv7 armv7s"
    end
  end
end


pod 'AMRatingControl'
pod 'ASIHTTPRequest', '1.8.1'
pod 'EDColor', '0.2.1'
pod 'FMDB', '2.1'
pod 'FontAwesomeKit', '2.1.4'
pod 'JSQSystemSoundPlayer'
pod 'JSONModel', '~> 0.12.0'
pod 'MNCalendarView', '~> 0.0.1'
pod 'MWPhotoBrowser'
pod 'RequestUtils'
pod 'SDWebImage', '~> 3.5.4'
pod 'SocketRocket'
pod 'ZXingObjC', '2.2.2'
pod 'Block-KVO', '~> 2.2.1'
pod "PPiAwesomeButton", :git=> 'https://github.com/pepibumur/PPiAwesomeButton.git', :commit => '1f11e43b34109cb8f64f2e923db061275e756e55'
pod 'SVWebViewController', '~> 1.0'
#pod 'iVersion', '~> 1.10.6'
pod 'iRate', '~> 1.10.2'
pod 'CTAssetsPickerController',  '~> 1.5.0'

#pod 'CocoaLumberjack', '~> 1.8.1'
#pod 'EGODatabase', '~> 2.0'
#pod 'KNSemiModalViewController', '~> 0.3'
#pod 'SVPullToRefresh', '0.4.1'
