platform :ios, '6.0'
inhibit_all_warnings!


pod 'ZXingObjC', '2.2.2'
pod 'ASIHTTPRequest', '1.8.1'
pod 'FMDB', '2.1'
pod 'SDWebImage', '3.5.1'
pod 'EDColor', '0.2.1'
pod 'FontAwesomeKit', '2.1.4'
pod 'MNCalendarView', '~> 0.0.1'
pod 'JSONModel', '~> 0.12.0'
pod 'AMRatingControl'
pod 'MWPhotoBrowser'
#pod 'KNSemiModalViewController', '~> 0.3'

#pod 'SVPullToRefresh', '0.4.1'
#pod 'CocoaLumberjack', '~> 1.8.1'
#pod 'EGODatabase', '~> 2.0'
