platform :ios, '6.0'
inhibit_all_warnings!


pod 'ZXingObjC', '~> 2.2.0'
pod 'ASIHTTPRequest', '~> 1.8.1'
pod 'FMDB', '~>2.1'
pod 'SDWebImage', '~>3.5.1'
pod 'EDColor', '~> 0.2.1'
pod 'FontAwesomeKit', '~> 2.1.4'

#fix the crash issue
#pod 'ZXingObjC', :git => 'https://github.com/larrylu1987/ZXingObjC.git', :commit => '678cff6cc322c834a3c6f4824556acf1c005b676'