<div class="projects">
    <div class="row">
        <div class="side_left span65">
            <div class="sideitem">
                <div id="tbody">
                    <div id="mainbody">
                        <img src="<?php echo $this->companyDetail['PictureUrl'][0]; ?>" width="100%" id="mainphoto" />
                    </div>
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goleft.gif" width="11" height="56" id="goleft" />
                    <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/goright.gif" width="11" height="56" id="goright" />
                    <div id="photos">
                        <div id="showArea">
                            <?php foreach ($this->companyDetail['PictureUrl'] as $pic): ?>
                            <img src="<?php echo str_replace('480x480', '110x110', $pic); ?>" rel="<?php echo $pic; ?>" />
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <div id="maincontent">
                    </div>
                </div>
                <div class="salonaddress">
                    <h2>
                        <span>
                            沙龙位置
                        </span>
                    </h2>
                    <ul>
                        <li class="addressmap">
                            <input id="latitude" type="hidden" name="latitude" value="<?php echo doubleval($this->companyDetail['Latitude']); ?>" />
                            <input id="longitude" type="hidden" name="longitude" value="<?php echo doubleval($this->companyDetail['Longitude']); ?>" />
                            <div id="company-map" class="map"></div>
                        </li>
                        <li class="addresscontent">
                            <h3>
                                <?php echo $this->companyDetail['CompanyName']; ?>
                            </h3>
                            <p>
                                地址：<?php echo $this->companyDetail['CompanyAddress']; ?>
                            </p>
                            <p>
                                电话：<?php echo empty($this->companyDetail['Mobile']) ? $this->companyDetail['Tel'] : $this->companyDetail['Mobile']; ?>
                            </p>
                        </li>
                    </ul>
                </div>
                <div class="sidefunc">
                    <div class="left">
                        <a class="add-comment salon-comment" style="display: none;float:left;" data-salon-id="<?php echo $this->companyDetail['CompanyId']; ?>">
                            <i class="iconfont">&#xf0199;</i>
                            我要评论
                        </a>
                    </div>
                    <div class="share">
                        <div class="bdsharebuttonbox">
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                            <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                            <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>
                            <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="tabList">
                    <ul>
                        <li rel="stylist-list" class="active">
                            <a>发型师</a>
                        </li>
                        <li rel="goods-list">
                            <a>商品</a>
                        </li>
                        <li rel="comment-list">
                            <a>评论</a>
                        </li>
                    </ul>
                </div>
                <div id="stylist-list" class="msgList">
                    <div class="card-container">
                    <?php foreach ($this->staffList as $staff): ?>
                    <div class="card-list">
                        <div class="card-list-inner">
                            <div class="card-img">
                                <a href="<?php echo $this->baseUrl('stylist/index/detail?stylist_id=' . $staff['UserId']); ?>">
                                    <img src="<?php echo $staff['AvatarUrl']; ?>" onerror="this.src='<?php echo $this->config->asset->baseUrl; ?>/img/photo-default.png';" />
                                </a>
                            </div>
                            <div class="card-info">
                                <div class="username">
                                    <strong>
                                        <a href="<?php echo $this->baseUrl('stylist/index/detail?stylist_id=' . $staff['UserId']); ?>"><?php echo $staff['Nickname']; ?></a>
                                    </strong>
                                </div>
                                <p class="card-info-first">沙龙：<?php echo $staff['Company']['Name']; ?></p>
                                <div class="card-action-bar">
                                    <ul>
                                        <li><img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/iconfont-chanpin.png"><span><?php echo $staff['WorkCount']; ?></span></li>
                                        <li><img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/iconfont-zan.png"><span><?php echo $staff['RateCount']; ?></span></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    </div>
                </div>
                <div id="goods-list" class="msgList" style="display: none;">
                    <div class="card-container">
                    <?php foreach ($this->goodsList as $goods): ?>
                    <div class="card-list">
                        <div class="card-list-inner">
                            <div class="card-img">
                                <a href="<?php echo $this->baseUrl('goods/index/detail?goods_id=' . $goods['GoodsId']); ?>">
                                    <img src="<?php echo $goods['PictureUrl'][0]; ?>" onerror="this.src='<?php echo $this->config->asset->baseUrl; ?>/img/photo-default.png';" />
                                </a>
                            </div>
                            <div class="card-info">
                                <div class="username">
                                    <strong>
                                        <a href="<?php echo $this->baseUrl('goods/index/detail?goods_id=' . $goods['GoodsId']); ?>"><?php echo $goods['Name']; ?></a>
                                    </strong>
                                </div>
                                <p class="card-info-first">价格：<span style="color: #ff2900; font-weight: bold;">￥<?php echo $goods['SellPrice']; ?></span></p>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    </div>
                </div>
                <div id="comment-list" data-hair-id="0" data-goods-id="0" data-salon-id="<?php echo $this->companyDetail['CompanyId']; ?>" data-stylist-id="0" class="msgList" style="display: none;">

                </div>
            </div>
        </div>
        <div class="side_right span33">
            <div class="c1">
                <a href="#" class="avatar">
                    <img src="<?php echo $this->companyDetail['CompanyLogoUrl']; ?>" class="picimg">
                    <span class="mask_side">
                    </span>
                </a>
            </div>
            <div class="c2">
                <div class=" username">
                    <a href="#">
                        <?php echo $this->companyDetail['CompanyName']; ?>
                    </a>
                </div>
                <div class="opt">
                    <a<?php echo $this->currentUser ? ' id="salon_like" href="#"' : (' href="' . $this->baseUrl('user/auth/signin?continue=' . $this->continueUrl) . '"'); ?> data-salon-id="<?php echo $this->companyDetail['CompanyId']; ?>" class=" btn btn2_xl btn2_l btn2_1_l">
                        <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/heart<?php echo $this->companyDetail['IsLiked'] ? '_red' : ''; ?>.png" class="ico">
                        <span class="t">
                            收藏
                        </span>
                    </a>
                </div>
                <div class="data">
                    <span class="count">
                        <?php echo count($this->staffList); ?>发型师
                    </span>
                    <span class="spacer">
                        |
                    </span>
                    <span class="count">
                        <?php echo count($this->goodsList); ?>商品
                    </span>
                </div>
            </div>
            <div class="c3">
                <div class="salonna">
                    区域：
                    <a href="#">
                        <?php echo $this->companyDetail['Region']; ?>
                    </a>
                </div>
                <div class="salonna">
                    地址：
                    <a href="#">
                        <?php echo $this->companyDetail['Address']; ?>
                    </a>
                </div>
                <div class="salonna">
                    电话：
                    <a href="#">
                        <?php echo empty($this->companyDetail['Mobile']) ? $this->companyDetail['Tel'] : $this->companyDetail['Mobile']; ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&amp;ak=3998daac6ca53a8067263f139b4aadf4"></script>
<script>

window._bd_share_config.common.bdText = "<?php echo $this->companyDetail['CompanyName']; ?>";

initSlider();
$(document).ready(function() {
    initLike();
    initTab();
    initComment(0, <?php echo $this->companyDetail['CompanyId']; ?>, 0, 0);
    initMap();
    initShare();
});

</script>