<div class="projects">
  <div class="row">
    <div class="side_left">
      <div class="sideitem">
        <div class="sideuser">
          <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
          <div class="pannel">
            <div class="username"><strong><a href="#">李彤彤</a></strong></div>
            <div class="usersalon">发布时间：2014-07-08 12:23</div>
          </div>
        </div>
        <div id="tbody">
          <div id="mainbody"> <img src="images/inacup_donut.jpg" width="100%" id="mainphoto"  /> </div>
          <img src="images/goleft.gif" width="11" height="56" id="goleft" /> <img src="images/goright.gif" width="11" height="56" id="goright" />
          <div id="photos">
            <div id="showArea">
              <!--
          SRC: 缩略图地址
          REL: 大图地址
          NAME: 网址
        -->
              <img src="images/inacup_donut.jpg" rel="images/inacup_donut.jpg"/ > <img src="images/inacup_pumpkin.jpg" rel="images/inacup_pumpkin.jpg"/> <img src="images/inacup_samoa.jpg" rel="images/inacup_samoa.jpg"/> <img src="images/inacup_vanilla.jpg" rel="images/inacup_vanilla.jpg"/> </div>
          </div>
            <div id="maincontent"><p>性一起讨论艺术，美容，生活的地方就叫做沙龙。后来到了近现代出现的美容美发化妆等综合店面，就开始流行叫做沙龙（SALON）了，如果是专业做关于头发的美发中心，档次高一点...</p></div>
        </div>

        <div class="salonaddress">
         <h2><span>沙龙位置</span></h2>
         <ul>
          <li class="addressmap"><img src="images/map.jpg" /></li>
          <li class="addresscontent"><h3>非凡造型沙龙</h3>
          <p>地址：历下区解放历下区解放历下区解放路16-3号(近公交总公司)</p>
          <p>电话：0531-5557896</p>
          </li>
         </ul>
        </div>
        <div class="sidefunc">
          <div class="left"> <span><a href="#">131转发</a></span> <span style="border:none;"><a href="#">17评论</a></span> <a href="#" class="heartcount"><img src="images/heart.png" />
            <p>452</p>
            </a> </div>
          <div class="share"> <a href="#"><i class="ico25 ico25a"></i></a> <a href="#"><i class="ico25 ico25b"></i></a> <a href="#"><i class="ico25 ico25c"></i></a> </div>
        </div>

        <div class="msgList">
          <ul>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
            <li>
              <div class="sideuser">
                <div class="userPic"><a href="#" class="avatar"><img src="images/1352.jpg" /></a></div>
                <div class="pannel">
                  <div class="username"><strong><a href="#">李彤彤</a></strong><span class="date">5月29日 12:36</span></div>
                  <div class="mscontent"><p>这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，这个发型很不错，店里的环境也不错，</p></div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="side_right">
      <div class="c1"><a href="#" class="avatar"><img src="images/135.jpg" class="picimg"><span class="mask_side"></span></a></div>
      <div class="c2">
        <div class=" username"><a href="#">设计师：杨俊秀</a> </div>
        <div class=" opt"><a href="#" class=" btn btn2_xl btn2_l"><span class="t">预约</span></a><a href="#" class=" btn btn2_xl btn2_l btn2_1_l"><img src="images/heart.png" class="ico"><span class="t">收藏</span></a></div>
        <div class="data"> <span class="count">11作品</span><span class="spacer">|</span><span class="count">34收藏</span> <span class="spacer">|</span><span class="count">56服务项目</span> </div>
      </div>
      <div class="c3">
        <div class="salonna">沙龙名称：<a href="#">沙宣造型</a></div>
        <div class="saloninfo">
          <h3>沙龙简介</h3>
          <p>身为国家级造型师，德国哈苏公司高级
            客座讲师。世界知名品牌姿生堂SHISEIDO的首
            席彩妆顾问, 自1991年正式进入中国时尚圈以
            来，以其对国际流行元素的敏锐感觉和把握，
            多年来始终走在潮流前列，执掌造型界牛耳，
            左右时尚走向。</p>
        </div>
      </div>
    </div>
  </div>
</div>