<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-payment-info" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">支付方式名称：</label>
                <div class="ipt">
                    <input id="paymentname" type="text"  datatype="*" value="<?php echo $this->paymentInfo['Name']; ?>"  errormsg="名称不能为空！" class="u-ipt"/> *
                     <p></p>
                </div>
            </div>
           <div class="formitm">
                <label class="lab">商户ID：</label>
                <div class="ipt">
                    <input id="partnerid" type="text"  value="<?php echo $this->paymentInfo['PartnerId']; ?>"   class="u-ipt"/> 
                    <p>支付平台中商户ID</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">商户密钥：</label>
                <div class="ipt">
                    <input id="partnerkey" type="text"  value="<?php echo $this->paymentInfo['PartnerKey']; ?>"   class="u-ipt"/>  
                    <p>支付平台中商户密钥</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">描述：</label>
                <div class="ipt">
                    <?php echo $this->paymentInfo['Description']; ?>
                </div>
            </div>
             <div class="formitm">
                <label class="lab">手续费设置：</label>
                <div class="ipt">
                    <label class="attr"><input type="radio" checked="checked" onclick="$('#paymentFeeText').text('商品总额的百分比：');" value="1" name="poundage_type">按商品总额的百分比</label>
                        <label class="attr"><input type="radio" onclick="$('#paymentFeeText').text('固定收取的手续费：');" value="2" name="poundage_type">按固定金额</label>
                        <label><span id="paymentFeeText">商品总额的百分比：</span><input type="text" alt="费用不能为空！" pattern="required" value="" name="poundage" class="small"></label>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">排序：</label>
                <div class="ipt">
                    <input id="sort" type="text" value="<?php echo $this->paymentInfo['Order']; ?>"   class="u-ipt"/> 
                </div>
            </div>

            <div class="formitm">
                <label class="lab">支付说明：</label>
                <div class="ipt">
                    <textarea  id='note' type="text"  class="u-ipt"><?php echo $this->paymentInfo['Note']; ?></textarea>
                    <p></p>
                </div>
            </div>  

             <div class="formitm">
                <label class="lab">开启：</label>
                <div class="ipt">
                    <label class="attr"><input type="radio" checked="checked" value="0" name="status">开启</label>
                    <label class="attr"><input type="radio" value="1" name="status">关闭</label>
                    <p>只有开启后，用户才能从前台进行支付选择</p>
                </div>
            </div>     
            
            
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="payment_id" value="<?php echo intval($this->paymentInfo['PaymentId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/payment-info.js'); ?>"></script>