<?php
use \Welfony\Utility\Util;
?>
<table class="m-table">
    <thead>
        <tr>
            <th>图标</th>
            <th>名称</th>
            <th>描述</th>
            <th>开启状态</th>
            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach( $this->rows as $payment) : ?>
        <tr>
            <td><img src="<?php echo Util::baseAssetUrl($payment['Logo']); ?>"></td>
            <td>
                <?php echo $payment['Name']; ?>
            </td>
            <td>
                <?php echo $payment['Description']; ?>
            </td>
            <td>
                <?php echo $payment['Status'] ?'使用中':'已关闭'; ?>
            </td>
            <td>
                <a href="<?php echo $this->baseUrl('system/payment/info?payment_id=' .  $payment['PaymentId']); ?>" >
                    <i class="iconfont">&#xf0022;</i>&nbsp;&nbsp;
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>