<?php
use Welfony\Utility\Converter;
use Welfony\Utility\Util;
?>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input id="chk_all" type="checkbox" /></th>
            <th>数量</th>
            <th>时间</th>
            <th>描述</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->dataList) > 0): ?>
        <?php foreach ($this->dataList as $data): ?>
        <tr>
            <td class="col-center"><input name="chk_ids[]" value="<?php echo $data['PaymentTransactionId']; ?>" type="checkbox" /></td>
            <td><?php echo $data['Amount']; ?></td>
            <td><?php echo $data['CreatedDate']; ?></td>
            <td><?php echo $data['Description']; ?></td>
            
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="4">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->pager; ?>