<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-user-info" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">角色：</label>
                <div class="ipt">
                    <select name="user_role" class="u-sel">
                        <?php if ($this->userInfo['Role'] == 1) : ?>
                        <option value="1"<?php echo $this->userInfo['Role'] == 1 ? ' selected' : ''; ?>>超级管理员</option>
                        <?php endif; ?>
                        <?php if ($this->userInfo['Role'] == 2 || $this->userInfo['Role'] == 3) : ?>
                        <option value="2"<?php echo $this->userInfo['Role'] == 2 ? ' selected' : ''; ?>>沙龙管理员</option>
                        <option value="3"<?php echo $this->userInfo['Role'] == 3 ? ' selected' : ''; ?>>发型师</option>
                        <?php endif; ?>
                        <?php if ($this->userInfo['Role'] == 4) : ?>
                        <option value="4"<?php echo $this->userInfo['Role'] == 4 ? ' selected' : ''; ?>>普通用户</option>
                        <?php endif; ?>
                    </select>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">账号：</label>
                <div class="ipt">
                    <input name="username" type="text" value="<?php echo $this->userInfo['Username']; ?>" datatype="s4-12" errormsg="账号至少4个字符，最多12个字符！" class="u-ipt"/>
                    <p>4~12个字符，包括字母，数字，下划线以字母开头，字母或数字结尾</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">昵称：</label>
                <div class="ipt">
                    <input name="nickname" type="text" value="<?php echo $this->userInfo['Nickname']; ?>" datatype="s2-12" errormsg="昵称至少2个字符，最多12个字符！" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">初始密码：</label>
                <div class="ipt">
                    <input name="password" type="password" datatype="*6-15" ignore="ignore" errormsg="密码范围在6~15位之间,不能使用空格！" class="u-ipt"/>
                    <p>6~15个字符，区分大小写</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">确认密码：</label>
                <div class="ipt">
                    <input name="password_repeate" type="password" datatype="*" ignore="ignore" recheck="password" errormsg="您两次输入的账号密码不一致！" class="u-ipt"/>
                    <p>再次输入密码</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">邮箱：</label>
                <div class="ipt">
                    <input name="email" type="text" datatype="e" ignore="ignore" value="<?php echo $this->userInfo['Email']; ?>" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">手机：</label>
                <div class="ipt">
                    <input name="mobile" type="text" datatype="m" ignore="ignore" value="<?php echo $this->userInfo['Mobile']; ?>" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">头像：</label>
                <div class="ipt">
                    <span class="u-img2">
                        <a href="javascript:;">
                            <img id="avatar-image" src="<?php echo $this->userInfo['AvatarUrl']; ?>" data-ori="<?php echo $this->userInfo['AvatarOriginalUrl']; ?>" data-110="<?php echo $this->userInfo['AvatarThumb110Url']; ?>" alt="">
                            <input id="avatar-url" type="hidden" name="avatar_url" value="<?php echo $this->userInfo['AvatarUrl']; ?>" />
                        </a>
                    </span>
                    <a class="update-thumb" href="#">调整缩略图</a>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"></label>
                <div class="ipt">
                    <div id="avatar-uploader"></div>
                </div>
            </div>
            <div class="formitm formitm-1">
                <input type="hidden" name="user_id" value="<?php echo intval($this->userInfo['UserId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/user-info.js'); ?>"></script>