<div class="m-form">
    <form method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">角色：</label>
                <div class="ipt">
                    <select name="userrole" class="u-sel">
                        <option value="1">超级管理员</option>
                        <option value="2">沙龙管理员</option>
                        <option value="3">发型师</option>
                        <option value="4">普通用户</option>
                    </select>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">账号：</label>
                <div class="ipt">
                    <input name="username" type="text" class="u-ipt"/>
                    <p>6~8个字符，包括字母，数字，下划线以字母开头，字母或数字结尾</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">昵称：</label>
                <div class="ipt">
                    <input name="nickname" type="text" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">初始密码：</label>
                <div class="ipt">
                    <input name="password" type="password" class="u-ipt"/>
                    <p>6~8个字符，区分大小写</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">确认密码：</label>
                <div class="ipt">
                    <input name="passwordrepeate" type="password" class="u-ipt"/>
                    <p>再次输入密码</p>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">邮箱：</label>
                <div class="ipt">
                    <input name="email" type="text" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">手机：</label>
                <div class="ipt">
                    <input name="mobile" type="text" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">头像：</label>
                <div class="ipt">
                    <span class="u-img2"><a href="#"><img src="http://nec.netease.com/img/s/1.jpg" alt=""></a></span>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"></label>
                <div class="ipt">
                    <span class="u-upload">
                        <button type="button">上传头像</button>
                        <input type="file"/>
                    </span>
                </div>
            </div>
            <div class="formitm formitm-1">
                <input type="hidden" value="<?php echo intval($this->users['UserId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<script>
    $(document).ready(function() {
        $( "input[name=username]" ).datepicker();
        $( "<p></p>" ).dialog({
            resizable: false,
            title: '登录',
            width: 600,
            height:400,
            modal: true,
            buttons: {
                "登录": function() {
                    $( this ).dialog( "close" );
                },
                "取消": function() {
                    $( this ).dialog( "close" );
                }
            }
        });
    });
</script>