<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('user/index/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
        <li>
            <a href="#">
                <i class="iconfont">&#xf013f;</i>
                删除
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">订单号</th>
            <th>详情</th>
            <th class="cola">收货人</th>
            <th class="cola">状态</th>
            <th class="colb">下单日期</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <a href="#" class="first pageprv z-dis">上一页</a>
    <a href="#">1</a>
    <a href="#" class="z-crt">2</a>
    <a href="#">3</a>
    <a href="#">4</a>
    <i>...</i>
    <a href="#">10</a>
    <a href="#" class="last pagenxt">下一页</a>
</div>