<form method="post">
<div class="my_container">
    <div class="contentset">
        <ul id="tags" style="border-bottom:none;" class="cleft">
            <li>
                <a href="<?php echo $this->baseUrl('user/setting'); ?>" class="tab_1">
                    基本信息
                </a>
            </li>
            <li class="selectTag">
                <a href="<?php echo $this->baseUrl('user/setting/account'); ?>" class="tab_1">
                    我的帐号
                </a>
            </li>
            <li>
                <a href="<?php echo $this->baseUrl('user/setting/changepassword'); ?>" class="tab_1">
                    修改密码
                </a>
            </li>
            <li>
                <a href="<?php echo $this->baseUrl('user/setting/address'); ?>" class="tab_1">
                    收货地址
                </a>
            </li>
        </ul>
        <div id="tagContent" class="cright">
            <div class="tagContent selectTag">
                <div class="toolbar">
                    <ul class="clearfix">
                        <li>
                            <a href="<?php echo $this->baseUrl('user/setting/accounthistory'); ?>">
                                <i class="iconfont">&#x344a;</i>
                                充值记录
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="rginfoitem">
                    <div class="tit">
                        帐号：
                    </div>
                    <div class="rginfo">
                        <input type="text" value="<?php echo $this->currentUser['Nickname']; ?>" readonly="readonly" class="winput" />
                    </div>
                </div>
                <div class="rginfoitem">
                    <div class="tit">
                        余额：
                    </div>
                    <div class="rginfo">
                        <input type="text" value="￥<?php echo number_format($this->totalBalance, 2); ?>" readonly="readonly" class="winput" />
                    </div>
                </div>


                <div style="border-bottom: 1px dashed #ddd; margin: 0 0 15px 0;"></div>


                <div class="rginfoitem">
                    <div class="tit">
                        支付方式：
                    </div>
                    <div class="rginfo">
                         <select name="payment" class="u-sel">
                            <option value="1">支付宝</option>
                        </select>
                    </div>
                </div>
                <div class="rginfoitem">
                    <div class="tit">
                        充值金额：
                    </div>
                    <div class="rginfo">
                        <input name="amount" type="text" value="100" class="winput" />
                    </div>
                </div>

                <div class="rginfoitem">
                    <div class="rgbt">
                        <button type="submit" class="btn btn2_xl btn2_l">
                            充值
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>