<div class="my_container">
    <div class="contentset">
        <ul id="tags" style="border-bottom:none;" class="cleft">
            <li>
                <a href="<?php echo $this->baseUrl('user/setting'); ?>" class="tab_1">
                    基本信息
                </a>
            </li>
            <li>
                <a href="<?php echo $this->baseUrl('user/setting/changepassword'); ?>" class="tab_1">
                    修改密码
                </a>
            </li>
            <li class="selectTag">
                <a href="" class="tab_1">
                    收货地址
                </a>
            </li>
        </ul>
        <div id="tagContent" class="cright">
            <div class="tagContent selectTag">
                <div class="toolbar">
                    <ul class="clearfix">
                        <li>
                            <a href="<?php echo $this->baseUrl('user/setting/addressedit'); ?>">
                                <i class="iconfont">&#xf0175;</i>
                                添加新地址
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <?php foreach ($this->addressList as $address): ?>
                    <div class="col-md-3 dalist span18">
                        <div class="daBox on">
                            <ul>
                                <li>
                                    <strong>
                                        <?php echo $address['ShippingName']; ?>
                                    </strong>
                                    <span class="tel">
                                        <?php echo $address['Mobile']; ?>
                                    </span>
                                </li>
                                <li>
                                    <p>
                                        <?php echo $address['Area']; ?>
                                    </p>
                                    <p>
                                        <?php echo $address['Address']; ?>
                                    </p>
                                </li>
                                <li>
                                    <?php if ($address['IsDefault']): ?>
                                    <button type="button" class="min_bt br">
                                        默认地址
                                    </button>
                                    <?php endif; ?>
                                    <a href="#" class="close" data-id="<?php echo $address['AddressId']; ?>" title="删除"></a>
                                    <a href="<?php echo $this->baseUrl('user/setting/addressedit?address_id=' . $address['AddressId']); ?>" class="edit" title="编辑"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('.close').click(function() {
        var lnk = $(this);
        var opts = {
            type: "GET",
            url: '/ajax/address/remove',
            contentType: "application/json",
            data: "address_id=" + lnk.attr('data-id'),
            success: function(data) {
                lnk.parent().parent().parent().parent().fadeOut();
            }
        };
        $.ajax(opts);
        return false;
    });
});
</script>