<form method="post">
<div class="my_container">
    <div class="contentset">
        <ul id="tags" style="border-bottom:none;" class="cleft">
            <li>
                <a href="<?php echo $this->baseUrl('user/setting'); ?>" class="tab_1">
                    基本信息
                </a>
            </li>
            <li class="selectTag">
                <a href="" class="tab_1">
                    修改密码
                </a>
            </li>
            <li>
                <a href="<?php echo $this->baseUrl('user/setting/address'); ?>" class="tab_1">
                    收货地址
                </a>
            </li>
        </ul>
        <div id="tagContent" class="cright">
            <div class="tagContent selectTag">

                <div class="rginfoitem">
                    <div class="tit">
                        <i>
                            *
                        </i>
                        原始密码：
                    </div>
                    <div class="rginfo">
                        <input name="original_password" type="password" class="winput" />
                    </div>
                </div>

                <div class="rginfoitem">
                    <div class="tit">
                        <i>
                            *
                        </i>
                        新密码：
                    </div>
                    <div class="rginfo">
                        <input name="new_password" type="password" class="winput" />
                    </div>
                </div>

                <div class="rginfoitem">
                    <div class="tit">
                        <i>
                            *
                        </i>
                        确认密码：
                    </div>
                    <div class="rginfo">
                        <input name="repeate_new_password" type="password" class="winput" />
                    </div>
                </div>

                <div class="rginfoitem">
                    <div class="rgbt">
                        <button type="submit" class="btn btn2_xl btn2_l">
                            保存
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>