<div class="foot">
    <ul>
        <li>
            <p>
                <a href="#" onclick="setHome(this,window.location);">设为首页</a> | <a href="#" onclick="addFavorite(window.location,document.title)">收藏本站</a> | <a href="#">关于我们</a> | <a href="#">版权声明</a> | <a href="#">联系我们</a> | <a href="#">网站帮助</a> | <a href="#">意见建议 </a>
            </p>
        </li>
        <li>
            <p>建议使用9.0以上版本的IE来访问本站</p>
        </li>
    </ul>
</div>

<script>
    $('document').ready(function() {
        $('.flexslider').flexslider();
    });
</script>