<script>
    var globalSetting = {
        baseUrl: '<?php echo $this->baseUrl(''); ?>',
        apiBaseUrl: '<?php echo $this->config->api->baseUrl; ?>',
        staticAssetBaseUrl: '<?php echo $this->config->asset->baseUrl; ?>'
    };
</script>
<div id="sitemast">
    <div id="sitemast_m">
        <div class="g_logo">
            <a href="<?php echo $this->baseUrl(''); ?>">
                <img src="<?php echo $this->config->asset->baseUrl; ?>/img/frontend/logo.png" />
            </a>
            <div class="g_homearea">
                <a href="<?php echo $this->baseUrl('city'); ?>">
                    <?php echo $this->userContext->area['City']['Name']; ?>
                </a>
            </div>
        </div>
        <div class="g_nav">
            <ul>
                <li<?php echo $this->module == 'hair' ? ' class="select"' : ''; ?>><a href="<?php echo $this->baseUrl('hair'); ?>">发型</a></li>
                <li<?php echo $this->module == 'salon' ? ' class="select"' : ''; ?>><a href="<?php echo $this->baseUrl('salon'); ?>">沙龙</a></li>
                <li<?php echo $this->module == 'stylist' ? ' class="select"' : ''; ?>><a href="<?php echo $this->baseUrl('stylist'); ?>">设计师</a></li>
                <li<?php echo $this->module == 'goods' ? ' class="select"' : ''; ?>><a href="<?php echo $this->baseUrl('goods'); ?>">商城</a></li>
            </ul>
        </div>
        <div class="f_search">
            <div class="f_search_left"></div>
            <input class="f_search_m" />
            <button class="f_search_bt"></button>
        </div>
        <div class="loginbt">
            <a class="account-icon" href="<?php echo $this->currentUser ? 'javascript:;' : $this->baseUrl('user/auth/signin'); ?>">
                <img src="<?php echo $this->currentUser ? str_replace('480x480', '110x110', $this->currentUser['AvatarUrl']) : $this->config->asset->baseUrl . '/img/frontend/man.png'; ?>" />
            </a>
            <?php if ($this->currentUser): ?>
            <div class="header-tc-content" style="width: 160px;">
                <span class="header-tc-ct-bg"></span>
                <span class="header-tuc-uname"><?php echo $this->currentUser['Nickname']; ?></span>
                <a class="header-tuc-item" href="<?php echo $this->baseUrl('user'); ?>">个人中心</a>
                <a class="header-tuc-item" href="<?php echo $this->baseUrl('user/setting'); ?>">帐号设置</a>
                <a class="header-tuc-logout" href="<?php echo $this->baseUrl('user/auth/signout'); ?>">退出帐号</a>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
