<div class="content">
 <div class="changecity">
  <div class="choice_province">
   <form>
    <span>选择城市省份：</span>
    <select>
     <option>山东</option>
     <option>北京</option>
     <option>河北</option>
    </select>
    <select>
     <option>济南</option>
     <option>青岛</option>
     <option>烟台</option>
    </select>
    <button class="btn min_bt">确定</button>
   </form>
  </div>
  <div class=" city_list">
  <h3>常用城市:</h3>
  <p><a href="#">上海</a><a href="#">北京</a><a href="#">广州</a><a href="#">深圳</a><a href="#">武汉</a><a href="#">天津</a><a href="#">西安</a><a href="#">南京</a><a href="#">杭州</a><a href="#">成都</a><a href="#">重庆</a><a href="#">苏州</a><a href="#">嘉兴</a><a href="#">无锡</a><a href="#">常州</a><a href="#">宁波</a><a href="#">长沙</a><a href="#">上海</a><a href="#">上海</a><a href="#">上海</a><a href="#">上海</a></p>
  </div>
  <div class="citieslist">
   <h3>按拼音首字母选择</h3>
   <ol>
    <li id="city-A">
     <p>
      <span class="label"><strong>A</strong></span>
      <span><a href="#" class="isonline">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a></span>
     </p>
    </li>
      <li id="city-B">
     <p>
      <span class="label"><strong>B</strong></span>
      <span><a href="#" class="isonline">北京</a><a href="#">包头</a><a href="#">滨海</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a></span>
     </p>
    </li>
      <li id="city-C" class="hover">
     <p>
      <span class="label"><strong>C</strong></span>
      <span><a href="#" class="isonline">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a></span>
     </p>
    </li>
    <li id="city-D">
     <p>
      <span class="label"><strong>B</strong></span>
      <span><a href="#" class="isonline">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a></span>
     </p>
    </li>
    <li id="city-E">
     <p>
      <span class="label"><strong>B</strong></span>
      <span><a href="#" class="isonline">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a></span>
     </p>
    </li>
    <li id="city-F">
     <p>
      <span class="label"><strong>B</strong></span>
      <span><a href="#" class="isonline">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a></span>
     </p>
    </li>
    <li id="city-H">
     <p>
      <span class="label"><strong>B</strong></span>
      <span><a href="#" class="isonline">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a><a href="#">鞍山</a></span>
     </p>
    </li>
   </ol>

  </div>
 </div>

</div>