<div class="operating">
        <a href="javascript:;"><button onclick="window.location='<?php echo $this->baseUrl('goods/brand/categoryinfo'); ?>'" type="button" class="operating_btn"><span class="addition">添加分类</span></button></a>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">格边框</th>
            <th>表头</th>
            <th class="cola">表头</th>
            <th class="cola">表头</th>
            <th class="colb">表头</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <a href="#" class="first pageprv z-dis">上一页</a>
    <a href="#">1</a>
    <a href="#" class="z-crt">2</a>
    <a href="#">3</a>
    <a href="#">4</a>
    <i>...</i>
    <a href="#">10</a>
    <a href="#" class="last pagenxt">下一页</a>
</div>