<?php
use \Welfony\Utility\Util;

$this->headLink()
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.uploadify/3.2.1/jquery.uploadify.css'))
     ->appendStylesheet(Util::baseAssetUrl('css/vendor/jquery.imgareaselect/0.9.10/imgareaselect-default.css'));

$this->headScript()
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.validform/5.3.2/jquery.validform.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.uploadify/3.2.1/jquery.uploadify.min.js'))
     ->appendFile(Util::baseAssetUrl('js/vendor/jquery.imgareaselect/0.9.10/jquery.imgareaselect.min.js'));
?>
<div class="m-form">
    <form id="frmBrandCategoryInfo" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">分类名称：</label>
                <div class="ipt">
                    <input name="name" type="text" value="<?php echo $this->brandCategoryInfo['Name']; ?>" class="u-ipt"/>
                </div>
            </div>
             <div class="formitm formitm-1">
                <input type="hidden" name="user_id" value="<?php echo intval($this->brandCategoryInfo['BrandCategoryId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
