<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-brand-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">品牌名称：</label>
                <div class="ipt">
                    <input name="brandname" type="text"  datatype="*" value="<?php echo $this->brandInfo['Name']; ?>"  errormsg="品牌名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">排序：</label>
                <div class="ipt">
                    <input name="sort" type="text" value="<?php echo $this->brandInfo['Sort']; ?>" datatype="n" errormsg="请输入数字！" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">网址：</label>
                <div class="ipt">
                    <input id='url' name="url" type="text" value="<?php echo $this->brandInfo['Url']; ?>" datatype="url" errormsg="请输入正确的URL." class="u-ipt"/>
                    <p>完整的URL链接地址，如：http://www.welhair.com</p>
                </div>
            </div>
          
            <div class="formitm">
                <label class="lab">LOGO：</label>
                <div class="ipt">
                    <span class="u-img2">
                        <a href="javascript:;">
                            <img id="brand-image" src="<?php echo $this->baseUrl( $this->brandInfo['Logo']); ?>"  alt="">
                            <input id="brand-url" type="hidden" name="logo_url" value="<?php echo $this->baseUrl( $this->brandInfo['Logo']); ?>" />
                        </a>
                    </span>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"></label>
                <div class="ipt">
                    <div id="brand-uploader"></div>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">所属分类：</label>
                <div class="ipt">
                    <ul class="select">
                        <?php foreach( $this->brandcategories as $brancategory) : ?>
                        <li><label><input type="checkbox" name="category[]" value="<?php echo $brancategory['BrandCategoryId']; ?>"><?php echo $brancategory['Name']; ?></label></li>
                        <?php endforeach; ?>

                    </ul>
                </div>
            </div>
             <div class="formitm">
                <label class="lab">描述：</label>
                <div class="ipt">
                    <textarea id = "description" name="description"    value="<?php echo $this->brandInfo['Description']; ?>" class="u-ipt"></textarea> 
                </div>
            </div>
            <div class="formitm formitm-1">
                <input type="hidden" name="brand_id" value="<?php echo intval($this->brandInfo['BrandId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/brand-info.js'); ?>"></script>