<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-brand-info" method="post">
        <fieldset>
           <div class="formitm">
                <label class="lab">品牌名称：</label>
                <div class="ipt">
                    <input name="brandname" type="text"  datatype="*" value="<?php echo $this->brandInfo['Name']; ?>"  errormsg="品牌名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">排序：</label>
                <div class="ipt">
                    <input name="sort" type="text" value="<?php echo $this->brandInfo['Sort']; ?>" datatype="n" errormsg="请输入数字！" class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">网址：</label>
                <div class="ipt">
                    <input name="url" type="text" value="<?php echo $this->brandInfo['Url']; ?>" datatype="url" errormsg="账号至少4个字符，最多12个字符！" class="u-ipt"/>
                    <p>完整的URL链接地址，如：http://www.welhair.com</p>
                </div>
            </div>
          
            <div class="formitm">
                <label class="lab">LOGO：</label>
                <div class="ipt">
                    <span class="u-img2">
                        <a href="javascript:;">
                            <img id="avatar-image" src="<?php echo $this->userInfo['AvatarUrl']; ?>" data-ori="<?php echo $this->userInfo['AvatarOriginalUrl']; ?>" data-110="<?php echo $this->userInfo['AvatarThumb110Url']; ?>" alt="">
                            <input id="avatar-url" type="hidden" name="avatar_url" value="<?php echo $this->userInfo['AvatarUrl']; ?>" />
                        </a>
                    </span>
                </div>
            </div>
            <div class="formitm">
                <label class="lab"></label>
                <div class="ipt">
                    <div id="avatar-uploader"></div>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">所属分类：</label>
                <div class="ipt">
                    <ul class="select">
                        <li><label><input type="checkbox" name="category[]" value="3">高档</label></li>
                        <li><label><input type="checkbox" name="category[]" value="5">世界</label></li>
                    </ul>
                </div>
            </div>
             <div class="formitm">
                <label class="lab">描述：</label>
                <div class="ipt">
                    <textarea name="brandname"    value="<?php echo $this->brandInfo['Description']; ?>" class="u-ipt"></textarea> 
                </div>
            </div>
            <div class="formitm formitm-1">
                <input type="hidden" name="user_id" value="<?php echo intval($this->userInfo['UserId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/brand-info.js'); ?>"></script>