<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('goods/brand/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
        <li>
            <a href="#">
                <i class="iconfont">&#xf013f;</i>
                删除
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">格边框</th>
            <th>表头</th>
            <th class="cola">表头</th>
            <th class="cola">表头</th>
            <th class="colb">表头</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td>内容</td>
            <td>内容内容内容内容内容内容内容</td>
            <td>内容内容</td>
            <td>内容内容</td>
            <td>内容内容内容</td>
        </tr>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>