<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('goods/brand/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
        <li>
            <a href="#">
                <i class="iconfont">&#xf013f;</i>
                删除
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th class="cola">排序</th>
            <th>品牌名称</th>
            <th>网址</th>
            <th class="cola">品牌分类</th>
            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach( $this->rows as $brand) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td><?php echo $brand['Sort']; ?></td>
            <td>
                <a href="<?php echo $this->baseUrl('goods/brand/info?brand_id=' .  $brand['BrandId']); ?>">
                <?php echo $brand['Name']; ?>
                </a>
            </td>
            <td><?php echo $brand['Url']; ?></td>
            <td><?php
                $cats = explode(',', $brand['BrandCategoryIds']);
                $names= array();
                foreach ($cats as $cat) {
                    if( isset($this->brandcategories[$cat]) )
                    $names[] = $this->brandcategories[$cat];
                }
                echo implode(',', $names);
            ?>
            </td>
            <td>
                <a href="#" href="#" class="btnDelete" data-id="<?php echo $brand['BrandId']; ?>" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/brand-list.js'); ?>"></script>
