<div class="container">
    <?php
    echo $this->partial('shared/header.phtml', array(
        'module' => $this->module,
        'config' => $this->config,
        'currentUser' => $this->currentUser,
        'userContext' => $this->userContext));
    ?>
</div>
<div class="my_container">
    <?php
    echo $this->partial('shared/leftnav.phtml', array('active' => 4, 'currentUser' => $this->currentUser));
    ?>
    <div class="my_right g_mc">
        <?php
        echo $this->partial('shared/topnavstylist.phtml', array('action' => $this->action));
        ?>
        <div style="padding: 15px 0 0 15px;">
            <div class="Dynamic_gmc">
                <div id="tagContent0" class="selectTag">
                    <?php foreach ($this->dataList as $note): ?>
                    <div class="Dynamicitem">
                        <div class="photo">
                            <img src="<?php echo $this->userInfo['AvatarUrl']; ?>" class="photoimg">
                            <span class="mask_side_100"></span>
                        </div>
                        <div class="darrow">
                        </div>
                        <div class="dcontent">
                            <div class="pannel">
                                <div class="username">
                                    <a href="#"><?php echo $this->userInfo['Nickname']; ?></a>
                                    <span class="date"><?php echo date('m月d日  H:i', strtotime($note['CreatedDate'])); ?></span>
                                </div>
                            </div>
                            <div class="dbody">
                                <ul>
                                    <?php if (count($note['PictureUrl']) > 0): ?>
                                    <li>
                                        <?php foreach ($note['PictureUrl'] as $pic): ?>
                                        <img src="<?php echo $pic; ?>"/>
                                        <?php endforeach; ?>
                                    </li>
                                    <?php endif; ?>
                                    <li class="cdetail">
                                        <p>
                                            <?php echo $note['Body']; ?>
                                        </p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="clearfix"></div>
            <?php echo $this->pager; ?>
        </div>
    </div>
</div>