<?php
use Welfony\Core\Enum\AppointmentStatus;
use Welfony\Utility\Converter;
?>
<div class="container">
    <?php
    echo $this->partial('shared/header.phtml', array(
        'module' => $this->module,
        'config' => $this->config,
        'currentUser' => $this->currentUser,
        'userContext' => $this->userContext));
    ?>
</div>
<div class="my_container">
    <?php
    echo $this->partial('shared/leftnav.phtml', array('active' => 4, 'currentUser' => $this->currentUser));
    ?>
    <div class="my_right g_mc">
        <?php
        echo $this->partial('shared/topnavstylist.phtml', array('action' => $this->action));
        ?>
        <div id="tagContent">
            <div class="tagContent selectTag" id="tagContent0">
                <table class="bought-table">
                    <colgroup>
                        <col class="baobei" />
                        <col class="price" />
                        <col class="trade-status" />
                        <col class="trade-operate" />
                    </colgroup>
                    <thead>
                        <tr class="col-name">
                            <th colspan="3">
                                项目
                            </th>
                            <th>
                                费用
                            </th>
                            <th>
                                状态
                            </th>
                            <th>
                                操作
                            </th>
                        </tr>
                    </thead>
                    <?php foreach ($this->appointmentList as $appointment): ?>
                    <tbody>
                        <tr class="sep-row">
                            <td colspan="6"></td>
                        </tr>
                        <tr class="col-name_1">
                            <th>
                                <span>
                                    <input name="appointment_id" type="checkbox" value="<?php echo $appointment['AppointmentId']; ?>" class="checkinput" />
                                </span>
                                <span>
                                    订单号：<?php echo $appointment['AppointmentNo']; ?>
                                </span>
                            </th>
                            <th colspan="5">
                                <a href="<?php echo $this->baseUrl('salon/index/detail?salon_id=' . $appointment['CompanyId']); ?>">
                                    <?php echo $appointment['CompanyName']; ?>
                                </a>
                            </th>
                        </tr>
                        <tr class="order-bd">
                            <td colspan="3">
                                <div class="chaterphoto">
                                    <a href="javascript:;">
                                        <img src="<?php echo str_replace('480x480', '110x110', $appointment['AvatarUrl']); ?>" />
                                        <span class="mask_side_100"></span>
                                    </a>
                                </div>
                                <div class="chaterbaobei">
                                    <ul>
                                        <li>
                                            <a href="javascript:;">
                                                <?php echo $appointment['ServiceTitle']; ?>
                                            </a>
                                        </li>
                                        <li>
                                            <span>
                                                预约人：<?php echo $appointment['Nickname']; ?>
                                            </span>
                                        </li>
                                        <li>
                                            <span>
                                                预约时间：<?php echo date('Y-m-d H:i', strtotime($appointment['AppointmentDate'])); ?>
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                                <div class="chatercount">
                                    <ul>
                                        <li>
                                            ￥<?php echo number_format($appointment['Price'], 2); ?>
                                        </li>
                                        <li>
                                            1
                                        </li>
                                    </ul>
                                </div>
                                <div class="chateaddress">
                                    地址：<?php echo $appointment['CompanyArea'] . ' ' . $appointment['CompanyAddress']; ?>
                                </div>
                            </td>
                            <td>
                                ￥<?php echo number_format($appointment['Price'], 2); ?>
                            </td>
                            <td>
                                <?php echo Converter::appointmentStatusFromEnumToString($appointment['Status']); ?>
                            </td>
                            <td>
                                <?php if ($appointment['Status'] == AppointmentStatus::Paid): ?>
                                <button class="btn btn2_xl btn2_l appointment-complete" data-appointment-id="<?php echo $appointment['AppointmentId']; ?>">
                                    <span class="t1">
                                        完成
                                    </span>
                                </button>
                                <br/>
                                <br/>
                                <button class="btn btn2_xl btn2_l appointment-cancel" data-appointment-id="<?php echo $appointment['AppointmentId']; ?>">
                                    <span class="t1">
                                        取消
                                    </span>
                                </button>
                                <?php endif; ?>
                                <?php if ($appointment['Status'] == AppointmentStatus::Completed): ?>
                                <a class="btn btn2_xl btn2_l appointment-note" href="<?php echo $this->baseUrl('user/appointment/note?appointment_id=' . $appointment['AppointmentId']); ?>">
                                    <span class="t1">
                                        效果图
                                    </span>
                                </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    </tbody>
                    <?php endforeach; ?>
                </table>
            </div>
            <?php echo $this->pager; ?>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    initAppointAction();
});
</script>