<div class="container">
    <?php
    echo $this->partial('shared/header.phtml', array(
        'module' => $this->module,
        'config' => $this->config,
        'currentUser' => $this->currentUser,
        'userContext' => $this->userContext));
    ?>
</div>
<div class="my_container">
    <?php
    echo $this->partial('shared/leftnav.phtml', array('active' => 4, 'currentUser' => $this->currentUser));
    ?>
    <div class="my_right g_mc">
        <?php
        echo $this->partial('shared/topnavstylist.phtml', array('action' => $this->action));
        ?>
        <div style="padding: 15px 0 0 15px;">
            <div class="card-container">
            <?php foreach ($this->dataList as $client): ?>
            <div class="card-list">
                <div class="card-list-inner">
                    <div class="card-img">
                        <a href="javascript:;">
                            <img src="<?php echo $client['AvatarUrl']; ?>" onerror="this.src='<?php echo $this->config->asset->baseUrl; ?>/img/photo-default.png';" />
                        </a>
                    </div>
                    <div class="card-info">
                        <div class="username">
                            <strong>
                                <a href="javascript:;"><?php echo $client['Nickname']; ?></a>
                            </strong>
                        </div>
                        <p class="card-info-first" style="margin-top: 20px;">
                            <a class="btn btn2_xl btn2_l" href="<?php echo $this->baseUrl('user/stylist/clientappointment?client_id=' . $client['UserId']);?>">查看所有预约</a>
                            <a class="btn btn2_xl btn2_l" href="<?php echo $this->baseUrl('user/stylist/clientnote?client_id=' . $client['UserId']);?>">查看所有效果图</a>
                        </p>
                        <div class="card-action-bar">
                            <ul>
                                <li><span>累计预约：<?php echo $client['AppointmentCount']; ?></span></li>
                                <li><span>完成预约：<?php echo $client['CompletedAppointmentCount']; ?></span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            </div>
        </div>
        <div class="clearfix"></div>
        <?php echo $this->pager; ?>
    </div>
</div>