<?php
use \Welfony\Utility\Util;
?>
<div class="container">
    <?php
    echo $this->partial('shared/header.phtml', array(
        'module' => $this->module,
        'config' => $this->config,
        'currentUser' => $this->currentUser,
        'userContext' => $this->userContext));
    ?>
</div>
<div class="my_container">
    <?php
    echo $this->partial('shared/leftnav.phtml', array('active' => 4, 'currentUser' => $this->currentUser));
    ?>
    <div class="my_right g_mc">
        <?php
        echo $this->partial('shared/topnavstylist.phtml', array('action' => $this->action));
        ?>
        <div style="padding: 15px 0 0 15px;">
            <div class="m-form">
                <form id="frm-work-info" method="post">
                    <fieldset>
                        <div class="formitm">
                            <label class="lab">作品图：</label>
                            <div class="ipt">
                                <ul class="formimglst clearfix">
                                    <?php if (count($this->workInfo['PictureUrl']) > 0): ?>
                                    <?php foreach ($this->workInfo['PictureUrl'] as $pic): ?>
                                    <li>
                                        <span class="u-img2">
                                            <a href="javascript:;">
                                                <img class="work-picture" src="<?php echo $pic; ?>" />
                                            </a>
                                        </span>
                                        <input type="hidden" value="<?php echo $pic; ?>" name="work_picture_url[]" />
                                        <a style="visibility: hidden;" href="#">调整缩略图</a>
                                        <a class="remove-thumb" href="#">移除</a>
                                    </li>
                                    <?php endforeach; ?>
                                    <?php endif; ?>
                                    <li<?php echo count($this->workInfo['PictureUrl']) >= 6 ? ' style="display: none;"' : ''; ?>>
                                        <span class="u-img2">
                                            <a id="work-image-uploader"></a>
                                        </span>
                                    </li>
                                </ul>
                                <p>多角度展示作品，仅限同一款发型作品哦。</p>
                            </div>
                        </div>
                        <div class="formitm">
                            <label class="lab">标题：</label>
                            <div class="ipt">
                                <input name="title" type="text" value="<?php echo $this->workInfo['Title']; ?>" datatype="*" class="u-ipt"/>
                            </div>
                        </div>
                        <div class="formitm">
                            <label class="lab">性别：</label>
                            <div class="ipt">
                                <span class="u-btns enable" data-type="radio">
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['Gender'] == 1 ? '5' : '4'; ?>" data-value="1">男</span>
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['Gender'] == 2 ? '5' : '4'; ?>" data-value="2">女</span>
                                    <input type="hidden" name="gender" value="<?php echo $this->workInfo['Gender']; ?>" />
                                </span>
                            </div>
                        </div>
                        <div class="formitm">
                            <label class="lab">脸型：</label>
                            <div class="ipt">
                                <?php
                                $hairSelected = explode(',', $this->workInfo['Face']);
                                ?>
                                <span class="u-btns enable" data-type="checkbox">
                                    <span class="u-btn u-btn-c<?php echo in_array(1, $hairSelected) ? '5' : '4'; ?>" data-value="1">圆脸</span>
                                    <span class="u-btn u-btn-c<?php echo in_array(2, $hairSelected) ? '5' : '4'; ?>" data-value="2">瓜子脸</span>
                                    <span class="u-btn u-btn-c<?php echo in_array(3, $hairSelected) ? '5' : '4'; ?>" data-value="3">方脸</span>
                                    <span class="u-btn u-btn-c<?php echo in_array(4, $hairSelected) ? '5' : '4'; ?>" data-value="4">长脸</span>
                                    <input type="hidden" name="face" datatype="*" value="<?php echo $this->workInfo['Face']; ?>" />
                                </span>
                            </div>
                        </div>
                        <div class="formitm">
                            <label class="lab">发型：</label>
                            <div class="ipt">
                                <span class="u-btns enable" data-type="radio">
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['HairStyle'] == 1 ? '5' : '4'; ?>" data-value="1">短发</span>
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['HairStyle'] == 2 ? '5' : '4'; ?>" data-value="2">长发</span>
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['HairStyle'] == 3 ? '5' : '4'; ?>" data-value="3">编发</span>
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['HairStyle'] == 4 ? '5' : '4'; ?>" data-value="4">中发</span>
                                    <input type="hidden" name="hair_style" value="<?php echo $this->workInfo['HairStyle']; ?>" />
                                </span>
                            </div>
                        </div>
                        <div class="formitm">
                            <label class="lab">发量：</label>
                            <div class="ipt">
                                <span class="u-btns enable" data-type="radio">
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['HairAmount'] == 1 ? '5' : '4'; ?>" data-value="1">多密</span>
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['HairAmount'] == 2 ? '5' : '4'; ?>" data-value="2">中等</span>
                                    <span class="u-btn u-btn-c<?php echo $this->workInfo['HairAmount'] == 3 ? '5' : '4'; ?>" data-value="3">偏少</span>
                                    <input type="hidden" name="hair_amount" value="<?php echo $this->workInfo['HairAmount']; ?>" />
                                </span>
                            </div>
                        </div>
                        <div class="formitm formitm-1">
                            <input type="hidden" name="hair_id" value="<?php echo intval($this->workInfo['WorkId']); ?>" />
                            <button class="u-btn u-btn-submit" type="button">确定</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(function() {
    $('#frm-work-info').Validform({
        tiptype: 3
    });

    function initUploader() {
        var liUploader = $('#work-image-uploader').parent().parent();
        function updateLiUploaderStatus() {
            if ($('input[name="work_picture_url[]"]').length >= 6) {
                liUploader.hide();
            } else {
                liUploader.show();
            }
        }
        function bindRemove() {
            $('.formimglst .remove-thumb').click(function() {
                $(this).parent().fadeOut('normal', function() {
                    $(this).remove();
                    updateLiUploaderStatus();
                });

                return false;
            });
        }
        bindRemove();

        var popup = $(' \
            <div class="crop-container"> \
                <div class="crop-content"> \
                    <img class="crop-img-o" src=""/> \
                    <input type="hidden" name="x1" value="" /> \
                    <input type="hidden" name="y1" value="" /> \
                    <input type="hidden" name="x2" value="" /> \
                    <input type="hidden" name="y2" value="" /> \
                </div> \
                <div class="crop-preview"> \
                    <p>拖拽或缩放曲线框，<br/>生成方形图片。</p> \
                    <div class="crop-preview-110"> \
                        <img class="crop-img-preview-110" src="" /> \
                    </div> \
                    <p>110*110像素</p> \
                    <div class="crop-preview-64"> \
                        <img class="crop-img-preview-64" src="" /> \
                    </div> \
                    <p>64*64像素</p> \
                    <div class="crop-preview-30"> \
                        <img class="crop-img-preview-30" src="" /> \
                    </div> \
                    <p>30*30像素</p> \
                </div> \
            </div> \
        ');

        $('#work-image-uploader').uploadify({
            fileObjName: 'uploadfile',
            width: 102,
            height: 102,
            multi: false,
            checkExisting: false,
            preventCaching: false,
            fileExt: '*.jpg;*.jpeg;*.png',
            fileDesc: 'Image file (.jpg, .jpeg, .png)',
            buttonText: '<i class="iconfont">&#xf0175;</i>',
            swf: WF.setting.staticAssetBaseUrl + '/swf/uploadify.swf',
            uploader: WF.setting.apiBaseUrl + '/upload/image',
            onUploadError: function(file, errorCode, errorMsg, errorString) {
                console.log(errorString);
            },
            onUploadSuccess: function(file, data, response) {
                var result = $.parseJSON(data);
                if (result.success !== false) {
                    var imgTemplate = $(' \
                        <li> \
                            <span class="u-img2"> \
                                <a href="javascript:;"> \
                                    <img class="work-picture" /> \
                                </a> \
                            </span> \
                            <input type="hidden" value="" name="work_picture_url[]" /> \
                            <a class="work-picture-update update-thumb" href="#">调整缩略图</a> \
                            <a class="remove-thumb" href="#">移除</a> \
                        </li> \
                    ');

                    imgTemplate.find('img').attr('src', result.Thumb110Url)
                                           .attr('data-110', result.Thumb110Url)
                                           .attr('data-ori', result.OriginalUrl);
                    imgTemplate.find('input[type=hidden]').val(result.Thumb480Url);

                    imgTemplate.insertBefore(liUploader).hide().fadeIn();

                    bindRemove();

                    imgTemplate.find('.update-thumb').click(function() {
                        var crop = null;
                        var img = $(this).parent().find('.work-picture');
                        var imgUrl = img.attr('data-ori');
                        if (!imgUrl) {
                            WF.showMessage('error', '注意', '请先上传一张图片');
                            return false;
                        }

                        $(popup).dialog({
                            resizable: false,
                            title: '编辑缩略图',
                            width: 600,
                            height:500,
                            modal: true,
                            draggable: false,
                            buttons: {
                                '保存': function() {
                                    var opts = {
                                        type: 'POST',
                                        url: WF.setting.apiBaseUrl + '/upload/image/crop',
                                        dataType: 'json',
                                        data: {
                                            x1: $('input[name="x1"]').val(),
                                            y1: $('input[name="y1"]').val(),
                                            x2: $('input[name="x2"]').val(),
                                            y2: $('input[name="y2"]').val(),
                                            img: img.attr('data-ori')
                                        },
                                        success: function(data, textStatus, jqXHR) {
                                            img.attr('src', img.attr('data-110') + '?timestamp=' + new Date().getTime());
                                            popup.dialog('close');
                                        }
                                    };
                                    $.ajax(opts);
                                },
                                '取消': function() {
                                    $(this).dialog('close');
                                }
                            },
                            open: function() {
                                var imgO = popup.find('.crop-img-o');
                                imgO.attr('src', imgUrl);

                                var imgPreview110 = popup.find('.crop-img-preview-110');
                                imgPreview110.attr('src', imgUrl).removeAttr('style');

                                var imgPreview64 = popup.find('.crop-img-preview-64');
                                imgPreview64.attr('src', imgUrl).removeAttr('style');

                                var imgPreview30 = popup.find('.crop-img-preview-30');
                                imgPreview30.attr('src', imgUrl).removeAttr('style');

                                WF.getImageSize(imgUrl, function(width, height) {
                                    if (width >= height) {
                                        imgO.css('width', imgO.parent().width())
                                            .css('height', 'auto')
                                            .css('margin-top', (imgO.parent().height() - imgO.height()) / 2)
                                            .show();
                                    } else {
                                        imgO.css('height', imgO.parent().height())
                                        .css('width', 'auto')
                                        .css('margin-left', (imgO.parent().width() - imgO.width()) / 2)
                                        .show();
                                    }

                                    crop = imgO.imgAreaSelect({
                                        instance: true,
                                        handles: true,
                                        aspectRatio: '1:1',
                                        onSelectEnd: function(img, selection) {
                                            var rate = width / imgO.width();

                                            $('input[name="x1"]').val(selection.x1 * rate);
                                            $('input[name="y1"]').val(selection.y1 * rate);
                                            $('input[name="x2"]').val(selection.x2 * rate);
                                            $('input[name="y2"]').val(selection.y2 * rate);
                                        },
                                        onSelectChange: function(img, selection) {
                                            var imgOWith = imgO.width();
                                            var imgOHeight = imgO.height();

                                            var scaleX = 110 / (selection.width || 1);
                                            var scaleY = 110 / (selection.height || 1);
                                            imgPreview110.css({
                                                width: Math.round(scaleX * imgOWith) + 'px',
                                                height: Math.round(scaleY * imgOHeight) + 'px',
                                                marginLeft: '-' + Math.round(scaleX * selection.x1) + 'px',
                                                marginTop: '-' + Math.round(scaleY * selection.y1) + 'px'
                                            });

                                            scaleX = 64 / (selection.width || 1);
                                            scaleY = 64 / (selection.height || 1);
                                            imgPreview64.css({
                                                width: Math.round(scaleX * imgOWith) + 'px',
                                                height: Math.round(scaleY * imgOHeight) + 'px',
                                                marginLeft: '-' + Math.round(scaleX * selection.x1) + 'px',
                                                marginTop: '-' + Math.round(scaleY * selection.y1) + 'px'
                                            });

                                            scaleX = 30 / (selection.width || 1);
                                            scaleY = 30 / (selection.height || 1);
                                            imgPreview30.css({
                                                width: Math.round(scaleX * imgOWith) + 'px',
                                                height: Math.round(scaleY * imgOHeight) + 'px',
                                                marginLeft: '-' + Math.round(scaleX * selection.x1) + 'px',
                                                marginTop: '-' + Math.round(scaleY * selection.y1) + 'px'
                                            });
                                        }
                                    });
                                });
                            },
                            close: function() {
                                if (crop) {
                                    crop.remove(true);
                                }
                                popup.dialog('destroy').remove();
                            }
                        });

                        return false;
                    });

                    updateLiUploaderStatus();
                } else {
                    WF.showMessage('error', '错误', '上传失败，请重试！');
                }
            }
        });
    }

    initUploader();
});
</script>