<div class="container">
    <?php
    echo $this->partial('shared/header.phtml', array(
        'module' => $this->module,
        'config' => $this->config,
        'currentUser' => $this->currentUser,
        'userContext' => $this->userContext));
    ?>
    <!-- 主体内容 开始 -->
    <div class="my_container">
        <?php
        echo $this->partial('shared/leftnav.phtml', array('active' => 3));
        ?>
        <div class="my_right g_mc">
        </div>
    </div>
</div>