<?php
use Welfony\Utility\Converter;
use Welfony\Utility\Util;
?>
<table class="m-table">
    <thead>
        <tr>
            <th>类别</th>
            <th>金额</th>
            <th>时间</th>
            <th>描述</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($this->dataList) > 0): ?>
        <?php foreach ($this->dataList as $data): ?>
            <td>
                <?php if ($data['IncomeSrc'] == 1 || $data['IncomeSrc'] == 6): ?>
                商品
                <?php endif; ?>
                <?php if ($data['IncomeSrc'] == 2 || $data['IncomeSrc'] == 5): ?>
                预约
                <?php endif; ?>
            </td>
            <td><?php echo $data['Amount']; ?></td>
            <td><?php echo $data['CreateTime']; ?></td>
            <td><?php echo $data['Description']; ?></td>
        </tr>
        <?php endforeach; ?>
        <?php else: ?>
        <tr>
            <td class="col-center" colspan="4">您还没有添加任何记录</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->pager; ?>