<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-freight-info" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">物流公司：</label>
                <div class="ipt">
                     <select id="freighttype" name="freighttype" class="u-sel">
                            <option value="CNEMS" <?php echo $this->freightInfo['FreightType'] == 'CNEMS'? 'selected':''; ?>>中国邮政EMS </option>
                            <option value="CNST" <?php echo $this->freightInfo['FreightType'] == 'CNST'? 'selected':''; ?>>申通快递 </option>
                            <option value="CNTT" <?php echo $this->freightInfo['FreightType'] == 'CNTT'? 'selected':''; ?>>天天快递 </option>
                            <option value="CNYT" <?php echo $this->freightInfo['FreightType'] == 'CNYT'? 'selected':''; ?>>圆通速递 </option>
                            <option value="CNSF" <?php echo $this->freightInfo['FreightType'] == 'CNSF'? 'selected':''; ?>>顺丰速运 </option>
                            <option value="CNYD" <?php echo $this->freightInfo['FreightType'] == 'CNYD'? 'selected':''; ?>>韵达快递 </option>
                            <option value="CNZT" <?php echo $this->freightInfo['FreightType'] == 'CNZT'? 'selected':''; ?>>中通速递 </option>
                            <option value="CNLB" <?php echo $this->freightInfo['FreightType'] == 'CNLB'? 'selected':''; ?>>龙邦物流 </option>
                            <option value="CNZJS" <?php echo $this->freightInfo['FreightType'] == 'CNZJS'? 'selected':''; ?>>宅急送 </option>
                            <option value="CNQY" <?php echo $this->freightInfo['FreightType'] == 'CNQY'? 'selected':''; ?>>全一快递 </option>
                            <option value="CNHT" <?php echo $this->freightInfo['FreightType'] == 'CNHT'? 'selected':''; ?>>汇通速递 </option>
                            <option value="CNMH" <?php echo $this->freightInfo['FreightType'] == 'CNMH'? 'selected':''; ?>>民航快递 </option>
                            <option value="CNYF" <?php echo $this->freightInfo['FreightType'] == 'CNYF'? 'selected':''; ?>>亚风速递 </option>
                            <option value="CNKJ" <?php echo $this->freightInfo['FreightType'] == 'CNKJ'? 'selected':''; ?>>快捷速递 </option>
                            <option value="DDS" <?php echo $this->freightInfo['FreightType'] == 'DDS'? 'selected':''; ?>>DDS快递 </option>
                            <option value="CNHY" <?php echo $this->freightInfo['FreightType'] == 'CNHY'? 'selected':''; ?>>华宇物流 </option>
                            <option value="CNZY" <?php echo $this->freightInfo['FreightType'] == 'CNZY'? 'selected':''; ?>>中铁快运 </option>
                            <option value="FEDEX" <?php echo $this->freightInfo['FreightType'] == 'FEDEX'? 'selected':''; ?>>FedEx </option>
                            <option value="UPS" <?php echo $this->freightInfo['FreightType'] == 'UPS'? 'selected':''; ?>>UPS </option>
                            <option value="DHL" <?php echo $this->freightInfo['FreightType'] == 'DHL'? 'selected':''; ?>>DHL </option>
                            <option value="OTHER" <?php echo $this->freightInfo['FreightType'] == 'OTHER'? 'selected':''; ?>>其它 </option>
                        </select>
                     <p></p>
                </div>
            </div>
           <div class="formitm">
                <label class="lab">物流公司全称：</label>
                <div class="ipt">
                    <input id="freightname" type="text"  datatype="*" value="<?php echo $this->freightInfo['FreightName']; ?>"  errormsg="名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">物流公司网址：</label>
                <div class="ipt">
                    <input id="url" type="text" value="<?php echo $this->freightInfo['Url']; ?>"   class="u-ipt"/>
                </div>
            </div>
            <div class="formitm">
                <label class="lab">排序：</label>
                <div class="ipt">
                    <input id="sort" type="text" value="<?php echo $this->freightInfo['Sort']; ?>"  datatype="n" class="u-ipt"/>
                </div>
            </div>



            <div class="formitm formitm-1">
                <input type="hidden" name="freight_id" value="<?php echo intval($this->freightInfo['FreightId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/freight-info.js'); ?>"></script>