<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('system/freight/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th>物流名称</th>
            <th>URL</th>
            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach( $this->rows as $freight) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td><a href="<?php echo $this->baseUrl('system/freight/info?freight_id=' .  $freight['FreightId']); ?>">
                <?php echo $freight['FreightName']; ?>
                </a>
            </td>
            <td>
                <?php echo $freight['Url']; ?>
            </td>
            <td>
                <a href="#" href="#" class="btnDelete" data-id="<?php echo $freight['FreightId']; ?>" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/freight-list.js'); ?>"></script>