<div class="container">
    <?php
    echo $this->partial('shared/header.phtml', array(
        'module' => $this->module,
        'config' => $this->config,
        'currentUser' => $this->currentUser,
        'userContext' => $this->userContext));
    ?>
</div>
<div class="my_container">
    <?php
    echo $this->partial('shared/leftnav.phtml', array('active' => 4, 'currentUser' => $this->currentUser));
    ?>
    <div class="my_right g_mc">
        <?php
        echo $this->partial('shared/topnavsalon.phtml', array('action' => $this->action));
        ?>
        <div style="padding: 15px 0 0 15px;">
            <div class="toolbar">
                <ul class="clearfix">
                    <li>
                        <a href="<?php echo $this->baseUrl('user/salon/account'); ?>">
                            <i class="iconfont">&#xf0112;</i>
                            返回
                        </a>
                    </li>
                </ul>
            </div>
            <table class="m-table">
                    <thead>
                        <tr>
                            <th>编号</th>
                            <th>状态</th>
                            <th>金额</th>
                            <th>日期</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->dataList as $withdraw): ?>
                        <tr>
                            <td>
                                <?php echo $withdraw['WithdrawalNo']; ?>
                            </td>
                            <td>
                                <?php echo $withdraw['Status'] =='0' ? '新建' :($withdraw['Status'] =='1'? '已批准': '已拒绝'); ?>
                            </td>
                            <td>
                                ￥<?php echo $withdraw['Amount']; ?>
                            </td>
                            <td>
                                <?php echo date('Y-m-d H:i', strtotime($withdraw['LastUpdateDate'])); ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php echo $this->pager; ?>
            </div>
        </div>
    </div>
</div>