<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-delivery-info" method="post">
        <fieldset>
            <div class="formitm">
                <label class="lab">配送方式名称：</label>
                <div class="ipt">
                    <input id="deliveryname" type="text"  datatype="*" value="<?php echo $this->deliveryInfo['Name']; ?>"  errormsg="名称不能为空！" class="u-ipt"/> *
                </div>
            </div>
            <div class="formitm">
                <label class="lab">物流公司：</label>
                <div class="ipt">
                     <select id="freight" name="freight" class="u-sel">
                            <?php foreach( $this->freights as $freight ): ?>
                            <option value="<?php echo $freight['FreightId'] ?>" <?php echo $this->delvieryInfo['FreightId'] == $freight['FreightId'] ? 'selected':''; ?>><?php echo  $freight['FreightName'] ;?> </option>
                            <?php endforeach; ?>
                        </select>
                     <p>选择此配送方式所使用的物流公司</p>
                </div>
            </div>
         
            <div class="formitm">
                <label class="lab">类型：</label>
                <div class="ipt">
                   
                        <label class="attr"><input type="radio" <?php echo $this->deliveryInfo['Type']? '':'checked' ?> name="deliverytype" value="0">先收款后发货</label>
                        <label class="attr"><input type="radio" <?php echo $this->deliveryInfo['Type']? 'checked':'' ?> name="deliverytype" value="1">货到付款</label>
                        <p>货到付款选择货到付款后顾客无需再选择支付方式</p>
                    
                </div>
            </div>
            <div class="formitm">
                <label class="lab">重量设置：</label>
                <div class="ipt">
                    <label class="attr">
                            首重重量
                            <select pattern="int" id="first_weight">
                                <option  <?php echo $this->deliveryInfo['FirstWeight'] =='500'? 'selected':''; ?> value="500" label="500克">500克</option>
                                <option   <?php echo $this->deliveryInfo['FirstWeight'] =='1000'? 'selected':''; ?> value="1000" label="1公斤">1公斤</option>
                                <option   <?php echo $this->deliveryInfo['FirstWeight'] =='1200'? 'selected':''; ?> value="1200" label="1.2公斤">1.2公斤</option>
                                <option  <?php echo $this->deliveryInfo['FirstWeight'] =='2000'? 'selected':''; ?>  value="2000" label="2公斤">2公斤</option>
                                <option   <?php echo $this->deliveryInfo['FirstWeight'] =='5000'? 'selected':''; ?> value="5000" label="5公斤">5公斤</option>
                                <option   <?php echo $this->deliveryInfo['FirstWeight'] =='10000'? 'selected':''; ?> value="10000" label="10公斤">10公斤</option>
                                <option   <?php echo $this->deliveryInfo['FirstWeight'] =='20000'? 'selected':''; ?> value="20000" label="20公斤">20公斤</option>
                                <option   <?php echo $this->deliveryInfo['FirstWeight'] =='50000'? 'selected':''; ?> value="50000" label="50公斤">50公斤</option>
                            </select>
                        </label>

                        <label class="attr">首重费用<input type="text" alt="该项必填且只允许填写数字金额" pattern="float" value="<?php echo $this->deliveryInfo['FirstPrice']; ?>" id="first_price" class="tiny">元</label>

                        <label class="attr">
                            续重重量
                            <select pattern="int" id="second_weight">
                                <option  <?php echo $this->deliveryInfo['SecondWeight'] =='500'? 'selected':''; ?> value="500" label="500克">500克</option>
                                <option  <?php echo $this->deliveryInfo['SecondWeight'] =='1000'? 'selected':''; ?> value="1000" label="1公斤">1公斤</option>
                                <option  <?php echo $this->deliveryInfo['SecondWeight'] =='1200'? 'selected':''; ?>  value="1200" label="1.2公斤">1.2公斤</option>
                                <option <?php echo $this->deliveryInfo['SecondWeight'] =='2000'? 'selected':''; ?>  value="2000" label="2公斤">2公斤</option>
                                <option <?php echo $this->deliveryInfo['SecondWeight'] =='5000'? 'selected':''; ?>   value="5000" label="5公斤">5公斤</option>
                                <option  <?php echo $this->deliveryInfo['SecondWeight'] =='10000'? 'selected':''; ?> value="10000" label="10公斤">10公斤</option>
                                <option  <?php echo $this->deliveryInfo['SecondWeight'] =='20000'? 'selected':''; ?> value="20000" label="20公斤">20公斤</option>
                                <option  <?php echo $this->deliveryInfo['SecondWeight'] =='50000'? 'selected':''; ?> value="50000" label="50公斤">50公斤</option>
                            </select>
                        </label>

                        <label class="attr">续重费用<input type="text" alt="该项必填且只允许填写数字金额" pattern="float" value="<?php echo $this->deliveryInfo['SecondPrice']; ?>" id="second_price" class="tiny">元</label>

                        <p><label>根据重量来计算运费，当物品不足《首重重量》时，按照《首重费用》计算，超过部分按照《续重重量》和《续重费用》乘积来计算</label></p>
                </div>
            </div>

           <div class="formitm">
                <label class="lab">支持保价:</label>
                <div class="ipt">
                   
                        <label class="attr"><input type="checkbox" onclick="$('#protectBox').toggle();" value="1" id="is_save_price" <?php echo $this->deliveryInfo['IsSavePrice']? 'checked':'' ?> >支持物流保价</label>

                        <!--支持保价隐藏域-->
                        <span style="<?php echo $this->deliveryInfo['IsSavePrice']? '':'display: none;' ?>" id="protectBox">
                            <label class="attr">费率<input type="text" alt="该项必填且只允许填写数字金额" pattern="float" class="tiny" value="<?php echo $this->deliveryInfo['SaveRate']; ?>" data-type="n" id="save_rate">%</label>
                            <label class="attr">最低保价费<input type="text" alt="该项必填且只允许填写数字金额" pattern="float" class="tiny" value="<?php echo $this->deliveryInfo['LowPrice']; ?>" data-type="n" id="low_price">元</label>
                            <label>当用户需要保价后，一般是按照货物总金额的《费率》计算，但是保价金额最低不低于《最低保价费》</label>
                        </span>
                    
                </div>
            </div>

             <div class="formitm">
                <label class="lab">设置地区运费:</label>
                <div class="ipt">
                   
                        <label class="attr"><input type="radio" <?php echo $this->deliveryInfo['PriceType']? '':'checked' ?>  value="0" name="price_type">统一地区运费</label>
                        <label class="attr"><input type="radio" <?php echo $this->deliveryInfo['PriceType']? 'checked':'' ?> value="1" name="price_type">指定地区运费</label>
                        <p>《统一地区运费》：全部的地区都使用默认的《重量设置》中的计费方式。《指定地区运费》：单独指定部分地区的运费</p>
                    
                </div>
            </div>
            <div id="areaBox" style="<?php echo $this->deliveryInfo['PriceType']? '':'display:none;' ?>">
                <div class="formitm">
                    <label class="lab"></label>
                    <div class="ipt">                   
                              
                            <label class="attr"><input type="checkbox"  <?php echo $this->deliveryInfo['OpenDefault']? 'checked':'' ?> value="1" name="open_default">地区默认运费</label>
                            <p>注意：如果不开启此项，那么未设置的地区将无法送达！</p>
                        
                    </div>
                </div>

                 <div class="formitm">
                    <label class="lab"></label>
                    <div class="ipt" id="areaList">   
                        <?php if(strlen(trim($this->deliveryInfo['AreaGroupId'])) == 0 ) :?>                    
                        <div style="padding:6px" class="content_box">
                          <label class='attr'>
                                选择地区：
                                <select name="province">
                                        <option value="110000">北京市</option>
                                        <option value="120000">天津市</option>
                                        <option value="130000">河北省</option>
                                        <option value="140000">山西省</option>
                                        <option value="150000">内蒙古自治区</option>
                                        <option value="210000">辽宁省</option>
                                        <option value="220000">吉林省</option>
                                        <option value="230000">黑龙江省</option>
                                        <option value="310000">上海市</option>
                                        <option value="320000">江苏省</option>
                                        <option value="330000">浙江省</option>
                                        <option value="340000">安徽省</option>
                                        <option value="350000">福建省</option>
                                        <option value="360000">江西省</option>
                                        <option value="370000">山东省</option>
                                        <option value="410000">河南省</option>
                                        <option value="420000">湖北省</option>
                                        <option value="430000">湖南省</option>
                                        <option value="440000">广东省</option>
                                        <option value="450000">广西壮族自治区</option>
                                        <option value="460000">海南省</option>
                                        <option value="500000">重庆市</option>
                                        <option value="510000">四川省</option>
                                        <option value="520000">贵州省</option>
                                        <option value="530000">云南省</option>
                                        <option value="540000">西藏自治区</option>
                                        <option value="610000">陕西省</option>
                                        <option value="620000">甘肃省</option>
                                        <option value="630000">青海省</option>
                                        <option value="640000">宁夏回族自治区</option>
                                        <option value="650000">新疆维吾尔自治区</option>
                                </select>
                            </label>                 

                            <a class="t-action btnAddProvince"><i class="iconfont">&#xf0175;</i>添加</a>
                            <label class='attr'>已选择地区：<input class="middle" name="areaName" value="" readonly="readonly" disabled='disabled' /></label>
                            <input type="hidden" name="areagroupid[]" />
                            <label class='attr'>首重费用：<input class="tiny" name="areafirstprice[]" value="" pattern="float" alt="该项必填且只允许填写数字金额" type="text" /></label>
                            <label class='attr'>续重费用：<input class="tiny" name="areasecondprice[]" value="" pattern="float" alt="该项必填且只允许填写数字金额" type="text" /></label>
                           

                            <a  href="javascript:void(0)" class="f_r btnDelete" ><i class="iconfont">&#xf013f;</i></a>
                        </div>
                        <?php else :?> 
                            <?php 
                                $areaIds= json_decode($this->deliveryInfo['AreaGroupId'], true);
                                $areaFirstPrices = json_decode($this->deliveryInfo['AreaFirstPrice'], true);
                                $areaSecondPrices = json_decode($this->deliveryInfo['AreaFirstPrice'], true);
                                $areaArray = array(
                                            '110000'=>'北京市', '120000'=>'天津市','130000'=>'河北省', '140000'=>'山西省',
                                            '150000'=>'内蒙古自治区', '210000'=>'辽宁省', '220000'=>'吉林省', 
                                            '230000'=>'黑龙江省', '310000'=>'上海市', '320000'=> '江苏省', '330000'=>'浙江省', 
                                            '340000'=>'安徽省','350000'=> '福建省', '360000'=> '江西省',
                                            '370000'=>'山东省', '410000'=>'河南省', '420000'=>'湖北省', '430000'=>'湖南省',
                                            '440000'=>'广东省', '450000'=>'广西壮族自治区', '460000'=>'海南省',
                                            '500000'=>'重庆市', '510000'=>'四川省', '520000'=>'贵州省',
                                            '530000'=>'云南省', '540000'=>'西藏自治区', '610000'=>'陕西省',
                                            '620000'=>'甘肃省', '630000'=>'青海省', '640000'=>'宁夏回族自治区',
                                            '650000'=>'新疆维吾尔自治区'
                                );
                             ?>
                            <?php foreach($areaIds as $aIndex => $aValue):?>
                                <div style="padding:6px" class="content_box">
                                  <label class='attr'>
                                        选择地区：
                                        <select name="province">
                                                <option value="110000">北京市</option>
                                                <option value="120000">天津市</option>
                                                <option value="130000">河北省</option>
                                                <option value="140000">山西省</option>
                                                <option value="150000">内蒙古自治区</option>
                                                <option value="210000">辽宁省</option>
                                                <option value="220000">吉林省</option>
                                                <option value="230000">黑龙江省</option>
                                                <option value="310000">上海市</option>
                                                <option value="320000">江苏省</option>
                                                <option value="330000">浙江省</option>
                                                <option value="340000">安徽省</option>
                                                <option value="350000">福建省</option>
                                                <option value="360000">江西省</option>
                                                <option value="370000">山东省</option>
                                                <option value="410000">河南省</option>
                                                <option value="420000">湖北省</option>
                                                <option value="430000">湖南省</option>
                                                <option value="440000">广东省</option>
                                                <option value="450000">广西壮族自治区</option>
                                                <option value="460000">海南省</option>
                                                <option value="500000">重庆市</option>
                                                <option value="510000">四川省</option>
                                                <option value="520000">贵州省</option>
                                                <option value="530000">云南省</option>
                                                <option value="540000">西藏自治区</option>
                                                <option value="610000">陕西省</option>
                                                <option value="620000">甘肃省</option>
                                                <option value="630000">青海省</option>
                                                <option value="640000">宁夏回族自治区</option>
                                                <option value="650000">新疆维吾尔自治区</option>
                                        </select>
                                    </label>                 

                                    <a class="t-action btnAddProvince"><i class="iconfont">&#xf0175;</i>添加</a>
                                    <?php 
                                        $names = [];
                                        if( $aValue)
                                        {
                                            $values = explode(',', $aValue);
                                         
                                            foreach($values as $v)
                                            {
                                                $names[] = $areaArray[$v];
                                            }
                                        }
                                    ?>
                                    <label class='attr'>已选择地区：<input class="middle" name="areaName" value="<?php echo implode(',', $names); ?>" readonly="readonly" disabled='disabled' /></label>
                                    <input type="hidden" name="areagroupid[]" value="<?php echo $aValue; ?>"/>
                                    <label class='attr'>首重费用：<input class="tiny" name="areafirstprice[]" value="<?php echo $areaFirstPrices[$aIndex]; ?>" pattern="float" alt="该项必填且只允许填写数字金额" type="text" /></label>
                                    <label class='attr'>续重费用：<input class="tiny" name="areasecondprice[]" value="<?php echo $areaSecondPrices[$aIndex]; ?>" pattern="float" alt="该项必填且只允许填写数字金额" type="text" /></label>
                                   

                                    <a  href="javascript:void(0)" class="f_r btnDelete" ><i class="iconfont">&#xf013f;</i></a>
                                </div>
                            <?php endforeach;?>
                        <?php endif;?>
                    </div>
                </div>
                <div class="formitm">
                    <label class="lab"></a></label>
                    <div class="ipt">
                        <a class="t-action" id="btnAddArea"><i class="iconfont">&#xf0175;</i>添加地区</a>
                    </div>
                </div>
            </div>

            <div class="formitm">
                <label class="lab">排序</label>
                <div class="ipt">                          
                        <input id="sort" type="text"  datatype="n" value="<?php echo $this->deliveryInfo['Sort']; ?>"   class="u-ipt"/> *
                    
                </div>
            </div>

            <div class="formitm">
                <label class="lab">状态</label>
                <div class="ipt">             
                          
                        <label class='attr'><input name="status" type="radio" value="1" <?php echo $this->deliveryInfo['Status']? 'checked':'' ?> />启用</label>
                        <label class='attr'><input name="status" type="radio" value="0" <?php echo $this->deliveryInfo['Status']? '':'checked' ?>/>关闭</label>
                    
                </div>
            </div>


             <div class="formitm">
                <label class="lab">详细介绍：</label>
                <div class="ipt">
                    <textarea  id='description' type="text"  datatype="s" class="u-ipt"><?php echo $this->deliveryInfo['Description']; ?></textarea>
                    <p></p>
                </div>
            </div>    
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="freight_id" value="<?php echo intval($this->freightInfo['FreightId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<div style="padding:6px;display:none;" class="content_box" id="area_template">
      <label class='attr'>
            选择地区：
            <select name="province">
                    <option value="110000">北京市</option>
                    <option value="120000">天津市</option>
                    <option value="130000">河北省</option>
                    <option value="140000">山西省</option>
                    <option value="150000">内蒙古自治区</option>
                    <option value="210000">辽宁省</option>
                    <option value="220000">吉林省</option>
                    <option value="230000">黑龙江省</option>
                    <option value="310000">上海市</option>
                    <option value="320000">江苏省</option>
                    <option value="330000">浙江省</option>
                    <option value="340000">安徽省</option>
                    <option value="350000">福建省</option>
                    <option value="360000">江西省</option>
                    <option value="370000">山东省</option>
                    <option value="410000">河南省</option>
                    <option value="420000">湖北省</option>
                    <option value="430000">湖南省</option>
                    <option value="440000">广东省</option>
                    <option value="450000">广西壮族自治区</option>
                    <option value="460000">海南省</option>
                    <option value="500000">重庆市</option>
                    <option value="510000">四川省</option>
                    <option value="520000">贵州省</option>
                    <option value="530000">云南省</option>
                    <option value="540000">西藏自治区</option>
                    <option value="610000">陕西省</option>
                    <option value="620000">甘肃省</option>
                    <option value="630000">青海省</option>
                    <option value="640000">宁夏回族自治区</option>
                    <option value="650000">新疆维吾尔自治区</option>
            </select>
        </label>                 

        <a class="t-action btnAddProvince"><i class="iconfont">&#xf0175;</i>添加</a>
        <label class='attr'>已选择地区：<input class="middle" name="areaName" value="" readonly="readonly" disabled='disabled' /></label>
        <input type="hidden" name="areagroupid[]" />
        <label class='attr'>首重费用：<input class="tiny" name="areafirstprice[]" value="" pattern="float" alt="该项必填且只允许填写数字金额" type="text" /></label>
        <label class='attr'>续重费用：<input class="tiny" name="areasecondprice[]" value="" pattern="float" alt="该项必填且只允许填写数字金额" type="text" /></label>
       

        <a  href="javascript:void(0)" class="f_r btnDelete" ><i class="iconfont">&#xf013f;</i></a>
    </div>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/delivery-info.js'); ?>"></script>