<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('system/delivery/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
        </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="col-chk"><input type="checkbox" /></th>
            <th>配送方式</th>
            <th>状态</th>
            <th>物流保价</th>
            <th>货到付款</th>
            <th>排序</th>
            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach( $this->rows as $delivery) : ?>
        <tr>
            <td class="col-center"><input type="checkbox" /></td>
            <td><a href="<?php echo $this->baseUrl('system/delivery/info?delivery_id=' .  $delivery['DeliveryId']); ?>">
                <?php echo $delivery['Name']; ?>
                </a>
            </td>
            <td>
                <?php echo $delivery['Status']; ?>
            </td>
            <td>
                <?php echo $delivery['IsSavePrice']; ?>
            </td>
            <td>
                <?php echo $delivery['PriceType']; ?>
            </td>
            <td>
                <?php echo $delivery['Sort']; ?>
            </td>
            <td>
                <a href="#" href="#" class="btnDelete" data-id="<?php echo $delivery['DeliveryId']; ?>" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/delivery-list.js'); ?>"></script>