<?php
use \Welfony\Utility\Util;
?>
<div class="m-form" >
    <form id="frm-order-info" method="post">
        <fieldset>
            <div id="tabs">
               <ul class="tab" name="menu1">
                    <li id="li_1"><a href="#tab-1" hidefocus="true">基本信息</a></li>
                    <li id="li_2"><a href="#tab-2" hidefocus="true">收退款记录</a></li>
                    <li id="li_3"><a href="#tab-3" hidefocus="true">发货记录</a></li>
                    <li id="li_4"><a href="#tab-4" hidefocus="true">优惠方案</a></li>
                    <li id="li_5"><a href="#tab-5" hidefocus="true">订单备注</a></li>
                    <li id="li_logs"><a href="#tab-logs" hidefocus="true">订单日志</a></li>
                    <li id="li_7"><a href="#tab-7" hidefocus="true">订单附言</a></li>
                </ul>
                <div id="tab-1" name="table" class="o-tab">
                    <div class="formitm">
                        <table class="m-table">
                            <col width="550px" />
                            <col width="100px" />
                            <col width="100px" />
                            <col width="100px" />
                            <col />
                            <thead>
                                <tr>
                                    <th>商品名称</th>
                                    <th>商品原价</th>
                                    <th>实际价格</th>
                                    <th>商品数量</th>
                                    <th>小计</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                $totalWeight = 0;
                                foreach( $this->ordergoods as $ordergoods): 
                                $totalWeight += $ordergoods['GoodsWeight'];
                                    ?>
                                <tr>
                                    <td>
                                        <?php 
                                            $goodName = json_decode($ordergoods['GoodsArray'], true);
                                            echo $goodName["Name"]. '&nbsp;&nbsp;'.$goodName['Value'];
                                        ?>                
                                    </td>
                                    <td><?php   echo $ordergoods['GoodsPrice'] ?></td>
                                    <td><?php   echo $ordergoods['RealPrice'] ?></td>
                                    <td><?php   echo $ordergoods['GoodsNums'] ?></td>
                                    <td><?php   echo $ordergoods['GoodsPrice']*$ordergoods['GoodsNums']; ?></td>
                                </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                    <div style="display:block; width:100%; min-height:700px;">
                        <table style="width:300px;margin-right:20px; height:400px;" class="m-table fl">
                            <thead>
                                <tr><th colspan="2">订单金额明细</th></tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>商品总额:</th><td>￥<?php echo $this->orderInfo['PayableAmount']; ?></td>
                                </tr>
                                <tr>
                                    <th>配送费用:</th><td>￥<?php echo $this->orderInfo['PayableFreight']; ?></td>
                                </tr>
                                <tr>
                                    <th>保价费用:</th><td>￥<?php echo $this->orderInfo['Insured']; ?></td>
                                </tr>
                                <tr>
                                    <th>税金:</th><td>￥<?php echo $this->orderInfo['Taxes']; ?></td>
                                </tr>
                                <tr>
                                    <th>优惠总额:</th><td>￥0.00</td>
                                </tr>
                                <tr>
                                    <th>增加或减少金额:</th><td>￥<?php echo $this->orderInfo['Discount']; ?></td>
                                </tr>
                                <tr>
                                    <th>订单总额:</th><td>￥<?php echo $this->orderInfo['OrderAmount']; ?></td>
                                </tr>
                                <tr>
                                    <th>已支付金额:</th><td></td>
                                </tr>
                            </tbody>
                        </table>

                        <table style="width:300px;margin-right:20px; height:400px;" class="m-table fl">
                            <thead>
                                <tr><th colspan="2">订单其他信息</th></tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>配送方式:</th><td><?php echo $this->delivery['Name']; ?></td>
                                </tr>
                                <tr>
                                    <th>配送保价:</th><td><?php echo $this->orderInfo['IfInsured']? '保价':'否'; ?></td>
                                </tr>
                                <tr>
                                    <th>商品重量:</th><td><?php echo $totalWeight;?></td>
                                </tr>
                                <tr>
                                    <th>支付方式:</th><td><?php echo $this->payment['Name']; ?></td>
                                </tr>
                                <tr>
                                    <th>是否开票:</th><td><?php echo $this->orderInfo['Invoice']? '是':'否'; ?></td>
                                </tr>
                                <tr>
                                    <th>发票抬头:</th><td><?php echo $this->orderInfo['InvoiceTitle']; ?></td>
                                </tr>
                                <tr>
                                    <th>可得积分:</th><td><?php echo $this->orderInfo['Point']; ?></td>
                                </tr>
                            </tbody>
                        </table>

                        <table style="width:300px;margin-right:20px; height:400px;" class="m-table fl">
                            <thead>
                                <tr><th colspan="2">收货人信息</th></tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>发货日期:</th><td><?php echo $this->orderInfo['SendTime']; ?></td>
                                </tr>
                                <tr>
                                    <th>姓名:</th><td><?php echo $this->orderInfo['AcceptName']; ?></td>
                                </tr>
                                <tr>
                                    <th>电话:</th><td><?php echo $this->orderInfo['Telphone']; ?></td>
                                </tr>
                                <tr>
                                    <th>手机 :</th><td><?php echo $this->orderInfo['Mobile']; ?></td>
                                </tr>
                                <tr>
                                    <th>地区:</th><td><?php echo $this->province?$this->province['Name']:''; ?>&nbsp;<?php echo $this->city?$this->city['Name']:''; ?>&nbsp;<?php echo $this->area?$this->area['Name']:''; ?></td>
                                </tr>
                                <tr>
                                    <th>地址:</th><td><?php echo $this->orderInfo['Address']; ?></td>
                                </tr>
                                <tr>
                                    <th>邮编:</th><td><?php echo $this->orderInfo['Postcode']; ?></td>
                                </tr>
                                <tr>
                                    <th>送货时间:</th><td><?php echo $this->orderInfo['AcceptTime']; ?></td>
                                </tr>
                            </tbody>
                        </table>

                        <table style="width:300px;margin-right:20px;" class="m-table fl">
                            <thead>
                                <tr><th colspan="2">商城用户信息</th></tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>用户名:</th><td></td>
                                </tr>
                                <tr>
                                    <th>姓名:</th><td></td>
                                </tr>
                                <tr>
                                    <th>电话:</th><td></td>
                                </tr>
                                <tr>
                                    <th>地区:</th><td></td>
                                </tr>
                                <tr>
                                    <th>Email:</th><td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div id="tab-2" name="table" class="o-tab">
                    <div class="formitm">
                    
                            <table style="width:400px; min-height:500px; display:block;float:left;" class="m-table o-table">
            
                                <thead>
                                    <tr><th colspan="2" style="padding:auto;">收款单据</th></tr>
                                </thead>
                                <tbody>
                                    <tr><td colspan='2'>暂无数据</td></tr>
                                </tbody>
                            </table>

                            <table style="width:400px; min-height:500px; display:block; float:left;" class="m-table o-table">
    
                                <thead>
                                    <tr><th colspan="2">退款单据列表</th></tr>
                                </thead>
                                <tbody>
                                    <tr><td colspan='2'>暂无数据</td></tr>
                                </tbody>
                            </table>
                      
                    </div>
                </div>

                <div id="tab-3" name="table" style="display:none" class="o-tab">
                    <div class="formitm">
                        <table style="width:98%" class="m-table o-table">
                            <thead>
                                <tr><th colspan="2">发货单据列表</th></tr>
                            </thead>
                            <tbody>
                                <tr><td colspan="2">暂无数据</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div id="tab-4" name="table" style="display:none" class="o-tab">
                    <div class="formitm">
                        <table width="98%" class="m-table">
                            <thead>
                                <tr>
                                    <th>方案</th>
                                    <th>优惠内容</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr><td colspan='2'>暂无数据</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div id="tab-5" name="table" style="display:none" class="o-tab">
                    <div class="formitm">
                        <div class="form_content">
                            <input type="hidden" name="tab" value="6"/>
                            <table  class="m-table">
                                <tbody>
                                    <tr>
                                        <th style="width:200px;">订单备注:</th>
                                        <td align="left"><textarea name="note" id="note" rows="8" cols="100"><?php echo $this->orderInfo['Note']; ?></textarea></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td align="left"><button type="button" id="btnSaveOrderNote" class="submit"><span>保存</span></button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div id="tab-logs" name="table" style="display:none" class="o-tab">
                    <div>
                        <table style='width:98%' class="m-table">
                            <thead>
                                <tr>
                                    <th>时间</th>
                                    <th>操作人</th>
                                    <th>动作</th>
                                    <th>结果</th>
                                    <th>备注</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(empty($this->logs)): ?>
                                <tr>
                                    <td colspan="5">暂无数据</td>
                                </tr>
                                <?php else: ?>
                                    <?php foreach($this->logs as $log): ?>
                                    <tr>
                                        <td><?php echo $log['AddTime']; ?></td>
                                        <td><?php echo $log['User']; ?></td>
                                        <td><?php echo $log['Action']; ?></td>
                                        <td><?php echo $log['Result']; ?></td>
                                        <td><?php echo $log['Note']; ?></td>
                                    </tr>
                                    <?php endforeach;?>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div id="tab-7" name="table" style="display:none" class="o-tab">
                    <div class="formitm">
                        <div class="form_content">
                            <table class="m-table">
                                <tbody>
                                    <tr>
                                        <th style="width:200px;">订单附言:</th>
                                        <td align="left"><?php echo $this->orderInfo['Postscript']; ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="pages_bar formitm formitm-1">
                <div class="t_c" id="ctrlButtonArea">
                    <input type="hidden" id="order_id" value="<?php echo $this->orderInfo['OrderId']; ?>"/>
                    <input type="hidden" id="order_no" value="<?php echo $this->orderInfo['OrderNo']; ?>"/>
                    <input type="hidden" id="order_status" value="<?php echo $this->orderInfo['Status']; ?>"/>
                    <button type="button" class="u-btn <?php echo ( $this->orderInfo['PayStatus'] == '1' || $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5)? ' u-btn-disabled ':''; ?>" id="to_pay" <?php echo ( $this->orderInfo['PayStatus'] == '1' || $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5 )? ' disabled="disabled" ':''; ?>><span>支付</span></button>
                    <button type="button" class="u-btn <?php echo ( $this->orderInfo['DistributionStatus'] == '1' || $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5)? ' u-btn-disabled ':''; ?>" id="to_deliver" <?php echo ( $this->orderInfo['DistributionStatus'] == '1' || $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5 )? ' disabled="disabled" ':''; ?>><span>发货</span></button>
                    <button type="button" class="u-btn <?php echo ( $this->orderInfo['PayStatus'] == '0' || $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5) ? ' u-btn-disabled ':''; ?>" id="to_refundment"  <?php echo ( $this->orderInfo['PayStatus'] == '0' || $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5 ) ? ' disabled="disabled" ':''; ?>><span>退款</span></button>
                    <button type="button" class="u-btn <?php echo (  $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5) ? ' u-btn-disabled ':''; ?>" <?php echo (  $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5 ) ? ' disabled="disabled" ':''; ?> id="to_complete"><span>完成</span></button>
                    <button type="button" class="u-btn <?php echo (  $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5) ? ' u-btn-disabled ':''; ?>" <?php echo ( $this->orderInfo['Status'] == '4' || $this->orderInfo['Status'] == 5 ) ? ' disabled="disabled" ':''; ?> id="to_discard"><span>作废</span></button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
<div id="paypopin" style="display:none;">
    <table width="90%" style="margin:10px auto" class="m-table">
        <colgroup><col width="100px">
        <col>
        <col width="100px">
        <col>
        </colgroup><tbody>
            <tr>
                <th>订单号:</th><td align="left"><?php echo $this->orderInfo['OrderNo']; ?></td>
                <th>下单时间:</th><td align="left"><?php echo $this->orderInfo['CreateTime']; ?></td>
            </tr>
            <tr>
                <th>订单总金额:</th><td align="left"><?php echo $this->orderInfo['OrderAmount']; ?></td>
            </tr>
            <tr>
                <th>收款方式:</th>
                <td align="left">
                    <select alt="请选择支付方式" pattern="required" id="pay_payment_id">
                        <?php foreach($this->payments as $payment): ?>
                            <?php if(!$payment['Status']):?>
                            <option <?php echo $payment['PaymentId'] == $this->orderInfo['PayType'] ? ' selected ': ''; ?> value="<?php echo $payment['PaymentId'] ?>"><?php echo $payment['Name'];?></option>
                            <?php endif;?>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <th>收款金额:</th>
                <td align="left" colspan="3">
                    <input type="text" pattern="float" value="<?php echo $this->orderInfo['OrderAmount']; ?>" id="pay_amount" name="amount" class="small">
                    <input type="hidden" id="to_pay_amount" value="<?php echo $this->orderInfo['OrderAmount']; ?>" >
                    <input type="hidden" id="order_user" value="<?php echo $this->orderInfo['UserId']; ?>">
                </td>
            </tr>
            <tr>
                <th>是否开票:</th><td align="left"><?php echo $this->orderInfo['Invoice']?'是':'否'; ?></td>
                <th>税金:</th><td align="left">￥<?php echo $this->orderInfo['Taxes']; ?></td>
            </tr>
            <tr>
                <th>发票抬头:</th><td align="left"><?php echo $this->orderInfo['InvoiceTitle']; ?></td>
                <th>付款人:</th><td align="left"><?php echo $this->orderInfo['UserName']; ?></td>
            </tr>
            <tr>
                <th>收款备注:</th>
                <td align="left" colspan="3">
                    <textarea cols="65" rows="3" id="paynote" name="paynote"></textarea>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="deliverpopin" style="display:none;">
    <table width="90%" style="margin:10px auto" class="m-table">
            <colgroup><col width="100px">
            <col>
            <col width="100px">
            <col>
            </colgroup><tbody>
                <tr>
                    <th>订单号:</th><td align="left"><?php echo $this->orderInfo['OrderNo']; ?></td>
                    <th>下单时间:</th><td align="left"><?php echo $this->orderInfo['CreateTime']; ?></td>
                </tr>
                <tr>
                    <th>配送方式:</th>
                    <td align="left">
                        <select alt="请选择配送方式" pattern="required" id="delivery_type">
                            <?php foreach($this->deliveries as $delivery): ?>
                            <option  <?php echo $delivery['DeliveryId'] == $this->orderInfo['Distribution']? ' selected ':''; ?> value="<?php echo $delivery['DeliveryId']; ?>"><?php echo $delivery['Name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <th>配送费用:</th><td align="left"><?php echo $this->orderInfo['PayableFreight']; ?><input type="hidden" value="<?php echo $this->orderInfo['PayableFreight']; ?>" id="delivery_freight"></td>
                </tr>
                <tr>
                    <th>配送单号:</th><td align="left" colspan="3"><input type="text" pattern="required" id="delivery_code" class="small"></td>
                </tr>
                <tr>
                    <th>是否保价:</th><td align="left"><?php echo $this->orderInfo['IfInsured']? '是':'否'; ?></td><th>保价费用:</th><td align="left">￥<?php echo $this->orderInfo['Insured']; ?></td>
                </tr>
                <tr>
                    <th>收货人姓名:</th><td align="left"><input type="text" pattern="required" value="<?php echo $this->orderInfo['AcceptName']; ?>" id="delivery_accept_name" class="small"></td>
                    <th>电话:</th><td align="left"><input type="text" empty="" pattern="phone" value="<?php echo $this->orderInfo['Telphone']; ?>" id="delivery_telphone" class="small"></td>
                </tr>
                <tr>
                    <th>手机:</th><td align="left"><input type="text" pattern="mobi" value="<?php echo $this->orderInfo['Mobile']; ?>" id="delivery_mobile" class="small"></td>
                    <th>邮政编码:</th><td align="left"><input type="text" empty="" pattern="zip" value="<?php echo $this->orderInfo['Postcode']; ?>" class="small" id="delivery_postcode"></td>
                </tr>
                <tr>
                    <th>地区:</th>
                    <td align="left" colspan="3">
                        
                        <select id="sel-province" name="province" class="u-sel">
                            <option value="">请选择</option>
                            <?php foreach ($this->provinceList as $province): ?>
                            <option value="<?php echo $province['AreaId']; ?>"<?php echo $this->orderInfo['Province'] == $province['AreaId'] ? ' selected="selected" ' : ''; ?>><?php echo $province['Name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <select id="sel-city" name="city" class="u-sel">
                            <option value="">请选择</option>
                            <?php foreach ($this->cityList as $city): ?>
                            <option value="<?php echo $city['AreaId']; ?>"<?php echo $this->orderInfo['City'] == $city['AreaId'] ? ' selected="selected" ' : ''; ?>><?php echo $city['Name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <select id="sel-district" name="district" class="u-sel" datatype="*">
                            <option value="">请选择</option>
                            <?php foreach ($this->districtList as $district): ?>
                            <option value="<?php echo $district['AreaId']; ?>"<?php echo $this->orderInfo['Area'] == $district['AreaId'] ? ' selected="selected" ' : ''; ?>><?php echo $district['Name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th>地址:</th><td align="left" colspan="3"><input type="text" pattern="required" size="50" value="<?php echo $this->orderInfo['Address']; ?>" id="delivery_address" class="normal"></td>
                </tr>
                <tr>
                    <th>发货单备注:</th><td align="left" colspan="3"><textarea cols="85" rows="3" id="delivery_note"></textarea></td>
                </tr>
            </tbody>
        </table>
        <table width="100%" style="margin:10px auto" class="m-table">

            </colgroup><thead>
                <tr><th>商品名称</th><th>商品价格</th><th>购买数量</th></tr>
            </thead>
            <tbody>
                <?php foreach( $this->ordergoods as $ordergoods): ?>
                <tr>
                    <td>
                        <?php 
                            $goodName = json_decode($ordergoods['GoodsArray'], true);
                            echo $goodName["Name"]. '&nbsp;&nbsp;'.$goodName['Value'];
                        ?>                
                    </td>
                    <td><?php   echo $ordergoods['RealPrice'] ?></td>
                    <td><?php   echo $ordergoods['GoodsNums'] ?></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
</div>
<div id="refoundpopin" style="display:none;">
    <table width="95%" style="margin:10px auto" class="m-table">
       <tbody>
            <tr>
                <th>订单号:</th><td align="left"><?php echo $this->orderInfo['OrderNo']; ?></td>
                <th>下单时间:</th><td align="left"><?php echo $this->orderInfo['CreateTime']; ?></td>
            </tr>
            <tr>
                <th>订单总金额:</th><td align="left"><?php echo $this->orderInfo['OrderAmount']; ?></td>
                <th>退款金额:</th><td align="left"><input type="text" pattern="float" value="<?php echo $this->orderInfo['OrderAmount']; ?>" id="refund_amount"  class="small"></td>
            </tr>
            <tr>
                <th>说明：</th>
                <td align="left" colspan="3">点击退款后，&lt;退款金额&gt;将直接转入到用户的余额中</td>
            </tr>
        </tbody>
    </table>
</div>

<script src="<?php echo Util::baseAssetUrl('js/backend/order-detail.js'); ?>"></script>