<?php
use \Welfony\Utility\Util;
?>
<div class="m-form">
    <form id="frm-order-info" method="post">
        <fieldset>
            <div id="tabs">
                <ul>
                    <li><a href="#tabs-1">商品信息</a></li>
                    <li><a href="#tabs-2">订单配置</a></li>
                    <li><a href="#tabs-3">收货人信息</a></li>
                </ul>
                <div id="tabs-1">
                    <div class="formitm">
                        <label class="lab"> 添加： </a></label>
                        <div class="ipt">
                            <a class="t-action" id="btnAddGoods"><i class="iconfont">&#xf0175;</i>添加商品</a>
                        </div>
                    </div>
                    <div>
                        <label class="lab"></label>
                        <div class="ipt">
                            <table class="m-table" id="goodstable">
                                 <thead>
                                    <tr>
                                        <th class="cola">商品名称</th>
                                        <th class="cola">沙龙</th>
                                        <th class="cola">商品价格</th>
                                        <th class="cola">数量</th>
                                        <th class="cola">操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach( $this->ordergoods as $goods) :?>
                                    <?php 
                                        $goodsarray = json_decode($goods['GoodsArray'],true);
                                        $goodsname= $goodsarray['Name'];
                                    ?>
                                    <tr class="goodsid" data-id="<?php echo $goods['GoodsId'].'_'.$goods['ProductsId']; ?>">

                                            <td><?php echo $goodsname; ?></td>
                                            <td><?php echo isset($goods['CompanyName'])? $goods['CompanyName']:''; ?></td>
                                            <td><?php echo $goods['GoodsPrice']; ?></td>

                                            <td><input type="text" name="goodscount" value="<?php echo $goods['GoodsNums']; ?>"/>
                                            <input type="hidden" name="goodsid" value="<?php echo $goods['GoodsId']; ?>" />
                                                <input type="hidden" name="productsid" value="<?php echo $goods['ProductsId']; ?>"/>
                                                <input type="hidden" name="goodsname" value="<?php echo $goodsname; ?>"/>
                                                <input type="hidden" name="goodsspec" value="<?php echo $goodsarray['Value']; ?>"/>
                                                <input type="hidden" name="weight" value="<?php echo $goods['GoodsWeight']; ?>" />
                                                <input type="hidden" name="sellprice" value="<?php echo $goods['GoodsPrice']; ?>"/>
                                                <input type="hidden" name="goodsimg" value="<?php echo $goods['Img']; ?>"/>
                                                <input type="hidden" name="companyid" value="<?php echo $goods['CompanyId']; ?>"/>
                                            </td>
                                            <td><a href="#" class="btnDelete"><i class="iconfont">&#xf013f;</i></a></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div id="tabs-2">

                    <div class="formitm">
                        <label class="lab">订单号：</label>
                        <div class="ipt">
                            <input id="orderno" type="text"  datatype="*" value="<?php echo $this->orderno; ?>"  errormsg="名称不能为空！" class="u-ipt"/> *
                        </div>
                    </div>

                    <div class="formitm">
                        <label class="lab">配送方式：</label>
                        <div class="ipt">
                            <select class="u-sel" id="distribution">
                                <?php foreach($this->deliveries as $delivery): ?>
                                    <?php if($delivery['Status']):?>
                                    <option value="<?php echo $delivery['DeliveryId']; ?>" 
                                        <?php echo $this->orderInfo['Distribution'] == $delivery['DeliveryId'] ? 'selected' : ''; ?>><?php echo $delivery['Name']; ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">支付方式：</label>
                        <div class="ipt">
                            <select class="u-sel" id="paytype">
                                <?php foreach($this->payments as $payment): ?>
                                <option value="<?php echo $payment['PaymentId']; ?>" <?php echo $this->orderInfo['PayType'] == $payment['PaymentId'] ? 'selected' : ''; ?>><?php echo $payment['Name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="formitm">
                        <label class="lab">是否保价：</label>
                        <div class="ipt">
                             <span class="u-btns" data-type="radio">
                                <span class="u-btn <?php echo $this->orderInfo['IfInsured']? 'u-btn-c3':'u-btn-c4'; ?>" data-value="1" name="ifinsured">是</span>
                                <span class="u-btn <?php echo $this->orderInfo['IfInsured']? 'u-btn-c4':'u-btn-c3'; ?>" data-value="0" name="ifinsured" >否</span>
                             </span>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">是否发票：</label>
                        <div class="ipt">
                            <span class="u-btns" data-type="radio">
                                <span class="u-btn <?php echo $this->orderInfo['Invoice']? 'u-btn-c3':'u-btn-c4'; ?>" data-value="1" name="invoice" >是</span>
                                <span class="u-btn <?php echo $this->orderInfo['Invoice']? 'u-btn-c4':'u-btn-c3'; ?>" data-value="0" name="invoice">否</span>
                             </span>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">发票抬头：</label>
                        <div class="ipt">
                            <input  type="text" id="invoicetitle" value="<?php echo $this->orderInfo['InvoiceTitle']; ?>"  class="u-ipt"/> *
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">指定送货时间：</label>
                        <div class="ipt">
                            <label class="attr"><input type="radio" value="任意" <?php echo $this->orderInfo['AcceptTime'] == '任意'? 'checked':''; ?> name="accept_time">任意</label>
                            <label class="attr"><input type="radio" value="周一到周五" <?php echo $this->orderInfo['AcceptTime'] == '周一到周五'? 'checked':''; ?> name="accept_time">周一到周五</label>
                            <label class="attr"><input type="radio" value="周末" <?php echo $this->orderInfo['AcceptTime'] == '周末'? 'checked':''; ?> name="accept_time">周末</label>
                        </div>
                    </div>

                    <div class="formitm">
                        <label class="lab">订单折扣或涨价：</label>
                        <div class="ipt">
                            <input id="discount" type="text"  value="<?php echo $this->orderInfo['Discount']; ?>"  class="u-ipt"/>￥
                            <p>折扣用" - ",涨价用" + "</p>
                        </div>
                    </div>

                    
                </div>
                <div id="tabs-3">
                    <div class="formitm">
                        <label class="lab">所属用户名：</label>
                        <div class="ipt">
                            <input id="username" type="text" data-id="<?php echo $this->orderInfo['UserId']; ?>" value="<?php echo $this->orderInfo['UserName']; ?>"  class="u-ipt"/>
                            <p>订单所属于的用户，直接填写用户名，订单创建后与该用户绑定在一起，如果为空则为游客订单或者线下订单</p>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">收货人姓名：</label>
                        <div class="ipt">
                            <input id="acceptname" type="text"  value="<?php echo $this->orderInfo['AcceptName']; ?>"  class="u-ipt"/>
                            <p></p>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">地区：</label>
                        <div class="ipt v-l-650">
                            <select id="sel-province" name="province" class="u-sel">
                                <option value="">请选择</option>
                                <?php foreach ($this->provinceList as $province): ?>
                                <option value="<?php echo $province['AreaId']; ?>"<?php echo $this->orderInfo['Province'] == $province['AreaId'] ? ' selected' : ''; ?>><?php echo $province['Name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                            <select id="sel-city" name="city" class="u-sel">
                                <option value="">请选择</option>
                                <?php foreach ($this->cityList as $city): ?>
                                <option value="<?php echo $city['AreaId']; ?>"<?php echo $this->orderInfo['City'] == $city['AreaId'] ? ' selected' : ''; ?>><?php echo $city['Name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                            <select id="sel-district" name="district" class="u-sel">
                                <option value="">请选择</option>
                                <?php foreach ($this->districtList as $district): ?>
                                <option value="<?php echo $district['AreaId']; ?>"<?php echo $this->orderInfo['Area'] == $district['AreaId'] ? ' selected' : ''; ?>><?php echo $district['Name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="formitm">
                        <label class="lab">收货地址：</label>
                        <div class="ipt">
                            <input id="address" type="text"  value="<?php echo $this->orderInfo['Address']; ?>"  class="u-ipt"/>
                            <p></p>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">联系手机：</label>
                        <div class="ipt">
                            <input id="mobile" type="text"  value="<?php echo $this->orderInfo['Mobile']; ?>"  class="u-ipt"/>
                            <p></p>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">联系电话：</label>
                        <div class="ipt">
                            <input id="telphone" type="text"  value="<?php echo $this->orderInfo['Telphone']; ?>"  class="u-ipt"/>
                            <p></p>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">邮编：</label>
                        <div class="ipt">
                            <input id="postcode" type="text"  value="<?php echo $this->orderInfo['Postcode']; ?>"  class="u-ipt"/>
                            <p></p>
                        </div>
                    </div>
                    <div class="formitm">
                        <label class="lab">用户附言：</label>
                        <div class="ipt">
                           <textarea class="u-ipt"  type="text" id="postscript"><?php echo $this->orderInfo['Postscript']; ?></textarea>
                            <p></p>
                        </div>
                    </div>
                    
                </div>
            </div>
     
            
            
            <div class="formitm formitm-1">
                <input type="hidden" name="order_id" value="<?php echo intval($this->orderInfo['OrderId']); ?>" />
                <button class="u-btn u-btn-submit" type="button">确定</button>
                <button class="u-btn" id="btnCancel" type="button">取消</button>
            </div>
        </fieldset>
    </form>
</div>
<div id="goodsList" style="display:none;" title="商品列表">

</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/order-info.js'); ?>"></script>