 <div>
    <table style='width:98%' class="m-table">
        <thead>
            <tr>
                <th>时间</th>
                <th>操作人</th>
                <th>动作</th>
                <th>结果</th>
                <th>备注</th>
            </tr>
        </thead>
        <tbody>
            <?php if(empty($this->logs)): ?>
            <tr>
                <td colspan="5">暂无数据</td>
            </tr>
            <?php else: ?>
                <?php foreach($this->logs as $log): ?>
                <tr>
                    <td><?php echo $log['AddTime']; ?></td>
                    <td><?php echo $log['User']; ?></td>
                    <td><?php echo $log['Action']; ?></td>
                    <td><?php echo $log['Result']; ?></td>
                    <td><?php echo $log['Note']; ?></td>
                </tr>
                <?php endforeach;?>
            <?php endif; ?>
        </tbody>
    </table>
</div>