<?php
use \Welfony\Utility\Util;
?>
<div class="toolbar">
    <ul class="clearfix">
        <li>
            <a href="<?php echo $this->baseUrl('order/index/info'); ?>">
                <i class="iconfont">&#xf0175;</i>
                添加
            </a>
      </li>
    </ul>
</div>
<table class="m-table">
    <thead>
        <tr>
            <th class="colb" style="width:138px;">订单号</th>
            <th class="cola">收货人</th>
            <th>支付状态</th>
            <th>发货状态</th>
            <th>配送方式</th>
            <th>支付方式</th>
            <th class="cola">用户</th>
            <th class="cola">下单时间</th>
            <th class="cola">操作</th>
        </tr>
    </thead>
    <tbody>
      <?php foreach( $this->rows as $order) : ?>
        <tr>
            <td>                    
                <?php echo $order['OrderNo']; ?>
            </td>
            <td> <?php echo $order['AcceptName']; ?></td>
            <td> <?php echo $order['PayStatus']? ( $order['PayStatus']== '1' ? '已支付': '退款'):'未支付'; ?></td>
            <td> <?php echo $order['DistributionStatus']?'已发送':'未发送'; ?></td>
            <td> <?php echo $order['DeliveryName']; ?></td>
            <td><?php echo $order['PaymentName']; ?></td>
            <td><?php echo $order['UserName']; ?></td>
            <td><?php echo $order['CreateTime']; ?></td>
            <td>
                 <a href="<?php echo $this->baseUrl('order/index/detail?order_id=' .  $order['OrderId']); ?>">
                    <i class="iconfont">&#xf0198;</i>&nbsp;&nbsp;详情
                </a>
                <?php if($order['IsDeleted'] || $order['Status'] == '4' || $order['Status'] == '5' ): ?>
                <?php else: ?>
                <a href="<?php echo $this->baseUrl('order/index/info?order_id=' .  $order['OrderId']); ?>">
                    <i class="iconfont"> &#xf0022;</i>&nbsp;&nbsp;编辑
                </a>
                <?php endif;?>
               
                <?php if(!$order['IsDeleted']): ?>
                <a href="#" href="#" class="btnDelete" data-id="<?php echo $order['OrderId']; ?>" >
                    <i class="iconfont">&#xf013f;</i>&nbsp;&nbsp;删除
                </a>
                <?php endif;?>

            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="m-page m-page-rt">
    <?php echo $this->pagerHTML; ?>
</div>
<script src="<?php echo Util::baseAssetUrl('js/backend/order-list.js'); ?>"></script>